### ISSUE TITLE
Unable to fully maximize app windows

### ISSUE THREAD

**Issue by JaidenIsDumb** [dremin/RetroBar#102]
I tried maximizing but it did not fully maximize the app windows and was able to see my wallpaper :>

**Comment by dremin** [comment]
Is this occurring with every app or only specific apps?

**Comment by dremin** [comment]
I believe this should now be fixed in [this test build](https://github.com/dremin/RetroBar/suites/5272119818/artifacts/162979122) (link requires GitHub login). Would you be able to verify if that version works correctly for you?

**Comment by dremin** [comment]
Closing due to likely fix and lack of response.
