### ISSUE TITLE
[Suggestion] Please somehow make the RetroBar scalable on large res monitors

### ISSUE THREAD

**Issue by miljann** [dremin/RetroBar#107]
I would suggest (if possible) to somehow make this retro bar scalable on high res monitors, since it is very very small on 5k resolution on 27'' monitor :(

Other than that, it is awesome 👍

**Comment by dremin** [comment]
RetroBar should already scale to your DPI scaling settings in Windows- or are you only using 100% scaling?

**Comment by dremin** [comment]
Additional scaling past the Windows setting is not planned. However, if RetroBar is not scaling according to Windows settings, that would be a bug that we can look at separately.
