### ISSUE TITLE
Some issues reported

### ISSUE THREAD

**Issue by Anixx** [dremin/RetroBar#11]
Thank you for this program! On WinClassic forum user Clasurol [reported](https://winclassic.boards.net/post/6936) the following issues, mostly with system tray:

- System tray icons seem to disappear at random: 3RVX icon's seems to go missing on it's own, forcing me to restart RetroBar to get it back.
- System tray programs that allow you to customize them (e.g. WatchCat) defaults to the original icon.
- Not all icons show.
- Network flyout icon shows regardless what your settings are (I have it disabled).

**Comment by dremin** [comment]
Are these issues still occurring in the latest release? I made some changes which should make a positive impact.

**Comment by dremin** [comment]
Closing since this issues should be resolved now.
