### ISSUE TITLE
System auto start up?

### ISSUE THREAD

**Issue by teddyursa** [dremin/RetroBar#12]
I love this program, after using a jank Window Blinds theme - this bar is actually accurate! But I have to run the exe manually each time - how can I get this to run on boot?

Thanks.

**Comment by Clasurol** [comment]
Create a shortcut and drop it into "C:\Users\YOURNAME\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup".

**Comment by dremin** [comment]
This is now in the properties window in the latest release.
