### ISSUE TITLE
Task list too big? Windows 11 Pro 21H2 22000.258

### ISSUE THREAD

**Issue by yellowwinner** [dremin/RetroBar#124]
I have the latest RetroBar v1.4.42 and am having issues with the task list. Essentially when nothing is open everything seems fine but the second I open a program the little up-down buttons show up to scroll a single pixel.
![1](https://user-images.githubusercontent.com/16910272/137683281-9ec0702e-f3f2-44c7-bf9e-6a9aa7b31e9f.png)
![2](https://user-images.githubusercontent.com/16910272/137683283-e8269569-9662-4134-b394-63b8757dfd15.png)

**Comment by dremin** [comment]
What DPI / scaling setting is your display set to?

**Comment by yellowwinner** [comment]
> What DPI / scaling setting is your display set to?

Issue still occurs on current version with scaling set to 125% (My laptops default) changing to 100% or 150% fixes but prefer to keep my device at 125%

**Comment by dremin** [comment]
This will be fixed in the next release, it is a duplicate of #314.
