### ISSUE TITLE
Loads of info but missing the one main bit.....

### ISSUE THREAD

**Issue by UberMicro** [dremin/RetroBar#126]
HOW TO INSTALL???

![image](https://user-images.githubusercontent.com/77238605/138045207-d1aca944-c86b-4435-b6ef-61151dacadac.png)

What do i do with this crap?!

**Comment by xoascf** [comment]
Ok, I get your point, GitHub changed their design again, no one is to blame here.
And that wasn't "crap", just source code that can be compiled.

The .exe is here:
![RetroBarDL](https://user-images.githubusercontent.com/28744392/138151631-0905c5f2-3007-47fc-a847-d88c7c30ff63.gif)
