### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by M1ghty-boy** [dremin/RetroBar#127]
Hey, just started using this on my main Win11 PC. great stuff. I do have a couple feature requests however.

1. scale option (it's already kinda small on a 1080p display, cant imagine on a 4k)
2. icon only/hide window title
3. multi monitor option - this program only shows the taskbar on the primary display. would be nice to have multi display options
4. show regular right click menu that youd see when right clicking taskbar, with the retrobar options and whatnot at the bottom or in a submenu

**Comment by dremin** [comment]
Item 3 has been added to RetroBar since this was opened. Regarding item 1, RetroBar will use the system scaling setting.

Windows 7 features are not planned, as the Windows 10 (and 11 with patches) taskbar has these features and theming utilities exist for these.
