### ISSUE TITLE
Hebrew / Arabic right to left language support

### ISSUE THREAD

**Issue by novatiberium** [dremin/RetroBar#128]
I've recently just heard of RetroBar not so long ago, and it's great. The only issue for me is, because I use the Hebrew version of the Windows operating system for critical reasons, RetroBar looks like a weird frankenstein when it's not fitting with the language I use. It would be nice if we can add Right-to-Left language support and languages for RetroBar, because the languages we have are only left-to-right.

**Comment by xoascf** [comment]
Closed by #132
