### ISSUE TITLE
Doesn't support 2 monitors

### ISSUE THREAD

**Issue by SIX10** [dremin/RetroBar#13]
When started it doesn't also use my second monitor.
![Screenshot_3](https://user-images.githubusercontent.com/34385243/116637347-46b5b980-a929-11eb-813c-deeb33c0cd87.jpg)

**Comment by oblicue** [comment]
yeah

**Comment by dremin** [comment]
Could you clarify what is the desired behavior in this scenario? The versions of Windows that RetroBar emulates do not show a taskbar on secondary monitors.

**Comment by binamracode** [comment]
It should show taskbar in both monitors

**Comment by ob14** [comment]
> Could you clarify what is the desired behavior in this scenario? The versions of Windows that RetroBar emulates do not show a taskbar on secondary monitors.

Windows allows you to show a taskbar on all monitors, as as a single taskbar on any monitor, as well as on top, on the side, etc.

**Comment by pmache** [comment]
> > Could you clarify what is the desired behavior in this scenario? The versions of Windows that RetroBar emulates do not show a taskbar on secondary monitors.
> 
> Windows allows you to show a taskbar on all monitors, as as a single taskbar on any monitor, as well as on top, on the side, etc.

I believe that dremin is alright. I don't remember that XP allowed to show taskbar on all monitors.

**Comment by ItsBrickblocks** [comment]
I agree, the taskbar itself works great. It would be nice as a QoL thing to have multi-monitor taskbar support.

**Comment by theLucy** [comment]
It emulates Windows XP behaviour, but I think back in the XP days most setups only ever had a single monitor. I think it would not break stile too much and if it is not too hard to implement too. to have a taskbar on each monitor.

**Comment by DavidXanatos** [comment]
Yes a multi monitor swupport is needed, i have 6 monitors so can use this awsome tool right now but when Win 11 hits this toll will become mandators!

I use one taskbar per monitor showing only programs on that monitor.

**Comment by WildFyr16** [comment]
I also agree that having an option to bring up the taskbar on multiple displays is almost mandatory here in 2021, the biggest issue I get when playing any game that is in Window Borderless is I lose access to my taskbar altogether, even on my multiple other monitors where the taskbar is normally it is gone, then to try and access my taskbar at that point I would need to use task manager to close retro bar as I can't even right-click on it as it is hidden behind the game. If you do add this feature please let me know how I will be able to add it to my own program as well as this is defiantly a needed update. Realistic or XP/ME/2000/1995/ect. or not for me is off the table as a lot of things have changed sinse the release of those operating sytems anyway.

**Comment by ignotusPev** [comment]
Yeah the taskbar its beautiful but would be better if it had support for 2 monitors

**Comment by SIX10** [comment]
@dremin Please reconsider adding this, just as an option. Even if it wasn't present in the original XP builds, it is a massive QoL improvement and would make this taskbar PERFECT.

**Comment by SIX10** [comment]
I created my own fork that supports multiple displays. Right now, it just puts the exact same taskbar on all displays. Will implement as an option in the future. https://github.com/SIX10/RetroBar

**Comment by SIX10** [comment]
> 
> 
> Yes a multi monitor swupport is needed, i have 6 monitors so can use this awsome tool right now but when Win 11 hits this toll will become mandators!
> 
> I use one taskbar per monitor showing only programs on that monitor.

I saw you hearted my last response, so I'm assuming you've tried the fork. Does it work on all 6 of your displays? I only have two. The only issue I've noticed is when opening the start menu it opens on your primary monitor, but that might be just OpenShell.

**Comment by DavidXanatos** [comment]
I havn't tryed as i still use windows 10 in production, w11 only in VM's but I'll put it on my work laptop soon there i have only 3 screens + laptop but when it works on those it wil work on my 6 @home as well

**Comment by dremin** [comment]
This is now available as an option in the latest release!

**Comment by SMUsamaShah** [comment]
Thank you :)

**Comment by SMUsamaShah** [comment]
Each display is showing all the apps from all displays. Can something be done about it? It isn't a very useful behaviour.

**Comment by SIX10** [comment]
> 
> 
> Each display is showing all the apps from all displays. Can something be done about it? It isn't a very useful behaviour.

I think this is intended, it's useful when you're in a fullscreen app on one screen and not on another.

**Comment by SMUsamaShah** [comment]
My left screen has taskbar on left side, right one has taskbar on right. Each screen has lots of things of their own. It becomes a hinderance in my case because I click a button on screen 1 hoping to show up on the same screen whiles its actually on the other one.

**Comment by SIX10** [comment]
> My left screen has taskbar on left side, right one has taskbar on right. Each screen has lots of things of their own. It becomes a hinderance in my case because I click a button on screen 1 hoping to show up on the same screen whiles its actually on the other one.

So you're clicking a taskbar app icon on one screen, hoping for it to show up on the same one, but it shows up on another screen?

I don't think this is a RetroBar problem, but just Windows behavior. The same thing happens when using the Windows 10 taskbar.

**Comment by xoascf** [comment]
> 
> 
> > My left screen has taskbar on left side, right one has taskbar on right. Each screen has lots of things of their own. It becomes a hinderance in my case because I click a button on screen 1 hoping to show up on the same screen whiles its actually on the other one.
> 
> So you're clicking a taskbar app icon on one screen, hoping for it to show up on the same one, but it shows up on another screen?
> 
> I don't think this is a RetroBar problem, but just Windows behavior. The same thing happens when using the Windows 10 taskbar

@SMUsamaShah is not wrong, this is something that is already implemented in Windows, and is really useful.
I assume @SMUsamaShah is referring to this feature:
![image_2021-11-10_17-14-23](https://user-images.githubusercontent.com/28744392/141202683-55f63c42-b59d-415c-bdde-06fd04424972.png)

**Comment by robin2715** [comment]
> this is intended, it's useful when you're in a fullscreen

I agree with this comment. This would be a useful feature. Once again, it was not present in the original windows build, but it would be highly useful. Is it something easy to tweak?

**Comment by ulao** [comment]
I came here from explorer patcher, Retrobar is nice because windows 11 does not seem to attack it like it does Explorer patcher, but retrobar has one HUGE problem, does not support two monitors... That is almost a given today, A major must. I use 5 montiors and the task back must be on all 5, This is a let down, otherwise love this tool!


Another feature that windows has is that application minimmize ont he taskbar of the windows. So minimize windows X on monitor A will be on task bar A. 
minimize windows Y on monitor B will be on task bar B. 
Kind of a big deal also...

**Comment by dremin** [comment]
> I came here from explorer patcher, Retrobar is nice because windows 11 does not seem to attack it like it does Explorer patcher, but retrobar has one HUGE problem, does not support two monitors... That is almost a given today, A major must. I use 5 montiors and the task back must be on all 5, This is a let down, otherwise love this tool!
> 
> 
> Another feature that windows has is that application minimmize ont he taskbar of the windows. So minimize windows X on monitor A will be on task bar A. 
> minimize windows Y on monitor B will be on task bar B. 
> Kind of a big deal also...
> 

Hi! Could you please clarify what functionality you're not finding? RetroBar has gained both of those features since this issue was originally submitted. You can configure how RetroBar handles multiple monitors in the Properties window, in the Advanced tab.

**Comment by ulao** [comment]
Hi, I foudn the options, thx! It was not on by default and I could not find any options at first. 

Another features ( maybe hidden in setting?) was the preview if you hover over the task back tab, it shows the window its accociated with.

**Comment by dremin** [comment]
> Hi, I foudn the options, thx! It was not on by default and I could not find any options at first. 
> 
> Another features ( maybe hidden in setting?) was the preview if you hover over the task back tab, it shows the window its accociated with. 
> 
> 

That feature is also available in the properties window, "show window previews."

**Comment by ulao** [comment]
ah ok, I see it thx!
