### ISSUE TITLE
Created an account just for this issue..

### ISSUE THREAD

**Issue by needhelpwiththings** [dremin/RetroBar#130]
Don't really know how to fix this as I don't know how to code or anything so I can hopefully fix this issue, and I'm hoping a new version gets released soon for Windows 11 because I really want this fixed but why do my tabs look like this every so often? I'm guessing people have the same issue as I do.
![Screenshot 2021-10-24 091327](https://user-images.githubusercontent.com/93090649/138602888-f54e43c0-023b-4834-9c43-989e31469b72.png)

**Comment by dremin** [comment]
I'll try to get a test version with software rendering to see if this is a GPU/driver issue.

**Comment by needhelpwiththings** [comment]
Thank you both! Also @xoascf I am not sure if I do or not. I will check.
Thank you all so much for the support!

**Comment by brownje96** [comment]
I entirely recant to having any resolution. I thought it was fixed, but it reared its ugly head again. I did not have this problem initially with RetroBar, but had a sudden onset of it. Common enough problem with any software and a likely dumb end-user (me). After deleting all files generated in AppData, and regardless of using 1.4 or 1.3, this graphical problem persists. 

Per @xoascf's question, I do have such drivers, although I do not have them configured (to my knowledge...) past their defaults. I have no interest in overclocking. I do wish they were optional, but they're seemingly not. They come with the chipset drivers for my computer. A DELL Inspiron G5 5505 SE.

**Comment by dremin** [comment]
[Here is a build that uses software rendering.](https://github.com/dremin/RetroBar/suites/4294663095/artifacts/111994424) Please give it a go and see if it solves your issue. (You'll need to be logged into GitHub for that link to work.)

**Comment by needhelpwiththings** [comment]
I tried it and yes, it does seem to work so far! Thank you so much!

**Comment by dremin** [comment]
Yay, glad to hear it! And to confirm as a baseline, if you download and run the official 1.5 release the issue re-appears? If so, I'll go ahead and add software rendering as a setting in the next official release.

**Comment by brownje96** [comment]
I can confirm as well that there are no weird rendering problems with the software rendering enabled build. Thank you @dremin

**Comment by xoascf** [comment]
Since this is a hardware rendering problem, could @brownje96 and @needhelpwiththings try this updated version of #153 ([link](https://github.com/dremin/RetroBar/suites/4346223570/artifacts/114015043)), which includes a toggleable option for this feature.

You can try it this way: the option is disabled by default, when the graphics problem occurs you should enable it immediately in the Properties window, the taskbar should update without the corruption (no need to restart) and save the configuration so that it no longer appears, if that fixes this issue, then this change will have to be applied.

**Comment by brownje96** [comment]
@xoascf I can confirm that the application behaves exactly as you've described.

**Comment by dremin** [comment]
Awesome, thanks for checking!

**Comment by dremin** [comment]
This should now be addressed with the new option to enable software rendering in the latest release.
