### ISSUE TITLE
Switching Virtual Desktops Results in Mixed Taskbar Elements

### ISSUE THREAD

**Issue by ghost** [dremin/RetroBar#131]
Hi there!

Windows 10 introduced virtual desktops.
Sadly RetroBar doesn't support them yet.
When switching from one virtual desktop to another, the taskbars get mixed up and fails to show the right tasks.
I'd love to see this getting fixed.

What a great projekt! I love it!
Thanks!

**Comment by fan-young** [comment]
The issue remains

**Comment by dremin** [comment]
This is now fixed in the latest release.

**Comment by dchaploeb** [comment]
Is there a way to add a task view button to retrobar?  (I know I can press WIN-TAB, and I do, but I would like a button I can click on).
