### ISSUE TITLE
No way of accessig windows 10 notification tray

### ISSUE THREAD

**Issue by Jonson26** [dremin/RetroBar#146]
As of today, there seems to be no way of accessing the windows 10 action center. A possible workaround could be a simple optional notification area icon.

**Comment by xoascf** [comment]
For now, just click on the clock and the notification center will appear, [as in Windows 11](https://support.microsoft.com/windows/find-your-notifications-cccdb22c-bda9-5ad5-897d-897ac67f7e39#WindowsVersion=Windows_11).

**Comment by dremin** [comment]
I'll expand the Windows 11 feature to 10. Not sure why I left 10 out, to be honest.

**Comment by dremin** [comment]
In the latest release you can single-click the clock to open this.
