### ISSUE TITLE
Cannot move elements on the taskbar

### ISSUE THREAD

**Issue by Jonson26** [dremin/RetroBar#147]
It seems to be impossible to change the position of tasks on the taskbar.

**Comment by kwagraphics** [comment]
Yes! Maybe if we could unlock the taskbar we could move the system tray icons.

I really like this, but I like my system tray icons is a specific order. As well as my taskbar icons. Can't move them with it locked.

**Comment by dremin** [comment]
Closing as duplicate of #19, which should be fixed in the next release.
