### ISSUE TITLE
Add Windows vista Theme

### ISSUE THREAD

**Issue by Areoxsa** [dremin/RetroBar#15]
Would be very nice if u can add the Windows vista Taskbar Theme because i love the Design of it

and add more features like Old clock system and Change Icons

**Comment by shakeyourbunny** [comment]
Oh yes please, this is sorely missing here.

**Comment by dremin** [comment]
I agree! I'd also like to add some of the earlier Longhorn themes--Plex, Jade, etc.

**Comment by Splitwirez** [comment]
@dremin You and me both. I'd love to pitch in with the Longhorn and Vista skins...though I've had some thoughts about how Retrobar skinning in general could be improved. I'll be opening an issue about that shortly, so...that should probably come first, if you're open to what I have in mind.

**Comment by XTMYTYT** [comment]
When will windows vista Theme release

**Comment by samiscoolest** [comment]
Add the vista era icons especially, the win10 volume network and battery icons don't look good with classic theme default colors.

**Comment by achmadsutardi441953** [comment]
This image
![bountypaid-for-increasing-windows-vista-taskbar-preview-size](https://user-images.githubusercontent.com/30205044/125409822-7e8bb380-e3e6-11eb-8820-b494dc863035.png)
![C](https://user-images.githubusercontent.com/30205044/125409950-9b27eb80-e3e6-11eb-9eee-a4d10b40828f.png)
![79378 image0](https://user-images.githubusercontent.com/30205044/125409956-9c591880-e3e6-11eb-8ce0-d89c9f6fe4f3.jpg)

**Comment by CodeRabbid64** [comment]
@dremin please add this!

**Comment by ColdSalt09** [comment]
![εικόνα](https://user-images.githubusercontent.com/77743845/157740676-0f47fe25-4d08-447e-9644-8c093ada2b89.png)

**Comment by ColdSalt09** [comment]
![εικόνα](https://user-images.githubusercontent.com/77743845/159043008-63285f51-ec01-4514-ae16-4f1651b72b39.png)

**Comment by shakeyourbunny** [comment]
Already switched to a better Windows, called SuSE Tumbleweed.

**Comment by ColdSalt09** [comment]
@shakeyourbunny we dont care

**Comment by XTMYTYT** [comment]
bro coldsalt09 the image  u send was true

**Comment by XTMYTYT** [comment]
add windows vista theme :dremin yes i will 1 year later bruh where is it? im waiting and im with my skeleton body

**Comment by ColdSalt09** [comment]
oooh @dremin cmon its likely been a year retrobar users waiting for vista theme

**Comment by dremin** [comment]
[Here's a preview build](https://github.com/dremin/RetroBar/suites/7332533657/artifacts/296859081) you can try that includes the upcoming Vista themes. (64-bit version, GitHub login required) Note that .NET 6 is required now, so you'll be prompted to install it if you haven't already.

**Comment by shakeyourbunny** [comment]
Some observations:
- if you have NEVER started RetroBar and there is no configuration on the system of an earlier build, this build just silently crashes.
- after installing RetroBar 1.8 (most recent regular build), closing it and then starting the preview build, it will run; but there is no "Windows Vista" (only the classic) option in the menu available.

Windows Version: 21H2 (19044.1766)
Dot Net 6 Runtime: windowsdesktop-runtime-6.0.0-win-x64.exe

Note that if there was no dot net runtime installed, it will redirect to the Windows dotnet Runtime 6.0 site which installs the runtime, but without the needed libraries for the Windows Desktop ... so RetroBar asks again again again again for the dotnet runtime if you don't install the "full" dotnet 6.0 runtime (27 MB vs 54 MB download).

**Comment by dremin** [comment]
> Some observations:
> 
>     * if you have NEVER started RetroBar and there is no configuration on the system of an earlier build, this build just silently crashes.
> 
>     * after installing RetroBar 1.8 (most recent regular build), closing it and then starting the preview build, it will run; but there is no "Windows Vista" (only the classic) option in the menu available.
> 
> 
> Windows Version: 21H2 (19044.1766) Dot Net 6 Runtime: windowsdesktop-runtime-6.0.0-win-x64.exe
> 
> Note that if there was no dot net runtime installed, it will redirect to the Windows dotnet Runtime 6.0 site which installs the runtime, but without the needed libraries for the Windows Desktop ... so RetroBar asks again again again again for the dotnet runtime if you don't install the "full" dotnet 6.0 runtime (27 MB vs 54 MB download).

I've been trying but haven't been able to reproduce this. Creating a new VM and launching this RetroBar build opens my browser to the correct .NET 6 download page for desktop apps, from where I can download `windowsdesktop-runtime-6.0.7-win-xxx.exe`. Once installed, RetroBar opens without issue.

If you delete/rename `%localappdata%/RetroBar` and open RetroBar again, are you able to reproduce the crash? If so:
- There may be crash logs in a newly created `%localappdata%/RetroBar/Logs` folder, if you have them and could upload it would help.
- If there are not crash logs, there should be some exception info in Event Viewer that could be helpful for troubleshooting as well.
