### ISSUE TITLE
Will you fix appearing black line when using some fullscreen apps?

### ISSUE THREAD

**Issue by mrt505** [dremin/RetroBar#155]
Retrobar unusable right now because of this. Really disturbing thing.
![image](https://user-images.githubusercontent.com/89605569/140996541-1c28be73-79cb-4820-8757-0c58120cf900.png)

**Comment by dremin** [comment]
Yes, this will be fixed in the next release. As this is a duplicate of #53 I'll track the progress of the fix there.
