### ISSUE TITLE
Cannot drag to select window

### ISSUE THREAD

**Issue by Darthagnon** [dremin/RetroBar#16]
When using RetroBar, I cannot drag a file from one window, onto the RetroBar button for another window and switch to it. Would it be possible to implement this?

Very useful when moving files between Explorer windows, or uploading things.

**Comment by dremin** [comment]
Oops, that is an oversight, I will get this added.

**Comment by Darthagnon** [comment]
Thank you so much! Loving RetroBar a lot!

**Comment by dremin** [comment]
This is now available in the latest release.
