### ISSUE TITLE
Something is WRONG!

### ISSUE THREAD

**Issue by SupaFromSupasShow** [dremin/RetroBar#164]
I have .NET but this still says to install it

**Comment by SupaFromSupasShow** [comment]
i have proof
![14 11 2021_12 20 40_REC](https://user-images.githubusercontent.com/92897376/141691420-4c098f95-596b-4506-9d79-48e484005f1b.png)
![14 11 2021_12 21 15_REC](https://user-images.githubusercontent.com/92897376/141691421-00836ef6-1f10-4418-b099-f4476612fbd8.png)

**Comment by xoascf** [comment]
> 
> 
> i have proof ![14 11 2021_12 20 40_REC](https://user-images.githubusercontent.com/92897376/141691420-4c098f95-596b-4506-9d79-48e484005f1b.png) ![14 11 2021_12 21 15_REC](https://user-images.githubusercontent.com/92897376/141691421-00836ef6-1f10-4418-b099-f4476612fbd8.png)

Click "Yes", and select the option that says "Run desktop applications".

**Comment by SupaFromSupasShow** [comment]
thanks now it is win 98
