### ISSUE TITLE
RetroBar 1.5 suddenly stopped working

### ISSUE THREAD

**Issue by BeaverInABlender** [dremin/RetroBar#181]
RetroBar 1.5 no longer working. Doesn't appear at all in Task Manager when trying to run. Running as administrator doesn't fix the problem. RetroBar 1.4 working as normal.

Windows ver: Windows 11 Home Insider Preview Build 22504

**Comment by dremin** [comment]
Is it working better on the newer insider builds?

**Comment by dremin** [comment]
Closing due to no response, and positive test results in newer builds.
