### ISSUE TITLE
On Windows 11 insider build 22504 using RetroBar can cause explorer.exe have a meltdown.

### ISSUE THREAD

**Issue by ToasterNet420** [dremin/RetroBar#187]
Basically on Windows 11 insider build 22504 RetroBar caused explorer.exe to enter a cycle of crashing and restarting quickly which can render Windows useless unless you fight this cycle with fast typing and delete RetroBar using cmd

**Comment by dremin** [comment]
I'm not seeing this on 22509 or later, are you?

**Comment by xoascf** [comment]
I recently had something similar happen to me regarding that cycle of crashes, but it was because I moved the taskbar window (Alt+Space → Move) from the second screen to the first screen and vice versa. It was in an Insider build, but I hadn't done it before...

**Comment by dremin** [comment]
Windows issue which seems to have since been fixed.
