### ISSUE TITLE
40MB RAM usage and desktop icons position

### ISSUE THREAD

**Issue by Lomik8908** [dremin/RetroBar#191]
My computer has 6 GB of RAM, but I need as much free memory for the game as possible, so how do I fix this? + desktop icon position bug
https://imgur.com/a/YjGHEi9

**Comment by mrflamist** [comment]
While it's true, 40MB is _a lot_ for a taskbar, it might rather be that the game you're trying to run is just too much for your hardware. My laptop has 4GB of RAM and a weak 3rd Gen i3 processor. I'm barely able to run the retail version of GTA 5 with stutters, so I can confirm those 40MB don't make any difference.
I would recommend [looking someplace else](https://mrflamist.github.io/low-end-gaming-guide.html) for free RAM, hardware upgrade or just not using RetroBar whilst playing the game.

**Comment by dremin** [comment]
The desktop icon bug on Windows 7 has since been fixed. Regarding RAM usage, it is the expected amount and I don't expect it to be lowered much even with optimizations.
