### ISSUE TITLE
[Request] Arabic Language Support

### ISSUE THREAD

**Issue by WindowsNinetyTen** [dremin/RetroBar#196]
Could you please add support for Arabic? Thank you.

**Comment by WindowsNinetyTen** [comment]
[Arabic.zip](https://github.com/dremin/RetroBar/files/7782415/Arabic.zip)

Here it is. Please add it. (Note: The file is supposed to say عربي, but XAML files are unsupported and so I had to send it to a ZIP folder which for some reason does not support Arabic characters.

**Comment by dremin** [comment]
Thanks for the translation, we'll add it!

**Comment by WindowsNinetyTen** [comment]
You're most welcome and thanks!

**Comment by xoascf** [comment]
Closed by #197
