### ISSUE TITLE
Zune Theme, POS Embedded Theme, Royal Noir theme, and possibly displaying different icons for the notification area?

### ISSUE THREAD

**Issue by Zeldaboy14** [dremin/RetroBar#207]
Would it be possible for those xp these to be added, and maybe a way to swap out to respective icons for the notification bar based on the os's they come from, or even your own set?

**Comment by Lianaja32** [comment]
The image below is a screenshot of the zune taskbar from my Windows XP vm.
![Zune taskbar (french)](https://user-images.githubusercontent.com/79010647/148675188-6502d048-a640-4ec3-b6f5-83df51eb1094.png)

**Comment by Zeldaboy14** [comment]
yes, that's one of the themes i'd like to see in the next update!

**Comment by Lianaja32** [comment]
Where is the PM on the clock ? On the screenshot, it will normally show 09:22:50 PM, but instead it shows...
![Capture d’écran 2022-01-10 212315](https://user-images.githubusercontent.com/79010647/148834378-fc4d9abf-66f9-44dd-ab03-6d0b91f1292e.png)

**Comment by Lianaja32** [comment]
Me too while using a dark theme ;)

**Comment by AveYo** [comment]
Have you tried [ShittyDark](https://github.com/dremin/RetroBar/issues/206)? ;)

**Comment by 1280px** [comment]
At this point I guess it's better to implement XP msstyles (#61) support so anyone can simply download themes from the Internet and use them as a taskbar style

**Comment by xoascf** [comment]
> At this point I guess it'd be better to implement XP .msstyles (#61) support or .msstyles to RetroBar themes converter, it will autoclose **all** theme requests (except Aero basic) since users will be able to simply use any XP themes as taskbar styles. The problem though is it will probably require to change the way current themes work because of the resources

I'd rather it had been that way if we weren't going the XAML route with vectorized graphics and all that, but the closest thing you can use for this effect is simply [WinClassic/SimpleClassicTheme.Taskbar](https://github.com/WinClassic/SimpleClassicTheme.Taskbar), it lets you load .msstyles with a bit of precision but it works.

I also thought about an external utility to do that, but the controls would get painted and not look right when scaled to larger sizes than defined, and it kind of defeats the purpose of XAML. However, it's something possible anyway...

**Comment by AveYo** [comment]
Updated ShittyDark v2, not even close to Zune level, but works for me  
(less contrast, active highlight, short start button)  
![shittydark_v2 preview](https://user-images.githubusercontent.com/12874843/151639887-a2fff9e5-b62d-4b05-9cea-213ef8a777db.png)

**Comment by ColdSalt09** [comment]
#263 and #266 the last ones aren't made yet

**Comment by xoascf** [comment]
> #263 and #266 the last one isn't created yet

And now it is! (#235)

Now only the "custom icons for the notification area" feature is missing (also asked in https://github.com/dremin/RetroBar/issues/161#issuecomment-966441582 and https://github.com/dremin/RetroBar/issues/55#issue-981954783).

**Comment by dremin** [comment]
These themes are now available in 1.8.
