### ISSUE TITLE
[Request] Windows Vista and 7 Taskbars

### ISSUE THREAD

**Issue by WindowsNinetyTen** [dremin/RetroBar#215]
How about adding Windows Vista and 7 to the options?

**Comment by TheDolphinSlayer** [comment]
I understand the aero themes not being added but what about the basic themes? The ones that don't use transparency, the only complication i can see is the Aero Glow (which is when hovering over the taskbar task button, the cursor will glow the color of the icon)

**Comment by Void48** [comment]
+1 for Vista taskbar

**Comment by gayfieri** [comment]
+1 for 7 taskbar

**Comment by KibSquib48** [comment]
+1 for both

**Comment by Pixel556** [comment]
true

**Comment by dremin** [comment]
Closing as duplicate of #15 and #45
