### ISSUE TITLE
Windows 11 - Taskbar vanishes with maximized apps. 

### ISSUE THREAD

**Issue by DangerDane** [dremin/RetroBar#234]
When running apps fully maximised the taskbar vanishes. I would prefer it to be possible to keep it on screen with the other apps "adjusting" to it like it was working originally...

**Comment by OICD** [comment]
Happens on Windows 10 too

**Comment by dremin** [comment]
If you change the theme to one with a different size (e.g. switching from Windows 2000 to Windows XP Blue, or vice versa) does the problem go away?

**Comment by zouyonghao** [comment]
I also meet this issue, when I use a fully screen app or game, I cannot see the bar when I press Windows button.

**Comment by dremin** [comment]
Duplicate of #171 which will be fixed in the next release.
