### ISSUE TITLE
Start menu floats above taskbar

### ISSUE THREAD

**Issue by 1xxxxxxxxx** [dremin/RetroBar#237]
Windows 10's start menu floats above the RetroBar taskbar

**Comment by Jonson26** [comment]
You need to check the "use small taskbar buttons" option in win10's taskbar settings.

**Comment by 1xxxxxxxxx** [comment]
so what if it's windows 11?
Minh

**Comment by Jonson26** [comment]
IIRC Windows 11 also has some sort of compact taskbar setting. It won't be pixel-perfect, but it should make it at least a little bit better.

**Comment by Jonson26** [comment]
A quick google search reveals this: https://allthings.how/how-to-enable-small-taskbar-in-windows-11/

**Comment by dremin** [comment]
Duplicate of #193
