### ISSUE TITLE
Start menu button opens the windows 11 menu, not the retro menu

### ISSUE THREAD

**Issue by jeffsharpe86** [dremin/RetroBar#239]
When I click the start menu button (bottom left) it opens the windows 11 menu (center screeb), not the retro menu above the button.  

I'm on a macbook M1 running parallels windows 11 home pro with windowsdesktop-runtime-3.1.22-win-x64.  When I noticed the issue I tried an earlier version 3.1.1, but it crashed my CPU.

**Comment by themoonmeetsthesun** [comment]
It doesn't NOT replace the start menu, the start menu has been same for me too. If you want the old start menu you can try open shell.

**Comment by dremin** [comment]
RetroBar does not replace the start menu.
