### ISSUE TITLE
[Request] Turkish Language Support

### ISSUE THREAD

**Issue by TommyHeavenLy6** [dremin/RetroBar#242]
[Turkish.zip](https://github.com/dremin/RetroBar/files/8056610/Turkish.zip)

Here's the Turkish XAML file. Thank you.

**Comment by michioxd** [comment]
i think u should create this request in [Pull requests](https://github.com/dremin/RetroBar/pulls) section.

**Comment by dremin** [comment]
This will be added in the next release by #232.

**Comment by dremin** [comment]
This is now available in 1.8.
