### ISSUE TITLE
Suggestion: time-accurate start menu

### ISSUE THREAD

**Issue by CrazyFrogEpic** [dremin/RetroBar#245]
There are little to no accurate start menus that perfectly recreate pre-Vista start menus, not even Open-Shell can compare.
![image](https://user-images.githubusercontent.com/77507284/154063128-286753db-589d-40ae-a458-d800a9f2f424.png)
![image](https://user-images.githubusercontent.com/77507284/154063482-07254530-aab6-4cc8-8b5f-3d7c66c9ecfd.png)

**Comment by chrislogan-foss** [comment]
I think that would be more suitable as a separate project

**Comment by 111ebobo** [comment]
> I think that would be more suitable as a separate project

Like add-on for retrobar

**Comment by dremin** [comment]
This is not currently planned to be added to RetroBar itself.
