### ISSUE TITLE
Hide tray icons

### ISSUE THREAD

**Issue by Ryan659** [dremin/RetroBar#25]
Is it possible to hide tray icons? Some of the emulated Windows versions (esp. WinXP) do allow this on the actual OS, but RetroBar doesn't.

**Comment by dremin** [comment]
Do you mean hide as in disable, or collapse?

**Comment by Ryan659** [comment]
Sorry, yes, I meant collapse. Though disabling could be a fun option too. :)

**Comment by dremin** [comment]
This was added in the latest release.
