### ISSUE TITLE
Loading theme appears incorrect and retro bar crashs on xp custom themes

### ISSUE THREAD

**Issue by Zeldaboy14** [dremin/RetroBar#252]
Me and a bud are noticing that loading the xaml's from the retrobar git are either defaulting to 9x (in terms of the xp classic xaml), or loading a custom theme for the xp taskbar seems to hardcrash retrobar until the theme is removed

**Comment by xoascf** [comment]
Have you used the [GitHub Actions builds](https://github.com/dremin/RetroBar/actions)?

That shouldn't happen.
It's possible that some of the older themes you can find on GitHub are no longer updated or no longer fully compatible, you may have to do some fixes on them.

**Comment by Zeldaboy14** [comment]
I havn't, but the xaml's i'm using appear to just have been updated 2 days ago.

**Comment by dremin** [comment]
Closing as this is user error (using non-embedded themes referencing embedded resources). The themes work when bundled with the app.
