### ISSUE TITLE
Start button label and icon do not appear as pressed (for classic themes)

### ISSUE THREAD

**Issue by xoascf** [dremin/RetroBar#255]
Comparison (Original Start button pressed/RetroBar Start button pressed):

XP Classic:
![XPClassicStart](https://user-images.githubusercontent.com/28744392/154812414-94c2a2b3-3f3b-46b0-9661-8ba8d934cd91.png)

2000 Classic (also, 1px to the right is extra):
![2KClassicStart](https://user-images.githubusercontent.com/28744392/154812408-c6d4dc7f-43c4-4a8d-a382-a8e7be71c45a.png)

95-(98) Classic (has something like `FocusVisualStyle` on the inner edges of the button):
![98ClassicStart](https://user-images.githubusercontent.com/28744392/154812411-76fb6d05-a8a3-490a-a835-599376d02671.png)

**Comment by xTmmm** [comment]
wow i didnt know that
