### ISSUE TITLE
white line above taskbar on firefox

### ISSUE THREAD

**Issue by chloe-burbank** [dremin/RetroBar#258]
![image](https://user-images.githubusercontent.com/94586008/154879456-97900937-de5a-4ac2-811c-72d29990028f.png)
hlep

**Comment by Pixel556** [comment]
Same bug happened to me aswell.

**Comment by dremin** [comment]
I've seen this issue if Firefox is already open when starting RetroBar, do you see this in other scenarios?

**Comment by mrt505** [comment]
i use brave browser and i see black line after watching fullscreen videos in youtube. i couldn't use retrobar because of this annoying bug. i created #193 thread hope it will fixed next release.

**Comment by 1280px** [comment]
Can confirm for RetroBar 1.9

**Comment by dremin** [comment]
This should not be an issue any longer, as Firefox no longer draws a white line here.
