### ISSUE TITLE
Customization settings for Notification not preserved? 

### ISSUE THREAD

**Issue by ckpager** [dremin/RetroBar#261]
Hello, thanks for much for the Retrobar and the terrific improvements which came in version 1.7

I have some programs which I only run occasionally, and which create a notification icon while they are running.
When I customize the Retrobar notification to "always show" the icon, it shows.
But some days later, when I run the program again, I find the Retrobar notification setting for this icon has defaulted back to "hide when inactive."

I'm not sure where or how Retrobar saves its Properties/Customization info, but I wonder if doesn't hold all the info that it should (or for as long as it should)?

((When the program is *not* running, any option in Retrobar to adjust customization settings for its notification disappears.  I think the equivalent Windows XP settings here also included the ability to customize not-currently-running icons.  It might be OK that Retrobar doesn't show them, but Retrobar should at least remember that the settings for not-currently-running icons had been set previously.))

**Comment by dremin** [comment]
Do you have a few example programs that cause this which I can install to try and reproduce?

(FWIW, RetroBar _should_ remember the settings for programs not running, even though they don't appear in the settings--at least when it is working correctly!)

**Comment by ckpager** [comment]
I sent the example program via 1MB zip attachment but I'm not sure whether
the e-mail filters have blocked it.

If you didn't receive the attachment let me know and I will re-send
differently.

 

Kind regards, and thanks,

Chet

 

 

  _____  

From: Chet KW Pager 
Sent: 02 March 2022 9:26 AM
To: dremin/RetroBar; dremin/RetroBar
Cc: Author
Subject: RE: [dremin/RetroBar] Customization settings for Notification not
preserved? (Issue #261)

 

Hi Sam,

 

Thanks for following up.

 

See the attached program - it's a portable program, so doesn't require
installation: I just run the executable from whatever directory the program
files are located.  I use it all the time - it's a great screen capture
utility.  

 

When I set RetroBar to always display the icon, the icon will be displayed,
but then after I exit the program and a few hours pass, if I activate it
again, the icon will be hidden again.

 

Separate question: would it be possible to create an option to change the
default for new/unknown-icons to "always show"  unless specifically set to
"hide when inactive" (rather than any new/unkown icons being hidden unless
specifically et to always show)?

 

Best regards,
Chet

 

 

  _____

**Comment by dremin** [comment]
Unfortunately the attachment didn't make it via email, you should be able to attach via the web.

**Comment by ckpager** [comment]
Hi Sam,

 

Here's a google drive link to a Zip file containing the (portable) software
with the icon/notification issue.

 

 
https://drive.google.com/file/d/1xMZSVnDUn2zXxLQZDh_LoNUMwpssL4od/view?usp=s
haring 

 

Thank you,
Chet

 

 

From 2 March e-mail:

 

See the attached program - it's a portable program, so doesn't require
installation: I just run the executable from whatever directory the program
files are located.  I use it all the time - it's a great screen capture
utility.  

 

When I set RetroBar to always display the icon, the icon will be displayed,
but then after I exit the program and a few hours pass, if I activate it
again, the icon will be hidden again.

 

Separate question: would it be possible to create an option to change the
default for new/unknown-icons to "always show"  unless specifically set to
"hide when inactive" (rather than any new/unkown icons being hidden unless
specifically et to always show)?

 

Best regards,
Chet

 

 

  _____

**Comment by dremin** [comment]
Thanks! I also noticed some issues with this program staying pinned on the Windows 11 taskbar, but I've made some changes to make this work better in RetroBar.

**Comment by dremin** [comment]
This is now fixed in 1.8.
