### ISSUE TITLE
Zune theme

### ISSUE THREAD

**Issue by veterica** [dremin/RetroBar#262]
It is the last theme i had when i last used XP, i will be very happy if you guys implemented it

**Comment by Lianaja32** [comment]
The screenshot below was taken from my Windows XP vm, and yeah, that's 1 of the 2 "dark" themes of XP. Me too, i would like this theme to be implemented in RetroBar.
![Zune taskbar (french)](https://user-images.githubusercontent.com/79010647/156391582-03c5a665-75ef-4abc-ab49-7e7cda62d337.png)

**Comment by veterica** [comment]
> #266 lol look here it is

It crashed my Retrobar when selecting, even if it is on 1.7

**Comment by ColdSalt09** [comment]
Why? mine works perfectly

**Comment by ColdSalt09** [comment]
![εικόνα](https://user-images.githubusercontent.com/77743845/156922977-b372895a-b9a2-4c98-aeb2-651f8bdabbbe.png)
Have you pasted the "startxpblue" icon to the resourses folder?

**Comment by dremin** [comment]
Closing as duplicate of #207
