### ISSUE TITLE
Transparent taskbar background doesn't work?

### ISSUE THREAD

**Issue by ashifolfi** [dremin/RetroBar#267]
I'm trying to make a longhorn aero theme but I can't get the taskbar to be properly transparent.

It always has a white background behind it.

Is this a limitation of RetroBar or am I doing something wrong?

**Comment by ashifolfi** [comment]
I ended up figuring out what I did wrong. It works now.

**Comment by 0x5066** [comment]
![70E46AF2-226A-45BC-B118-B865B1D560D0](https://user-images.githubusercontent.com/38136789/156587098-661dc8dd-75a0-479b-9550-b70af5d58034.png)

**Comment by xoascf** [comment]
> I ended up figuring out what I did wrong. It works now.

You could clarify the property you were missing to set in the XAML theme.

https://user-images.githubusercontent.com/28744392/156586647-96ff5acf-51fe-4bcd-9bb6-49db95a95a73.mp4

Transparent themes should use:
`<system:Boolean x:Key="AllowsTransparency">True</system:Boolean>`
