### ISSUE TITLE
Retrobar potentially contacting malicious domains

### ISSUE THREAD

**Issue by Christophermenn** [dremin/RetroBar#272]
Correct me if i am wrong but i think retrobar is contacting malicious domains as shown in the following virustotal graph 
https://www.virustotal.com/graph/embed/gc9573f288e0f451d90d4db399e12bff467cbd151e598444fa6669d5ba902aa2f

**Comment by xoascf** [comment]
Check the IPs, they belong to Microsoft and GitHub servers, if you consider them malicious you can add them to your system hosts file, but RetroBar will no longer check for updates.

**Comment by Christophermenn** [comment]
thanks for the explanation
