### ISSUE TITLE
Please add the windows vista   theme please 

### ISSUE THREAD

**Issue by xTmmm** [dremin/RetroBar#275]
please
![image](https://user-images.githubusercontent.com/86075685/158187932-789635b5-ba7c-498d-aa71-a2222a519912.png)

**Comment by ColdSalt09** [comment]
![εικόνα](https://user-images.githubusercontent.com/77743845/158222526-4edd0571-58f2-4f07-bda4-4654c2116cf7.png)
Im trying but i cant its so hard

**Comment by xoascf** [comment]
I can work on this, it looks easy enough to do!

**Comment by xoascf** [comment]
Oops...
Duplicate of #15

**Comment by xTmmm** [comment]
why

**Comment by xoascf** [comment]
Duplicate of #15

**Comment by markyb86** [comment]
I've gotten pretty close , although the start orb does not overlap
![image](https://user-images.githubusercontent.com/34405495/159130363-3138a740-1e9e-4309-aabc-f60090058c3f.png)

**Comment by XTMYTYT** [comment]
NICE!

**Comment by XTMYTYT** [comment]
can u send me theme

**Comment by markyb86** [comment]
https://github.com/markyb86/RetroBar

you need 
retrobar\controls\Vista Frame.xaml
retrobar\resources\startvista.png
retrobar\resources\startvistablue.png
retrobar\themes\Vista Ultimate.xaml

I believe it will not work unless you have retrobar 1.7, with all of the supporting files extracted

![image](https://user-images.githubusercontent.com/34405495/159161405-da5cfbd4-3b97-48ef-a6e2-28dbc5399f3e.png)
