### ISSUE TITLE
idea: for custom themes for retrobar 

### ISSUE THREAD

**Issue by XTMYTYT** [dremin/RetroBar#276]
put custom theme if it is a file then u can put in retrobar  then u can use the theme

**Comment by xoascf** [comment]
That is already available, you can try custom themes here: https://github.com/dremin/RetroBar/labels/custom%20theme

1. Just copy the folders inside your RetroBar directory:
It will probably be the most recent directory at `%LocalAppData%\Temp\.net\RetroBar`
2. Then open the Properties window
3. Select the custom theme
