### ISSUE TITLE
windows xp classic system theme

### ISSUE THREAD

**Issue by samiscoolest** [dremin/RetroBar#28]
system theme but windows xp classic start button

**Comment by XTMYTYT** [comment]
agreed

**Comment by achmadsutardi441953** [comment]
![ewfsdf](https://user-images.githubusercontent.com/30205044/125415434-93aef88c-cea7-49cf-9122-9a3bfd294a77.png)
And this Luna Theme?

**Comment by dremin** [comment]
This is now available in the latest release!
