### ISSUE TITLE
Task and Toolbar icons blurry, low res

### ISSUE THREAD

**Issue by Jawomo** [dremin/RetroBar#289]
Icons seem a little blurry / low res when using a bigger taskbar. 

Would be nice if the app would use hi res icons for tasks and toolbar.

**Comment by dremin** [comment]
Do you mean when a custom theme is using icons larger than 16 points, high DPI, or something else that is making the taskbar larger?

**Comment by xoascf** [comment]
I think @Jawomo is referring to these low resolution icons with this custom theme created:
![159129044-37fe5cc3-b97a-4daf-bdcd-471c6e3e7c56](https://user-images.githubusercontent.com/28744392/159186092-8e05aae5-d6fb-4777-8c68-c1d35cdf4ae3.png)

**Comment by Jawomo** [comment]
> Do you mean when a custom theme is using icons larger than 16 points, high DPI, or something else that is making the taskbar larger?
Yes, when using a theme which is higher, with bigger icons, they get blurry.

**Comment by dremin** [comment]
Thanks for clarifying! I will look into adding a property that themes can set to use larger icons.

**Comment by Jawomo** [comment]
> Thanks for clarifying! I will look into adding a property that themes can set to use larger icons.

That would be awesome 👌 

Now if we could get black tray system icons and a desktop shortcut in right corner this app would be perfect. 

Thanks for your support!

**Comment by xoascf** [comment]
For large icons in the latest build you will only need to add:
`<system:Boolean x:Key="UseLargeIcons">True</system:Boolean>`


> Now if we could get black tray system icons...

Check out #293, it's already available via GitHub Actions builds for now.
You will need to add:
`<system:Boolean x:Key="InvertSystemNotifyIcons">True</system:Boolean>`

> ...and a desktop shortcut in right corner this app would be perfect.

Working on it (#169).

**Comment by Jawomo** [comment]
@xoascf 
Thats great news! Will test this asap. With this RetroBar will get even more flexible 👍

**Comment by dremin** [comment]
This is now available in 1.8.

**Comment by jayglo9k** [comment]
![retrobar](https://github.com/dremin/RetroBar/assets/153105204/0b499fe4-6222-4b7e-8453-e6419ed7a908)

Hello, I've recently upgraded to a 1440p monitor, and now I've noticed retrobar is kind of blurry. Is there anything I can do? Thanks in advance.

**Comment by yereverluvinunclebert** [comment]
What is the scale factor on the windows desktop - try adjusting that. 
I run Retrobar on a 4K monitor with 150% scaling, I do not see any blurring.

**Comment by jarupxx** [comment]
When I adjust the scaling of windows desktop, Integer multiples (300%, 200%, 100%) are displayed beautifully.
Unfortunately, it's blurry at 150% and 175% scaling.
![adjust scales](https://github.com/dremin/RetroBar/assets/20138367/c1ccbcdf-7f0e-49c5-85e7-71358885a1c6)
