### ISSUE TITLE
XP Luna start button text is inaccurate in Polish

### ISSUE THREAD

**Issue by FrostedGeulleisia** [dremin/RetroBar#301]
The "start" text on the XP Luna themes (both Blue and Silver) is inaccurate, the "S" should be capitalized, just like in some other languages (and all other themes).
How it looks like:
![obraz](https://user-images.githubusercontent.com/27410260/160167351-5d1475d7-63f5-40db-a3ff-68e10ead092e.png)
How it should look like:
![obraz](https://user-images.githubusercontent.com/27410260/160169553-02f48a6e-40fd-41d7-a3e8-830a6406435e.png)
Looking at it closer, the original issue which submitted the translation in the first place, didn't include images, (stating they've been copied over from English), copying them from a language which has this capitalized S should work (and be accurate).

**Comment by xoascf** [comment]
The translator is @setmatrix, I don't know if he would agree with that.

**Comment by setmatrix** [comment]
@FrostedGeulleisia you're right. I missed that detail.

**Comment by dremin** [comment]
Fixed in #302.

**Comment by dremin** [comment]
This is now available in 1.8.
