### ISSUE TITLE
The taskbar is slightly above the edge of the screen

### ISSUE THREAD

**Issue by xoascf** [dremin/RetroBar#304]
Sometimes, after turning the monitor off and on again, the taskbar goes up a little
![explorer_ADwfycAvzP](https://user-images.githubusercontent.com/28744392/160463335-9336e9a9-9214-4e53-93c0-55f1d38f3109.png)

**Comment by dremin** [comment]
Is this still happening with newer Windows and RetroBar builds? I haven't seen it lately.

**Comment by xoascf** [comment]
> Is this still happening with newer Windows and RetroBar builds? I haven't seen it lately.

Yeah, me neither, I'll reopen it if it happens again.
