### ISSUE TITLE
suggestion for adding the toolbars

### ISSUE THREAD

**Issue by exalye** [dremin/RetroBar#307]
what about adding the toolbars?
![link1](https://user-images.githubusercontent.com/94129338/160724002-694a8847-1334-43d5-8fda-2f592d6d4944.jpg)

**Comment by 1280px** [comment]
The string for toolbars context menu item is in language files, so I believe it's planned to be added somewhere in the future.
https://github.com/dremin/RetroBar/blob/db053b3a9857aca927f0175ca5e25d29624952e7/RetroBar/Languages/English.xaml#L48

**Comment by dremin** [comment]
Duplicate of #42
