### ISSUE TITLE
Any way to rescale the taskbar?

### ISSUE THREAD

**Issue by Oyster91** [dremin/RetroBar#308]
Hi,
After installing the RetroBar, i noticed that the taskbar is much smaller, than its supposed to be.
Is there any way to rescale the bar? Would it be possible just edit xaml file and install it, as custom theme?
Unfortunately i dont know xaml scripting, so if anyone could do that, or just let me know if its even possible, that would be great.

![Screenshot 2022-03-31 144743](https://user-images.githubusercontent.com/102737195/161058130-88d1b89d-358c-4be5-9e8a-5a8e06bd2f07.png)

**Comment by mutoyoru** [comment]
It's not small actually. In XP and Vista (and Windows 7 taskbar with small icons), default taskbar height is 30px and RetroBar uses this value as default. But if you want, you can change the value in theme file (if this line not exists, you can add it):

`<system:Double x:Key="TaskbarHeight">30</system:Double>`

**Comment by Oyster91** [comment]
> It's not small actually. In XP and Vista (and Windows 7 taskbar with small icons), default taskbar height is 30px and RetroBar uses this value as default. But if you want, you can change the value in theme file (if this line not exists, you can add it):
> 
> `<system:Double x:Key="TaskbarHeight">30</system:Double>`

Thats wierd, i was sure it used to be way bigger than this, i can barely see icons on the bar.
Okay so another issue regarding increasing height.
Whenever i try load cusom theme, for example XP Blue (which is basically a copy paste from themes folder), it just does not work.
![Screenshot 2022-04-01 141626](https://user-images.githubusercontent.com/102737195/161262674-f3e47ceb-09f1-457c-ae1f-79cd762ec60c.png)

**Comment by mutoyoru** [comment]
Some themes needs extra resources. You need to copy the contents in Resources folder as well. For XP Blue theme, you need startxpblue.png and startxpbluebutton.png as well. File structure:
```
.
├── RetroBar.exe
├── Resources
    ├── startxpblue.png
    └── startxpbluebutton.png
├── Themes
    ├── Windows XP Blue.xaml
```

Also some themes uses another themes as base source, so that base theme has to be in Themes folder as well.
