### ISSUE TITLE
could we have a show desktop button in the bottom right

### ISSUE THREAD

**Issue by Tommy2678** [dremin/RetroBar#316]
have it be a toggleable for the people who don't prefer it, but i'm really missing it

**Comment by zigafide** [comment]
Windows key + M does the same thing, if this never gets added

**Comment by exalye** [comment]
create shortcut with adress C:\Windows\explorer.exe shell:::{3080F90D-D7AD-11D9-BD98-0000947B0257} and and it to your Quick Launch folder.

**Comment by xoascf** [comment]
Duplicate of #84

**Comment by TommyHeavenLy6** [comment]
Not for bottom right but it could be add to right click cuz all Windows versions had that if i remember correct.

**Comment by dremin** [comment]
Duplicate of #84
