### ISSUE TITLE
Vista basic theme pls

### ISSUE THREAD

**Issue by Pixel556** [dremin/RetroBar#326]
Add vista basic theme please

**Comment by Lianaja32** [comment]
Some people have the same request, and i have the same idea.

**Comment by MasterSlenderTR** [comment]
Yeah, it'd be nice.

**Comment by Pixel556** [comment]
Yeah.

**Comment by Pixel556** [comment]
We're so lucky! 95 issues!

**Comment by dremin** [comment]
Closing as duplicate of #15 (which the PR is linked to).
