### ISSUE TITLE
Start button bug

### ISSUE THREAD

**Issue by Frapoo** [dremin/RetroBar#33]
![image](https://user-images.githubusercontent.com/61443778/125190311-0484ee80-e26f-11eb-901d-7573de4d2ebc.png)

The button still shows the normal status even I clicked on it and the start menu appeared.

**Comment by sweetchoc** [comment]
![image](https://user-images.githubusercontent.com/61443778/125190612-9e996680-e270-11eb-9651-7c676e9d176d.png)
It should be something like this

**Comment by dremin** [comment]
This is fixed in the latest release.
