### ISSUE TITLE
How do i use the themes?

### ISSUE THREAD

**Issue by DolanDukk** [dremin/RetroBar#335]
im alittle bit confused about how to actually install the themes, got the .NET app thing, but still stuck. any help?

**Comment by CheemsLuL** [comment]
right-click the taskbar and select "properties"
you can change your theme from there

**Comment by 111ebobo** [comment]
> To install custom themes, make a folder named "Themes" on the folder the retrobar executable is in and put the theme files there

Maybe he will get the problem when you put a theme in a folder with themes and you still see a classic theme

**Comment by dremin** [comment]
Closed, answered by @gayfieri, thanks!
