### ISSUE TITLE
Maximized windows don't update their size (ghost taskbar)

### ISSUE THREAD

**Issue by DatGamerYoloYT** [dremin/RetroBar#336]
![image](https://user-images.githubusercontent.com/84749503/166827771-8ff4861d-bcaa-485b-b9f4-227e8490a23d.png)
im using windows 11 btw

**Comment by dremin** [comment]
By chance do you have multiple monitors, have disconnected monitors while RetroBar was running, or connected via remote desktop?

**Comment by 111ebobo** [comment]
Turn on auto hide taskbar in sett6

**Comment by dremin** [comment]
Closing due to lack of response.
