### ISSUE TITLE
Longhorn Aero Theme

### ISSUE THREAD

**Issue by TheDolphinSlayer** [dremin/RetroBar#352]
THIS SERIOUSLY LOOKS AMAZING!

Does that mean Vista Aero and Windows 7 aero soon? (Hopefully with the Vista/Windows 7 Jumplist, and customizable notification systray : D

**Comment by dremin** [comment]
Glad you like it! I am working on a Vista Aero theme at the moment.

**Comment by XTMYTYT** [comment]
> Glad you like it! I am working on a Vista Aero theme at the moment.

are you also gonna leak a picture of the vista aero theme or u can make also the basic theme

**Comment by WF4123** [comment]
> Glad you like it! I am working on a Vista Aero theme at the moment.

Finally. I cannot wait for a moment.

**Comment by dremin** [comment]
Closing as duplicate of #15 (which the PR is linked to).
