### ISSUE TITLE
Selecting custom themes on retrobar in properties causing crashes

### ISSUE THREAD

**Issue by RedDragonTix** [dremin/RetroBar#354]
I was trying to install Windows Longhorn Aero theme on Retrobar, I did create Themes directory, xaml file, but when I select windows longhorn aero theme in properties, Retrobar crashes!

Any clue?

**Comment by dremin** [comment]
The theme needs a newer version of RetroBar, try the version [on this page](https://github.com/dremin/RetroBar/actions/runs/2492770120) under the Artifacts section.

**Comment by RedDragonTix** [comment]
> The theme needs a newer version of RetroBar, try the version [on this page](https://github.com/dremin/RetroBar/actions/runs/2492770120) under the Artifacts section.

thank you, it seems Longhorn Aero theme work
