### ISSUE TITLE
What code changes are required to use system's current theme instead of Custom Theme? OS: Win 7/8/10/11

### ISSUE THREAD

**Issue by amitprs2003** [dremin/RetroBar#357]
Please let me know what and where code changes are required in RetroBar project to use currently applied windows theme instead of using any of the custom themes.

Thanks.

**Comment by ColdSalt09** [comment]
What do you mean? Using your operating system's taskbar instead of retrobar?

**Comment by ThaBluNate** [comment]
> What do you mean? Using your operating system's taskbar instead of retrobar?

I... guess?
The question was so vague...

**Comment by amitprs2003** [comment]
Sorry if my question was not clear. I am trying to use retrobar code which has theme (i.e. xaml) for XP, Vista etc. However I want to draw taskbar using retrobar code but want to use system theme which user has selected. I am new to WPF so not very clear that if I need to write new XAML themes as target OS can be Windows 7, 8, 10 or 11 or is there a way to modify retrobar code to use system theme instead of writing XAML? and if there is a way, then what/where code changes are required in retrobar code to achieve same? Hope I am clear this time.

**Comment by xoascf** [comment]
> Sorry if my question was not clear. I am trying to use retrobar code which has theme (i.e. xaml) for XP, Vista etc. However I want to draw taskbar using retrobar code but want to use system theme which user has selected. I am new to WPF so not very clear that if I need to write new XAML themes as target OS can be Windows 7, 8, 10 or 11 or is there a way to modify retrobar code to use system theme instead of writing XAML? and if there is a way, then what/where code changes are required in retrobar code to achieve same? Hope I am clear this time. Thanks.

The System theme can help you with that, as it uses the system color scheme, but if you mean the system controls and styling, you can't as you need to style them in XAML (if the theme doesn't include it, but RetroBar overrides the styling of the controls by the system except in the Properties window).

You can also use [StartIsBack](https://www.startisback.com/), as it will use the style of the theme from your selected .msstyles file.

Another option would be [WinClassic/SimpleClassicTheme.Taskbar](https://github.com/WinClassic/SimpleClassicTheme.Taskbar) as it also uses the .msstyles, but in this case, from XP.

**Comment by amitprs2003** [comment]
Thanks for response.
