### ISSUE TITLE
white line under the start button of the new longhorn aero theme

### ISSUE THREAD

**Issue by ColdSalt09** [dremin/RetroBar#358]
![εικόνα](https://user-images.githubusercontent.com/77743845/176693320-e65a1a8b-03f0-4e44-ab51-bce38df2c24c.png)

**Comment by dremin** [comment]
This is actually intentional, the theme is modeled after [Aero TWIWMTB](https://www.betaarchive.com/forum/viewtopic.php?t=41350).
