### ISSUE TITLE
RetroBar displays tooltip when last window is closed

### ISSUE THREAD

**Issue by tunedal** [dremin/RetroBar#364]
Steps to reproduce:
1. Launch Notepad.
2. Close all other windows.
3. Click on RetroBar to give it focus.
4. Close Notepad.

Results: RetroBar displays the tooltip "Click here to begin" over the start button.

The Windows taskbar doesn't exhibit this behaviour. Although it receives input focus (which might have something to do with it?) when the last window is closed, and it can be navigated with the tab key, it doesn't display any tooltips or pop-overs in this scenario.

![retrobar-unexpected-tooltip](https://user-images.githubusercontent.com/556423/177752847-797bb195-2a83-46bf-975a-34985b91e765.png)

**Comment by dremin** [comment]
The issue should be fixed in [this test build](https://github.com/dremin/RetroBar/suites/18109417606/artifacts/1043875550) if you'd like to confirm. Thanks!
