### ISSUE TITLE
Add Ukrainian language support

### ISSUE THREAD

**Issue by 111ebobo** [dremin/RetroBar#366]

**Comment by 1280px** [comment]
If you know Ukrainian, you can translate it yourself using [English translation file](https://github.com/dremin/RetroBar/blob/master/RetroBar/Languages/English.xaml) as reference and PR it to the project

**Comment by 111ebobo** [comment]
> If you know Ukrainian, you can translate it yourself using [English translation file](https://github.com/dremin/RetroBar/blob/master/RetroBar/Languages/English.xaml) as reference and PR it to the project

Thanks for the idea, but I made it and it doesn't work

**Comment by VovaTheHuman** [comment]
Here is the translated file
[українська.zip](https://github.com/dremin/RetroBar/files/9150055/default.zip)

**Comment by xoascf** [comment]
Added in #525
