### ISSUE TITLE
Couldn't get RetroBar working, because of ".NET is required. Would you like to install it?"

### ISSUE THREAD

**Issue by bangbangyouall** [dremin/RetroBar#367]
I even installed a correct version, still will not work!

**Comment by ColdSalt09** [comment]
have  you installed the 6.0?
Also you need to select run desktop apps and the architecture of your cpu
hav you selected the right download?

**Comment by shakeyourbunny** [comment]
You have to install the FULL dotnet 6.x runtime, not the basic one RetroBar redirects to.

The basic dotnet 6.0 runtime does NOT include support for the needed Windows Desktop libraries. The correct one has about 50-60 MB (not 27MB) and you can find it on the https://dotnet.microsoft.com/en-us/download/dotnet/6.0 under the section ".NET Desktop Runtime 6." and choose "x64".

**Comment by torben-struct** [comment]
Same issue here on windows 11 with windowsdesktop-runtime-6.0.7-win-x64.exe installed.
Works though when I cloned the repo and build RetroBar locally.

**Comment by SigmaTel71** [comment]
Yep, can reproduce with both .NET runtimes installed.
![image](https://user-images.githubusercontent.com/17989678/179422216-204bfe00-68e4-49d6-88a2-db9eaa5b8df6.png)

**Comment by dremin** [comment]
Sorry for the confusion, the readme is for the _next_ version of RetroBar, which requires a different .NET version. I'm getting pretty close to releasing it, so you can [download it here](https://github.com/dremin/RetroBar/suites/7394012266/artifacts/301113427).

**Comment by dremin** [comment]
Closing as the version discrepancy will be fixed shortly with the upcoming release.
