### ISSUE TITLE
[Feature Request] Open-Shell menu button and RetroBar

### ISSUE THREAD

**Issue by shakeyourbunny** [dremin/RetroBar#370]
Open-Shell and RetroBar do work alongside nicely, but RetroBar paints over the start menu button of Open-Shell.

Could you include an option that - if Open-Shell is running - does not paint over the start menu button of Open-Shell?

Thank you.

**Comment by ThaBluNate** [comment]
OpenShell directly paints over the default windows taskbar, while RetroBar makes a completely new taskbar.
So no, I don't think so

**Comment by FoxbitDreamtail** [comment]
It should be possible if openshell really is an update to support retro bar, basically this issue needs to be over there and not over here.

**Comment by dremin** [comment]
The above comment is correct, Open Shell hooks Explorer directly to accomplish this and would need to be modified to do the same with RetroBar. However, RetroBar themes allow changing the start button without additional utilities.

**Comment by shakeyourbunny** [comment]
Does this also include a hover glow like the Vista Orb does?

**Comment by FoxbitDreamtail** [comment]
> Does this also include a hover glow like the Vista Orb does?

This issue is closed. If you want to know if a feature exists I recommend starting a Windows virtual Machine and installing this application in said Windows virtual Machine.

**Comment by shakeyourbunny** [comment]
Really, I appreciate the hostility here :)

**Comment by dremin** [comment]
> Does this also include a hover glow like the Vista Orb does?

Unfortunately not currently.

**Comment by FoxbitDreamtail** [comment]
There's no hostility, your issue was closed therefore this section of this GitHub page should not be used.
