### ISSUE TITLE
[Feature Request] resizing the task bar?

### ISSUE THREAD

**Issue by epiclulz666** [dremin/RetroBar#371]
this coud be a handy feature to have in future released. the ablity to resize the task bar. on a 4k display running at 4k the task bar looks very small compared to what it would have looked like on an old crt or early lcd at like 1024x800 and so on. the ablity to resize the task bar would give more of a retro feel to the app.

**Comment by dremin** [comment]
RetroBar uses the Windows scaling options. Scaling past that point is not currently planned as the classic themes do not scale well.
