### ISSUE TITLE
button still cut off after windows vista theme update

### ISSUE THREAD

**Issue by ColdSalt09** [dremin/RetroBar#373]
![εικόνα](https://user-images.githubusercontent.com/77743845/179403040-93a82294-df61-4b0a-8cd7-ca05721b68fd.png)

**Comment by dremin** [comment]
Are you sure its the right build? This one should have it: https://github.com/dremin/RetroBar/suites/7390102598/artifacts/300837717

**Comment by xoascf** [comment]
Looking closely at the Start button, it seems to be different from the Windows Vista orb, or it seems to have too much shadow...

**Comment by dremin** [comment]
@xoascf I think some sort of blending mode is applied in Vista, the image extract from Aero.msstyles does not seem to match what is displayed.

**Comment by xoascf** [comment]
> @xoascf I think some sort of blending mode is applied in Vista, the image extract from Aero.msstyles does not seem to match what is displayed.

So it seems, I am using an alternative orb that is "more accurate", but it is credited to fediafedia:
https://www.deviantart.com/fediafedia/art/Aero-Ultimate-ViOrb-82139851

![orb](https://user-images.githubusercontent.com/28744392/179425447-ab6030cb-132e-4a67-99ce-df2dac91418b.png)

**Comment by ColdSalt09** [comment]
Thanks guys. It works now.
![εικόνα](https://user-images.githubusercontent.com/77743845/179504365-51dc7c76-6728-464f-a5ed-a2a0134c1cfe.png)

**Comment by dremin** [comment]
Yay! Closing this issue.
