### ISSUE TITLE
latest version not launching

### ISSUE THREAD

**Issue by Zeldaboy14** [dremin/RetroBar#382]
Been trying to launch the most recent version of retrobar, and it completly fails on 32 and 64 bit modes

**Comment by dremin** [comment]
This is probably due to .NET 6.0 or 6.0.1. Could you please [install the latest .NET 6 desktop runtime](https://dotnet.microsoft.com/download/dotnet/6.0/runtime) (select the appropriate download button under "Run desktop apps") and see if that helps?

**Comment by Zeldaboy14** [comment]
that fixed it! Thanks!

**Comment by dremin** [comment]
Great!
