### ISSUE TITLE
[Request]Windows 7 Taskbar/Pinning Icons

### ISSUE THREAD

**Issue by lvzxr** [dremin/RetroBar#385]
Loving the vista look, but I really do miss the stock Windows method of opening programs in my taskbar, it's a small quality of life thing but it would be really nice to have. I also think a Windows 7 style taskbar could look pretty cool and I really do miss that transparent aero look it had

**Comment by SigmaTel71** [comment]
Possible duplicate of #215.

**Comment by lvzxr** [comment]
oh yea definitely is
