### ISSUE TITLE
add progressbar on taskbar

### ISSUE THREAD

**Issue by 111ebobo** [dremin/RetroBar#387]

**Comment by 1280px** [comment]
I think they meant the taskbar items progress state integration ![изображение](https://user-images.githubusercontent.com/71165491/181308606-da3b8069-86cc-404e-af4b-ef310d7a6131.png)

**Comment by 111ebobo** [comment]
> I think they meant the taskbar items progress state integration ![изображение](https://user-images.githubusercontent.com/71165491/181308606-da3b8069-86cc-404e-af4b-ef310d7a6131.png)
> 

Yes I meant this

**Comment by dremin** [comment]
Adding a textual indicator for this. Since the feature didn't exist until Windows 7, showing a progress bar would reduce theme accuracy, but the information is still very good to have.

**Comment by 111ebobo** [comment]
> Adding a textual indicator for this. Since the feature didn't exist until Windows 7, showing a progress bar would reduce theme accuracy, but the information is still very good to have.

It exist in vista

**Comment by xoascf** [comment]
> > Adding a textual indicator for this. Since the feature didn't exist until Windows 7, showing a progress bar would reduce theme accuracy, but the information is still very good to have.
> 
> It exist in vista

No:
https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nn-shobjidl_core-itaskbarlist3

**Comment by Nazeeh114** [comment]
what i belive is that the progress bar should be relating to the current operating software theme. meaning that if the user has selected the theme windows xp and it's sub themes they should not be able to see the progress bar. but if the user has selected windows 7 or any other operating software that had progress bar natively enabled in the taskbar, the user who chose the particular theme should be able to see the progress bar.

**Comment by BobbyMcJefferson** [comment]
I know this feature is officially completed but for me it doesn't work. When I'm downloading something in Firefox for example, without RetroBar on it will show my download progress in the taskbar but not with RetroBar enabled.
