### ISSUE TITLE
Windows XP task bar/start button font smoothing.

### ISSUE THREAD

**Issue by wordpass1** [dremin/RetroBar#391]
Windows XP's start button had a smooth font, But items in the task bar did not.
![image](https://user-images.githubusercontent.com/102382867/181152780-c48b4d94-657e-493b-89f5-ddf2409f7052.png)

**Comment by 1280px** [comment]
In XP you can disable the button font smoothing, as enable it for all the taskbar as well.
I guess this should be a separate option, enabled by default for XP.

**Comment by dremin** [comment]
Maybe it would make sense to always use font smoothing for the XP start button.
