### ISSUE TITLE
Start Button Second Monitor / Quick Launch Taskbar Spacers

### ISSUE THREAD

**Issue by adamshumpisxxx** [dremin/RetroBar#396]
I wish I had an option for a Start button on my second monitor. Everything else shows up except that. If I'm doing something wrong, please tell me. Also, the original Windows 98 / SE had these nub spacers between the Start button, Quick Launch and the rest of the Taskbar that I'd love to see come back / be able to move them around (reference below).

https://imgur.com/a/UMkHCSt

Thanks for all the work you have done / do!

**Comment by Humper04** [comment]
I have the same thing that the start button is only shown on my main monitor and not on my second monitor. I would like to see the start button on all my monitors if that is possible. 


Left is second, right is main: https://drive.google.com/file/d/1CjwY9VjISLzG92zKUiS8YGV-24zM05r4/view?usp=sharing

Thanks for everything that is done and is planned so far. Keep it up!

**Comment by dremin** [comment]
Start button on multiple displays is a duplicate of #158. Quick launch spacers/nubs are in the latest releases :)
