### ISSUE TITLE
Start button bug still not fixed with non-English language and/or 3rd party Start menu

### ISSUE THREAD

**Issue by Frapoo** [dremin/RetroBar#40]
It got a delay for the correct thing for >5secs
but is recovered after it

**Comment by dremin** [comment]
Could you please explain? Are you using the Windows 10 start menu, or a different one?

**Comment by Frapoo** [comment]
Both with default and classic shell

**Comment by Frapoo** [comment]
*open shell

**Comment by dremin** [comment]
I would expect the open shell menu to still not use the right behavior, but the default one should. Is your system set to English, or another language?

**Comment by Frapoo** [comment]
Chinese

**Comment by dremin** [comment]
Thanks! I think I now see what is going on here and will take a look.

**Comment by Frapoo** [comment]
https://drive.google.com/file/d/1CEDYsswPNDrcFFPJphY12NkNMuy7_8vc/view?usp=sharing
poorly edited but hope you can understand

**Comment by Frapoo** [comment]
Yup, I tried with English and Default Start menu and I knew that it was fixed.

But not with Open Shell/other languages,
One of them will break it.

**Comment by dremin** [comment]
Could you please check if [this build](https://github.com/dremin/RetroBar/suites/3527107574/artifacts/84300030) fixes the start button issue when using the default Windows start menu and Chinese? I believe it should work now.

**Comment by Frapoo** [comment]
I was busy so I didn't notice your reply before, I will take a look when I am free.

**Comment by Frapoo** [comment]
![image](https://user-images.githubusercontent.com/61443778/134294451-1b3ebb5c-6cd4-4927-9c32-8e75adbae567.png)
Thx, now it is working.

**Comment by Frapoo** [comment]
but still, 3rd party Start menu still got this bug.

**Comment by dremin** [comment]
This is fixed in the latest release.
