### ISSUE TITLE
[Request] Some missing TaskBar Icons from standard Windows 10/11-Features, esp. the search button and optionally the TaskBar-integrated search bar.

### ISSUE THREAD

**Issue by SlitEye** [dremin/RetroBar#407]
Currently there are some missing TaskBar Icons from standard Windows 10/11-Features, esp. the search button and optionally the TaskBar-integrated search bar.

But also some other Buttons/TaskBar Icons: Search, Show Desktop, Switch Desktop, Windows Store, UWP Apps etc.:
![2022-08-03_17h05_45](https://user-images.githubusercontent.com/24313436/182646958-0cc40a2e-9454-49d7-8884-03f2d003997c.png)

![2022-08-03_17h16_13](https://user-images.githubusercontent.com/24313436/182648457-47de748d-c673-4717-8969-1b4cc298a60e.png)

I know, some of these feature are not avaiable in the past (e.g. 98/XP), but if I / we use RetroBar on a actual system, we expect the old theme, but also that all TaskBar-Icons (of all TaskBar sections) from the origin TaskBar are also available on Retro Bars.

So it would be nice if you could implement these TaskBar icons (and corresponding functional triggers) for RetroBar (of course only if the underlying operating system has these features, but that could be identified automatically).

It would be nice to be able to optionally enable/disable these buttons.

**Comment by ARBlueSlime** [comment]
Use quick launch for Show Desktop, Windows Store and other apps, search will be in the start menu. For start menus you can use Open Shell or StartIsBack (You might encounter bugs tho, I haven't tested this for Windows 11, for Windows 10 works fine.)
