### ISSUE TITLE
[Bug/Request?] Missing TaskBar thumbnails hover

### ISSUE THREAD

**Issue by SlitEye** [dremin/RetroBar#408]
Hello Together, 

with RetroBar I miss the thumbnails of startet/used programs when I hover over it.

Without RetroBar is works fine. With RetroBar I miss this standard OS feature (avaiable since Windows 7).

It would be nice to be able to optionally enable/disable this feature at RetroBar.

![2022-08-03_17h06_48](https://user-images.githubusercontent.com/24313436/182650930-ba5106bf-59f1-4b2e-a9dd-e3153e832f66.png)

**Comment by ARBlueSlime** [comment]
I don't want to be the "BUT" guy... but its from Vista, not 7, 7 only added some more functionality to certain apps (music players get a small control panel with the preview window for example)

**Comment by SlitEye** [comment]
> I don't want to be the "BUT" guy... but its from Vista, not 7, 7 only added some more functionality to certain apps (music players get a small control panel with the preview window for example)

Correct, nice Vista.

**Comment by tunedal** [comment]
If this feature is implemented, the toggle to completely disable it would be the most important part to me. Getting rid of this feature after a Windows update re-enabled it is the whole reason I started using RetroBar.

**Comment by SlitEye** [comment]
> If this feature is implemented, the toggle to completely disable it would be the most important part to me. Getting rid of this feature after a Windows update re-enabled it is the whole reason I started using RetroBar. (Which is to say that while this is a useful feature, the guaranteed absence of hover popups is also a useful feature, so a toggle would be nice.)

Correct. Such Features should be options. I like this feature, so I would like activate it. You not, so you can deactivate it.

**Comment by PastaSource** [comment]
This is the only thing preventing me from dailying this. A very useful feature in terms of productivity for me, hopefully it'll be implemented at some point.

**Comment by dremin** [comment]
I've started working on this for the next release. It will be optional (off by default).

**Comment by PastaSource** [comment]
> I've started working on this for the next release. It will be optional (off by default).

legend, can't wait!
