### ISSUE TITLE
Start menu overlaps Windows Vista Orb

### ISSUE THREAD

**Issue by ARBlueSlime** [dremin/RetroBar#411]
Edit: image added (note: I was using Open Shell here, BUT this happens with the default start menu as well)
![image](https://user-images.githubusercontent.com/46797392/183247048-16a86dac-f2a9-4b68-be77-9bb5189dbfa6.png)

Pretty much what the tittle says.

**Comment by FoxbitDreamtail** [comment]
Honestly, this isn't a major deal. However I do agree that it is mildly annoying. It's just a layering issue. It doesn't affect how the system is used.

**Comment by dremin** [comment]
The Start menu in newer versions of Windows always appears above all desktop apps due to some special privileges that explorer.exe has. More info regarding this is here: https://blog.adeltax.com/window-z-order-in-windows-10/

I don't believe it is currently feasible to fix this.
