### ISSUE TITLE
Unable to collapse quick launch

### ISSUE THREAD

**Issue by ARBlueSlime** [dremin/RetroBar#412]
More of a missing feature rather than a bug with something existing. There is no option to collapse the quick launch into just a few that show 24/7.

**Comment by TheDolphinSlayer** [comment]
Yeah this would be a nice feature to have! A flyout menu that shows the other icons, it just takes up too much space, though I am greatful we can even pin them in the first place
![Screenshot 2023-04-15 005815](https://user-images.githubusercontent.com/73983610/232183940-090dd774-41cb-4410-8aab-5b2ccf929069.png)

**Comment by dremin** [comment]
Closing as duplicate of #377.
