### ISSUE TITLE
[suggestion] Retrobar + add Shell Enhancement for wine ( if [Retrobar => Wine] start shellenhamcement plugins and runtimemanager and Bar at right side)

### ISSUE THREAD

**Issue by blackcrack** [dremin/RetroBar#415]
Hi,
why supports Retrobar not via plugin-dll in Linux a Shell replacement for have a surface and a startpaneel for Wine in a Linux-Desktop ?
by start checks retrobar if have a wine-environment and which version of emulated WinNt is running, then use the right theme and place the Retrobar at first on the "Right" (not left side) side and make it able for start/add OpenShell as Startmenu.. this could be cool for the whole Linuxcommunity who use wine as WinNT environment and therewith could be Retrobar the head of the Wine-environment :) So, not only developing for MS-WinNt, nope, Useable also in a Wine-environment + plugins for more makea real WinNT(Windows-environment) for have better running Windows-programms aaand have a Startmenu for Wine in a Linux Windowmanager environment, like Plasma(Kde) and Gnome, i use plasma.. and then use the Retrobar as enhancement in Wine at the desktop :), first Start at the right side and later configurable like the user whant,on top, left or, if works bottom..
If this works, could be Retrobar also as a Windowmanager with wine-subsystem as a run allone behind the KDM/Sddm or Gdm
this would be a great huge thing imho, if this be able and possible..
need just easy "wine /path/to/retrobar.exe" in a script for run wine in Linux with Retrobar as Surface and starter of diffrent programms.. so, could be really cool.. and usable for the huge wine-community.. in Linux too....
and i bet, if Retrobar supports wine with runtime plugins, gives imho manny more peoples who works in Linux and deliver paches for Retrobar !
best regards
Blacky

**Comment by blackcrack** [comment]
hey @xoascf /Amaro if comes anyone there with a stored  and not active used Account and becomes off topic and start with multi Systems and arch.. and i have a tread with Wine only tread and he want with all force speaks about .Net dependency and so on.. can't i defend me by self  and close the tread and make a new open ?

and then do you get a thump down...  with no explanation... wow... and close it directly.. wow..
what for a support for an ass with an stored and not often used account who goes off topic ....
and this by a more as 25years Computergeek .. i be very disappointed ..


info for @dremin

**Comment by dremin** [comment]
Hi @blackcrack - RetroBar does function with wine currently, albeit not very well. Full functionality here would be dependent on wine adding support for more of the underlying win32 APIs that RetroBar uses.

There are currently no plans to add plugin/extensibility support to RetroBar, but if that does come in the future it will be in the form of providing a Start menu via plugins.

Apologies this got closed without explanation earlier!

**Comment by blackcrack** [comment]
Hi @dremin Sam :) \*happy*

well, Reactos works together with Wine in developement of Reactos and Wine isuse it as WinNT Subsystem.. and because Reactos ... both is open source.. 
could it somehow takes dll's from Reactos to Retrobar for fullfill the WinNT compatibility in Linux Wine.. 
humm.. a idea/suggestion could it be ..
so, Reactos it is a "tested" winNT System on win32/64 in development and could serve as dll resource to make Wine more compatible for Retrobar ... so just as idea ...
I know, Reactos is still alpha, but Programms runs in Reactos and i bet Retrobar also and give therewith a higher compatibility as wine alone, therewith could beat 2 fly's in one slap... : Hold the Compatibility to Reactos and make it more Compatible in Wine with Reactos DLL's at linux (so libraries from Reactos) therewith it could also gives to found bugs and codeparts who need reactos to run/be more compatible to WinNT(M$) .. you see what i meant ;) :)  
best regards
Blacky

**Comment by SlitEye** [comment]
> Hi @dremin Sam :) \*happy*
> 
> 
> 
> well, Reactos works together with Wine in developement of Reactos and Wine is use it as WinNT Subsystem.. and because Reactos ... both is open source.. 
> 
> could it somehow takes dll's from Reactos to Retrobar for fullfill the WinNT compatibility in Linux Wine.. 
> 
> humm.. a idea/suggestion could it be ..
> 
> so, Reactos it is a "tested" winNT System on win32/64 in development and could serve as dll resource to make Wine more compatible for Retrobar ... so just as idea ...
> 
> I know, Reactos is still alpha, but Programms runs in Reactos and i bet Retrobar also and give therewith a higher compatibility as wine alone, therewith could beat 2 fly's in one slap... : Hold the Compatibility to Reactos and make it more Compatible in Wine with Reactos DLL's at linux (so libraries from Reactos) therewith it could also gives to found bugs and codeparts who need reactos to run/be more compatible to WinNT(M$) .. you see what i meant ;) :)  
> 
> best regards
> 
> Blacky

Sorry, but first get to grips with Wine and ReactOS.

It is more likely that ReactOS uses Wine as a WIN API replacement than vice versa.

And ReactOS still covers far too little for anything to work. And it is even less useful to use ReactOS DLLs in Wine.

As I wrote before (was annoyingly deleted here), you should rather make your wish known to the WineHQ project, not to the RetroBar project.

From the RetroBar project's point of view, the exclusive use of .NET 6 cross-platform APIs and possibly a cross-platform GUI framework would be advisable.

**Comment by blackcrack** [comment]
Reactos is use Wine dll's, youre right and i be ca more as 25 Jears in the net.. i was
as Member in the reactos project and was in before the bastard Daniel Raimer it was,
later have this ass all done to kick me out and an couples good peoples also.. so, ,
thank you for you kill the Idea and "it can not works" and "My opinion is this" blabla..

more better would be if this Project stay on wxbasic .. or maybe not ?
bblubb .. i have speak here about a more supporting and better supporting in Wine,
because the Peoples in Reactos build by self the needed Api and the compatibility, 
SlithEye, on this do you not think.. you want bring in your Net-Ass in any case... and nerves every futher with this f..\*beep* Idea and offtopic and therewith have you kill this tread again.. so f\*beep* up and thanks for killing my treads !

this project don't need .Net 6 in my opinion, it is pretty well how it is now and i be thankful for this super well working Program
