### ISSUE TITLE
Unable to make the taskbar multi-row

### ISSUE THREAD

**Issue by ARBlueSlime** [dremin/RetroBar#416]
Another feature request rather than a bug, originates from Vista
Multi-row taskbar, normally windows allows you to use up to half of the screen if you feel like it, but that's way overkill, I suggest a max of 3 rows
![image](https://user-images.githubusercontent.com/46797392/183247411-b65a916b-be03-4411-9432-5e7827b57a0d.png)

**Comment by dremin** [comment]
Duplicate of #14
