### ISSUE TITLE
[Bug] Open-Shell start menu is often positioned 6 pixels too far down

### ISSUE THREAD

**Issue by SL6464** [dremin/RetroBar#430]
About 80% of the time when you click the start button, the menu that appears is 6 pixels too low, causing it to overlap with the taskbar.

![Incorrect Position](https://user-images.githubusercontent.com/73923583/187140024-54077200-14fc-49e9-8378-6acc9c2ab3d0.png)

It doesn't do this every time.  Sometimes, it is correctly positioned.

![Correct Position](https://user-images.githubusercontent.com/73923583/187140067-3ac947fe-17ad-4a13-9032-c902d5152601.png)

I've tried a number of different styles/options within Open-Shell, and it happens no matter what type of start menu is selected (classic/XP/7).

I also wanted to see if it affected other third party start menus, so I tried IObit's Start Menu 8.  That one was correctly aligned on every press, which suggests it may be a problem with Open-Shell, but it's worth noting I've never experienced this issue a single time in my 7+ years of using Classic/Open-Shell and it only happens even now when RetroBar is also running.

The issue happens whether you actually click the button or press the Windows key.

I'm running Windows 11 21H2, but this issue presents on all the versions of Windows 10 I've tried too (including 21H2).

Any ideas?

**Comment by SL6464** [comment]
I've discovered a clue.

I'm using the classic theme and ExplorerPatcher.  I've noticed that if you have "Enable advanced mitigations for correct rendering using classic theme" under Advanced ticked, this error never happens and the start menu is always placed correctly.  However, for reasons that don't  really matter, I don't have that ticked and do not want it ticked.  Hopefully this at least helps figure out what the issue is.

**Comment by LogoFun13-YT** [comment]
Within the Menu Look tab of the Open Shell menu settings, did you have "Align start menu to working area" enabled? If you don't, enable it. This should help fix the issue.

**Comment by xoascf** [comment]
If you think about it, this is quite similar to the default behavior when opening the Start menu with the classic theme in other OSes:

![StartMenuOpen95](https://user-images.githubusercontent.com/28744392/200215883-5959b61b-5111-43ed-905a-494344ff89dc.png)
![StartMenuOpenXP](https://user-images.githubusercontent.com/28744392/200215427-e4d8308e-af5b-47e9-ba3a-e66dedda1240.png)

**Comment by SL6464** [comment]
> Within the Menu Look tab of the Open Shell menu settings, did you have "Align start menu to working area" enabled? If you don't, enable it. This should help fix the issue.

This seems to have fixed it.  Thanks!
