### ISSUE TITLE
It displays random stuff like "" and "Microsoft Text Input"

### ISSUE THREAD

**Issue by NeptuneSocket** [dremin/RetroBar#432]
Hello, there is a issue, it displays system processes like Microsoft Text Input and Explorer, how do I fix that?

**Comment by ARBlueSlime** [comment]
Could you post some images? I'm not sure what you mean

**Comment by NeptuneSocket** [comment]
![Capture](https://user-images.githubusercontent.com/111225431/188100141-0bcb3e03-2275-4a47-aaa8-c24d5cd3da22.PNG)

**Comment by NeptuneSocket** [comment]
Also when you start RetroBar it displays a whole bunch of Metro apps.

**Comment by ARBlueSlime** [comment]
huh.., never saw this before, is the windows install clean or did you make changes? debloating, stuff relating to the theming maybe ?
also what version of windows are you using?

**Comment by dremin** [comment]
Is RetroBar running in compatibility mode by chance?

**Comment by NeptuneSocket** [comment]
No, I'm using windows 10.

**Comment by NeptuneSocket** [comment]
It was on compability mode, thanks!

**Comment by dremin** [comment]
No problem, glad we were able to take care of the issue!
