### ISSUE TITLE
Retrobar not starting because doesn't find .NET 6.0.8, but it's installed.

### ISSUE THREAD

**Issue by ShadowOfPripyat** [dremin/RetroBar#435]
After installing all the .NET Frameworks, Retrobar Doesn't start anyway. And whenever I click "Get the missing frameworks" it closes without doing anything.
![image](https://user-images.githubusercontent.com/73404930/188832435-d8ca5707-3e49-48ac-9fd0-faafaace9a57.png)
![image](https://user-images.githubusercontent.com/73404930/188839623-cb58097e-2b92-402c-bccf-a2f725ca12be.png)
I installed .NET 6.0.8 and 3.5.

**Comment by xoascf** [comment]
You need to install the requirement .NET 6.0 Runtime, it should be listed as "Microsoft Windows Desktop Runtime".

Download it from https://dotnet.microsoft.com/en-us/download/dotnet/6.0/runtime
![dl](https://user-images.githubusercontent.com/28744392/188974959-715be2b3-5257-4e1e-83d3-3c2dd63de392.png)

**Comment by ShadowOfPripyat** [comment]
I already did that 5 times and still not working.
