### ISSUE TITLE
Few problems

### ISSUE THREAD

**Issue by Lee-chanson** [dremin/RetroBar#436]
My first problem is that when I right click the apps on the taskbar it opens up an icon tester that has different resolutions of the icons for the app I'm clicking.

![Screenshot 2022-09-12 143640](https://user-images.githubusercontent.com/113382486/189731032-3c3dc9c2-b11b-4174-98b3-af0a64117abf.png)

My second problem is that I don't know how to edit the quick select icons.

![Screenshot 2022-09-12 143817](https://user-images.githubusercontent.com/113382486/189731101-14a7e30d-5c40-474e-94ad-dd22da3af40e.png)

And my final problem is that on my second monitor it has icons only for open apps while my main monitor has text and everything. I would like to know how to change that so my first monitor is like my second.

main monitor
![Screenshot 2022-09-12 143911](https://user-images.githubusercontent.com/113382486/189731120-57929529-e70d-4268-9b2e-69229dec1ee0.png)
second monitor
![Screenshot 2022-09-12 143926](https://user-images.githubusercontent.com/113382486/189731137-788b9037-9326-4980-8c84-0aff1907ba4d.png)

Thank you I greatly appreciate it.

**Comment by dremin** [comment]
To be honest, the app in the screenshots doesn't look like RetroBar. I think you're running SimpleClassicThemeTaskbar. You can download RetroBar from here: https://github.com/dremin/RetroBar/releases

**Comment by Lee-chanson** [comment]
I guess I downloaded so many things then uninstalled and re-installed I forgot what I had lol.

**Comment by dremin** [comment]
No worries!
