### ISSUE TITLE
Start Retrobar as a service to show sooner

### ISSUE THREAD

**Issue by ghost** [dremin/RetroBar#440]
I would love to see Retrobar made into a system service (like classicsounds XP program) so it starts before "explorer.exe". That way it would already be running when the user's desktop loads. It's fine the way it is but it doesn't load right away, leaving the system toolbar and start button visible for quite a while.
 One other thing I'd like to see fixed: if Retrobar is running, I can open another instance of it, causes problems like the program slowing down. Then if I close the currently running instance, the second instance loads (even a long time later).
 If Retrobar is already running, a second instance should either "replace" the first instance, or be ignored.
Thanks for this awesome program, I like it :)
(EDIT) ... the tooltip over the Start button sticks sometimes and does not go away. Maybe some code which turns it off when the mouse pointer is not over the start button?

**Comment by batcaalex** [comment]
This is a must! I only created an account to say this! Devs if you see this you must do it if you, sometimes it is really bothering!

**Comment by plopilpy** [comment]
I second this.

**Comment by dremin** [comment]
One thing you can do to make RetroBar start much sooner is to add it to Task Scheduler set to start at logon. However, keep in mind that from time to time (I've noticed it mostly the first logon after applying Windows updates) this causes RetroBar to start _before_ Explorer, which can cause neither to work properly until they are restarted in the proper order.

**Comment by blackwidowfarms** [comment]
thanks dremin for the information... would a line of code solve that issue? perhaps a "WinWaitActive" type command which waits until Explorer is active before running RetroBar (triggered on/off by a checkbox in options). I wonder if this, coupled with programatically adding RetroBar to Task Scheduler might work to open it earlier (if adding as a service isn't an option. I looked into that and was drowning in information lol)

**Comment by dremin** [comment]
> One thing you can do to make RetroBar start much sooner is to add it to Task Scheduler set to start at logon. However, keep in mind that from time to time (I've noticed it mostly the first logon after applying Windows updates) this causes RetroBar to start _before_ Explorer, which can cause neither to work properly until they are restarted in the proper order.

The issue described here is fixed by the fix for #96, so RetroBar should now reliably work when being started via Task Scheduler.

**Comment by RogerYao-Dev** [comment]
[The solution is here.](https://github.com/dremin/RetroBar/issues/1224)
