### ISSUE TITLE
How to put an image between the quick launch toolbar?

### ISSUE THREAD

**Issue by ItsMeSaturn** [dremin/RetroBar#442]
I am making a Windows 2000 theme for Retrobar that is designed to be as accurate as possible to the real thing.
I want to put an image, in this case seperation lines between the quick launch toolbar [as shown here](https://media.discordapp.net/attachments/889255367433936899/1024016265410519040/unknown.png), and I haven't been able to do much. **Keep in mind I don't want it to be adjustable, I just want the lines and that's it.**
I only managed to make some 'dummy icons' in the folder where the quick launch is, but it has 2 problems: it's not as long as it is in win2k, and there is a bunch of space between the program buttons and the start button [here](https://media.discordapp.net/attachments/889255367433936899/1024015284991967313/unknown.png).

**Comment by blackwidowfarms** [comment]
I remember those lines, they are when the taskbar is "unlocked" and they allowed users to "slide" the sections of taskbar left and right to adjust their location. Were those lines also there when the taskbar was locked?

**Comment by xoascf** [comment]
That is the taskbar grip (rebar gripper), and it is only visible when the taskbar is not locked.

>**Keep in mind I don't want it to be adjustable, I just want the lines and that's it.**

Btw, maybe in the future in RetroBar:


[https://youtu.be/DtphSIeMstY](https://user-images.githubusercontent.com/28744392/192922854-9c3d23ea-a523-4992-b8da-88e9b28214ab.mp4)

**Comment by blackwidowfarms** [comment]
ok that's the coolest video ever about "locking your taskbar" lol had to say 🙂
________________________________

**Comment by dremin** [comment]
> Btw, maybe in the future in RetroBar:
> lockthetaskbah.mp4

This is now available in 1.13!
