### ISSUE TITLE
Does RetroBar modify the Windows registry?

### ISSUE THREAD

**Issue by sarahgal** [dremin/RetroBar#443]
I want to use RetroBar, but first, I want to confirm if the Windows registry or other files will be modified or replaced by RetroBar.

**Comment by xoascf** [comment]
Only one if the "Automatically start at logon" option is checked:
https://github.com/dremin/RetroBar/blob/c506e91f30bb00418db95705c90196bbc3c6dd68/RetroBar/PropertiesWindow.xaml.cs#L177-L187
