### ISSUE TITLE
Stopped working, won't open again

### ISSUE THREAD

**Issue by mello418** [dremin/RetroBar#449]
This is my first time using github, not sure if this is the right place to ask for help.

Retrobar simply does not work for me. I open the program and all it does is hide my normal taskbar. Nothing else. Was working before! but it crashed and refused to work since then. I havent seen anyone with this issue, and im running out of ideas. Please help.

(in case it matters; yes i restarted the pc. yes i uninstalled. yes i reinstalled and tried again. nothing; i repaired the window desktop runtime. yes i uninstalled it too. yes i reinstalled. yes i tried older versions of both this program + retrobar. None of it worked)

**Comment by dremin** [comment]
If it was working previously, you could try deleting the `%localappdata%\RetroBar` folder to should reset the settings. Do you get any error messages for RetroBar in the Windows application event log?

**Comment by dremin** [comment]
Closing due to no response.
