### ISSUE TITLE
Windows 7 style taskbar.

### ISSUE THREAD

**Issue by Techfromthepast123** [dremin/RetroBar#451]
Can we get windows 7 styles ?
Because i am making windows 11 look like windows 7.
And I use windowblinds 11 for the theme.And startallback for the taskbar.
The problem is windowblinds 11 conflicts with startallback because windowblinds 11 skins the taskbar and without startallback.The taskbar is not accurate.There are not the old jumplists with the borders like in windows 7.
Will it be possible to add windows 7 styles ?
Aero,basic and classic styles ?

**Comment by TheDolphinSlayer** [comment]
I saw @dremin added support for taskbar thumbnails so its quite possible! If we can't get the windows vista/8 taskbar jumplist, I hope we can atleast have the hover over thumbnails on the taskbar. Pictures for what i'm talking about below, which samples colors from the icons for the aero hover
![image](https://user-images.githubusercontent.com/73983610/197623816-e7078886-d19e-4fa2-9c6c-9854794c5793.png)
![image](https://user-images.githubusercontent.com/73983610/197623883-e2711b5a-f6f9-4d63-acd2-df29391ffca4.png)
![image](https://user-images.githubusercontent.com/73983610/197623926-0b5b90f5-5a28-4a25-9354-9b691823cb15.png)
![image](https://user-images.githubusercontent.com/73983610/197624049-170ce492-af1f-445b-9e1a-09227aaeed22.png)
![image](https://user-images.githubusercontent.com/73983610/197624116-456b905c-7147-4333-99d2-015aad9e53fd.png)

**Comment by Techfromthepast123** [comment]
Also windows 7 basic has a list style.And windows 7 aero and classic has thumbnails.

**Comment by emeraldongithub** [comment]
that would be a good idea ngl. hope dremin adds it

**Comment by 111ebobo** [comment]
I think that windows 7 is not so retro to have it by default

**Comment by emeraldongithub** [comment]
so what about vista

**Comment by emeraldongithub** [comment]
ion think it's retro either

**Comment by BiatuAutMiahn** [comment]
I think anything before metro is retro ie; win8

**Comment by BiatuAutMiahn** [comment]
I'd say in terms of UI win7 with aero glass enabled was a all time favorite. I'd be using fan made versions on win10/11 if they were done right.

**Comment by BiatuAutMiahn** [comment]
Dup #45

**Comment by yusufmrzsincar256-lgtm** [comment]
i need this
