### ISSUE TITLE
Retrobar Crashes explorer

### ISSUE THREAD

**Issue by ThaBluNate** [dremin/RetroBar#457]
When explorer's shell restarts or opens with retrobar active, explorer crashes (making a crash loop of explorer)
Whatever this program does to keep the taskbar inactive in normal explorer seems to be crashing explorer on startup

`The shell stopped unexpectedly and explorer.exe was restarted.`
`Source: WinLogon`
`EventSourceName: Wlclntfy`
`Event ID: 1002`

**Comment by willdaboss** [comment]
I have the exact same issue it seems to happen whenever i open file explorer or Process explorer(better task manager in sysinternals)

**Comment by ThaBluNate** [comment]
Probably fixed by [the latest build](https://github.com/dremin/RetroBar/actions/runs/12064288618/artifacts/2248321339), as mentioned in issue #964. Will re-open if this appears again.
