### ISSUE TITLE
Windows 7 taskbars?

### ISSUE THREAD

**Issue by emeraldongithub** [dremin/RetroBar#465]
i kinda want a windows 7 taskbar ngl

**Comment by BiatuAutMiahn** [comment]
duplicate, and I think dev already said he's not going to do it. the vista theme was enough.

**Comment by 1280px** [comment]
Just use StartAllBack (11) or StartIsBack++ (10), they both allow to restore Aero/Metro taskbar look.

**Comment by TheDolphinSlayer** [comment]
> Just use StartAllBack (11) or StartIsBack++ (10), they both allow to restore Aero/Metro taskbar look by modifying the native taskbar's resources (which, actually, is a better solution than relying on a third-party one)

doesn't work with windows blinds which can restore aero transparency on windows 10 2004 - windows 11

**Comment by SL6464** [comment]
> Just use StartAllBack (11) or StartIsBack++ (10), they both allow to restore Aero/Metro taskbar look by modifying the native taskbar's resources (which, actually, is a better solution than relying on a third-party one)

This is fine for the Aero taskbar, but I would like a RetroBar theme which replicates the Windows 7 taskbar when the classic theme was enabled.  It's similar to the Vista one, but the spacing and start icons are a bit different.  IMO, this is worth including in RetroBar as Windows 7 was the last version to officially let you use the classic theme, and this program is all about recreating the classic taskbar.

**Comment by emeraldongithub** [comment]
> Just use StartAllBack (11) or StartIsBack++ (10), they both allow to restore Aero/Metro taskbar look by modifying the native taskbar's resources (which, actually, is a better solution than relying on a third-party one)

I would if Windowblinds stopped having problems with StartIsBack++.

**Comment by chloe-burbank** [comment]
i think a 7 basic theme would be cool but alas it may not happen in our lifetime

**Comment by BiatuAutMiahn** [comment]
> i think a 7 basic theme would be cool but alas it may not happen in our lifetime

I wouldn't say a lifetime it would take a few weeks tops to whip up a modern equiv of 7 Aero /w Blur.
