### ISSUE TITLE
Colour inversions on some system tray icons.

### ISSUE THREAD

**Issue by that1cutie** [dremin/RetroBar#467]
![image](https://user-images.githubusercontent.com/118422867/202368398-ca6f9e75-3fad-4963-b8e0-394885a39bcd.png)

This started suddenly with version 1.10. Technically not Windows 10 icons but otherwise unsure why this would be happening.

**Comment by dremin** [comment]
Ah, RetroBar only looks at the running OS version, not checking if the icons were changed from the defaults. You can disable invert in the theme; I've attached an example where I've disabled it on the Windows 95 theme.

[Windows 95 No Invert.zip](https://github.com/dremin/RetroBar/files/10028612/Windows.95.No.Invert.zip)

**Comment by that1cutie** [comment]
Oh, thank you for the fast reply! I can't tell where I'm supposed to put this theme to use it, however and I'm not skilled enough to recompile on my own. Is there a directory I'm missing somewhere in appdata or documents?

**Comment by dremin** [comment]
Oh, sorry, I forgot to include instructions! In the same directory as RetroBar.exe, create a Themes directory, then place the .xaml file from the zip into it.

**Comment by that1cutie** [comment]
This is perfect, thank you so much! Have been a fan of this since first release!

**Comment by dremin** [comment]
No problem, glad you are enjoying it!
