### ISSUE TITLE
Allow for the system tray icons to be hid

### ISSUE THREAD

**Issue by mareslem** [dremin/RetroBar#47]
It's in the title

**Comment by dremin** [comment]
Do you mean disabling the notification area completely, or selective per-icon such as [this dialog](https://media.askvg.com/articles/images/Notification_Area_Past_Icons_Win_XP.png)?

**Comment by pietrekkk** [comment]
> Do you mean disabling the notification area completely, or selective per-icon such as [this dialog](https://media.askvg.com/articles/images/Notification_Area_Past_Icons_Win_XP.png)?

Hi I'm not op but I would like to see the same option, because I use EarTrumpet.
I would add an option to move systray icons because it's second which I would like to see :)

**Comment by mareslem** [comment]
> 
> 
> Do you mean disabling the notification area completely, or selective per-icon such as [this dialog](https://media.askvg.com/articles/images/Notification_Area_Past_Icons_Win_XP.png)?

I mean disabling each icon individually. So yes, like this dialog

**Comment by dremin** [comment]
Added this in PR #208 for the next release.

**Comment by dremin** [comment]
This is now available in the latest release!
