### ISSUE TITLE
Colors on taskbar 

### ISSUE THREAD

**Issue by ohlev** [dremin/RetroBar#474]
Some programs that have a toggle between on and off display two colors to distinguish themselves but Retrobar doesn't emulate it.
Example: https://imgur.com/a/V0CZWPy

**Comment by dremin** [comment]
Apps set this by indicating an operation is in progress at 100%, and change it to red by indicating an error in the operation. RetroBar already handles progress, but hides it at 100%. Given that this is a bit of an abuse of that API, and I don't think this is feasible to implement in a way that respects the original OS appearances, I don't plan to handle it.
