### ISSUE TITLE
They should add this option

### ISSUE THREAD

**Issue by Chintrola** [dremin/RetroBar#477]
They should add an option so that the am of the time is seen in uppercase and that it looks more like windows xp

**Comment by BiatuAutMiahn** [comment]
I'd change title to `lower-case am/pm time like winxp`.

imo

**Comment by ThatRandomToast** [comment]
How is the way am/pm written looking like Windows XP? It's a regional settings.

**Comment by xoascf** [comment]
In the next release you will be able to change this format in Regional Settings:
![imagen](https://user-images.githubusercontent.com/28744392/226499437-52172870-1041-46df-a8d5-ad184a4de74c.png)
