### ISSUE TITLE
Resize the bar without changing the Windows DPI?

### ISSUE THREAD

**Issue by PicchiarelloMatto** [dremin/RetroBar#480]
![BarSize](https://user-images.githubusercontent.com/53583115/204902202-636e8549-0bb9-4242-9041-921b88da2527.jpg)
By editing the Vista theme file, I was able to increase the height of the bar, bringing the value to 40
    _<system:Double x:Key="TaskbarHeight">**40**</system:Double>_
and I changed the global font size to 14
    _<system:Double x:Key="GlobalFontSize">**14**</system:Double>_
this enlarges the buttons a bit, however they remain aligned towards the top.
Is it possible to center the buttons and icons in quick launch, adapting them to the size of the bar?

**Comment by dremin** [comment]
I will be adding a scale slider allowing this.

**Comment by dremin** [comment]
A scaling setting is available in the latest release.
