### ISSUE TITLE
RetroBar doesnt open.

### ISSUE THREAD

**Issue by gogo1701** [dremin/RetroBar#482]
I tried restaring, reinstalling and also saw the event viewer and the errors where these:

![image](https://user-images.githubusercontent.com/30569429/205435764-858940a3-7d7b-4c5d-8875-73bfceef2332.png)
![image](https://user-images.githubusercontent.com/30569429/205435776-f209e66a-ff57-4e5d-9fcb-3ac8fe45e50b.png)

**Comment by dremin** [comment]
Please try updating your version of .NET, it looks like yours is too old: https://dotnet.microsoft.com/en-us/download/dotnet/6.0/runtime

**Comment by dremin** [comment]
Closing due to no response.
