### ISSUE TITLE
RetroBar Needs a Windows 7 Theme!

### ISSUE THREAD

**Issue by Windows-7-Fan** [dremin/RetroBar#485]
I personally believe RetroBar needs a windows 7 theme!

**Comment by emeraldongithub** [comment]
based

**Comment by Windows-7-Fan** [comment]
> > I personally believe RetroBar needs a windows 7 theme!
> 
> I think we are not because it's not so retro

please elaborate.

**Comment by y2k04** [comment]
How is it not retro?

**Comment by Windows-7-Fan** [comment]
> How is it not retro?

no idea but it doesn't matter because they've closed this issue.

**Comment by SwiftyPeed** [comment]
> > I personally believe RetroBar needs a windows 7 theme!
> 
> I think we are not because it's not so retro

can you stop trying to prevent this theme from getting made

**Comment by 111ebobo** [comment]
> > > I personally believe RetroBar needs a windows 7 theme!
> > 
> > 
> > I think we are not because it's not so retro
> 
> can you stop trying to prevent this theme from getting made

no

**Comment by 111ebobo** [comment]
So, why windows 7 theme isnt retro. Because windows 7 uses Superbar which is used even today

**Comment by y2k04** [comment]
Honestly sad that it isn't a retro theme

**Comment by BiatuAutMiahn** [comment]
Many of us are, _we could_ (those of us who strongly desire win7 aero) fork this repo, and implement it.

**Comment by SwiftyPeed** [comment]
> Many of us are, _we could_ (those of us who strongly desire win7 aero) fork this repo, and implement it.

How do i fork again?

**Comment by SwiftyPeed** [comment]
i just forked it although idk how to make it lol.

**Comment by emeraldongithub** [comment]
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
💀💀💀💀then whyd you fork it

**Comment by BiatuAutMiahn** [comment]
1. Reimplement Aero 7 assets in RetoBar theme format maybe use Vista as a base.
2. study how RetroBar does it's painting to figure out where to start working on blur.
3. Use some graphics API that can capture the window session, mask out the taskbar region, then apply blur. Then let RetroBar do the rest of the painting.

This is just surface thought of how to go about it. It will take a LOT of R&D to pull this off. DWM Aero had access to hardware, each window, handeled Z-ordering etc.

Some old 3p software that used to work: TrueTransparency, maybe FastAero back in the WinXP days. you could always use an API call analyzer with these programs or even DWM and attempt to follow the calls, and analyze how the Blur is functioning.

**Comment by BiatuAutMiahn** [comment]
Scratch all of what I said previously, all the blur effects are already handled by RetroBar. Make use of msstyles Editor and port Win7 Aero over to RetroBar assets as said before...don't use the bitmaps, use inkscape or something to help with converting the bitmaps to SVG, then port those to RetroBar's format.
