### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by 111ebobo** [dremin/RetroBar#486]
Can you make a windows whistler candy theme? Also can you make a remake of launcher 8 for Android?

**Comment by Icepenguins101** [comment]
I actually made a Candy theme quite a while ago, I could send you the link for it if you want.

**Comment by 111ebobo** [comment]
Ok, I wanna try it

**Comment by Icepenguins101** [comment]
Here's my Candy theme. https://github.com/Icepenguins101/retrobar-candy-theme
