### ISSUE TITLE
Retrobar Needs a Windows 7 Theme!

### ISSUE THREAD

**Issue by Windows-7-Fan** [dremin/RetroBar#488]
I personally believe RetroBar needs a windows 7 theme!

**Comment by Windows-7-Fan** [comment]
> are you just going to spam the issues with this?
Spam???

**Comment by BiatuAutMiahn** [comment]
...it's very annoying and counter productive. Many of us want Windows 7 Aero theme., including myself. If you want it bad enough then reverse engineer 7's `aero.msstyles` a good start would be `msstylesEditor.` Although it doesn't fully support 7's implementation, it's enough to read and digest the theme enough to port it to something more usable like RetroBar. Focus on Glass/Blur should be last priority.

I'd do it, but atm there are more important things to worry about.

**Comment by BiatuAutMiahn** [comment]
Dup #45
