### ISSUE TITLE
Win 7 taskbar theme please

### ISSUE THREAD

**Issue by DefaultUser19865** [dremin/RetroBar#490]
please

**Comment by BiatuAutMiahn** [comment]
Dup #45

**Comment by mutoyoru** [comment]
On the first page, there are 5 'issues' that wants Windows 7 style taskbar and the same 'issue' is closed last week as 'NOT PLANNED'. If you want that so much, then there's a button up there, it's called 'Fork'. Clone the repo, make it yourself, and open a pull request. You can't make it yourself? Then, stop opening USELESS requests and stop harrasing people!

**Comment by DefaultUser19865** [comment]
I'm just simply asking them to add it. And how am I harassing people?

**Comment by BiatuAutMiahn** [comment]
It's not specifically targeted at you, it's at those whom keep spamming the issues.
