### ISSUE TITLE
Add quick back to desktop on setting

### ISSUE THREAD

**Issue by BHD1673** [dremin/RetroBar#495]
pls adding it

**Comment by 1280px** [comment]
There's already a [pull request](https://github.com/dremin/RetroBar/pull/169) to implement "Show Desktop" button, but for some reason it's been in drafted state for over a year now. However, you can compile it yourself, or fork [xoascf's fork](https://github.com/xoascf/RetroBar/tree/show-desktop-button) and download autocompiled version from thw "Actions" tab.

**Comment by dremin** [comment]
Duplicate of #84
