### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by arukateru** [dremin/RetroBar#496]
I am requesting Windows 7 Basic skin. I know it can be accomplished with StartIsBack++, but the reason for it is because when using StartIsBack++ with basicthemer2-detours or DWM disabled, the taskbar is black regardless of the settings. With the addition of a Windows 7 Basic skin, it would make for the possibility of maybe the most precise Windows 7 theme in existence.

**Comment by BiatuAutMiahn** [comment]
Dup #45

...I think

**Comment by 0x5066** [comment]
well it asks for a windows 7 theme so it is a duplicate

**Comment by emeraldongithub** [comment]
> I am requesting Windows 7 Basic skin. I know it can be accomplished with StartIsBack++, but the reason for it is because when using StartIsBack++ with basicthemer2-detours or DWM disabled, the taskbar is black regardless of the settings. With the addition of a Windows 7 Basic skin, it would make for the possibility of maybe the most precise Windows 7 theme in existence.

golden rule of retrobar is to never request windows 7 related shit otherwise your request will be beaten up by the duplicate patrol

**Comment by emeraldongithub** [comment]
and i don't think dremin wants to add it anyways so

**Comment by 0x5066** [comment]
stay mad

**Comment by BiatuAutMiahn** [comment]
I'm rooting for win7 aero too. Spamming the issues is going to make any chances of it coming about to be less likely. Thus the dup'ing

**Comment by 0x5066** [comment]
i mean, have y'all heard about forking the project and doing it yourself?

**Comment by 1280px** [comment]
> and i don't think dremin wants to add it anyways so

I mean, it does make sense. In Win7, taskbar was updated for the new dock-style behaviour ("superbar"), and the purpose of Retro-bar is to restore pre-Superbar one. Futhermore, there's already working solutions to skin modern taskbar to look like 7/8 one (e.g. WindowBlinds)

**Comment by BiatuAutMiahn** [comment]
WindowBlinds is commercial software.
