### ISSUE TITLE
Taskbar buttons don't appear when coming back from sleep/hibernation

### ISSUE THREAD

**Issue by SMUsamaShah** [dremin/RetroBar#499]
#439 added ability to show buttons on their own displays.

Sometimes, taskbar buttons don't appear on a display or don't appear for some windows.

I have two extra displays attached. Steps to reproduce are usually like:
- Windows open on all displays
- Hibernate
- Turn on the computer, login.
- (Since extra displays are connected via docking station, there is sometimes a lag and those displays don't turn on immediately. This also causes windows to swap between displays or move to other display.)
- (No shuffling/moving of windows happen, all windows are in the same place as I left while hibernating.)
- But now one of the Taskbars is not showing buttons for any of the windows on that screen.
- Workaround: Untick "Show on multiple displays", then tick again to refresh the buttons.

**Comment by plovlover** [comment]
I can confirm that this bug still persists on 1.13.30

**Comment by dremin** [comment]
[This build](https://github.com/dremin/RetroBar/suites/15621801091/artifacts/891584939) should fix the issue if you'd like to try it early.
