### ISSUE TITLE
Possibility of Vertical Position?

### ISSUE THREAD

**Issue by SMUsamaShah** [dremin/RetroBar#50]
My taskbar usually has lots of things and I like seeing titles and don't group taskbar buttons. That's why I put it left or right side of screen. 

Can this be done with RetroBar?

**Comment by 0x5066** [comment]
It'd be nice to have it placed on the top as well

**Comment by samiscoolest** [comment]
this to both, especially the top

**Comment by dremin** [comment]
Working on this :)

**Comment by dremin** [comment]
This is implemented in the latest release.
