### ISSUE TITLE
Retrobar crashes often

### ISSUE THREAD

**Issue by TwistedZeon** [dremin/RetroBar#504]
I've tried hardware/software rendering and no change happens, Retrobar will just kill itself after sometime. After taking a look at the logs it would seem it has something todo with .Net? Is this something on my end that I can fix or is this a fault with the program?

![image (1)](https://user-images.githubusercontent.com/8218882/211915118-e8691c6f-7e8e-4347-9250-7dd7e30da5c1.png)
![image (2)](https://user-images.githubusercontent.com/8218882/211915120-a3a85f00-f444-4649-870a-656ba34d9283.png)
![image (3)](https://user-images.githubusercontent.com/8218882/211915121-aebbf805-2a66-4803-8a3c-a368f609cb7b.png)
![image (4)](https://user-images.githubusercontent.com/8218882/211915122-51e6a847-8ce7-4485-848e-5d017ba2473c.png)
![image (5)](https://user-images.githubusercontent.com/8218882/211915123-4bf41a95-bed1-4e91-bf5f-676d646216ad.png)
![image (6)](https://user-images.githubusercontent.com/8218882/211915125-d0e3fd22-7ea2-44f2-bd17-6c3def7fa40c.png)
![image (7)](https://user-images.githubusercontent.com/8218882/211915126-6f4b6cb3-b918-4392-9417-ac1e238d1065.png)
![image](https://user-images.githubusercontent.com/8218882/211915128-f41e6d07-d126-482e-87a4-c79657ccc556.png)

**Comment by dremin** [comment]
Interesting, that is an audio DLL, and the only audio functions RetroBar calls are when a balloon notification is received. Does it sound plausible that you were receiving a notification from some app at the time of the crash? Do you have any audio issues on your system?

**Comment by TwistedZeon** [comment]
That is very interesting, it is quite plausible that I could have been receiving a notification at that time though I have the ones through windows muted. As for audio issues, none that I'm aware of.

**Comment by dremin** [comment]
When you say you have the ones through Windows muted, which setting are you referring to?

**Comment by TwistedZeon** [comment]
This is what I meant by muted, essentially just about any windows notification just goes to the notification area silently.

![image (8)](https://user-images.githubusercontent.com/8218882/212253892-bb1a8bbf-9c22-48b8-bee1-f0b5461883e4.png)

**Comment by TwistedZeon** [comment]
Okay so, I tried a few things and none of them triggered it e.g. MSN, Discord, Thunderbird all were fine notification/sound wise. However I finally saw it happen and it wasn't a sound related thing? I have two monitors, one with my browser open, the other with discord. I got a message on discord so I went to click the window to type and that's when Retrobar crashed.

**Comment by dremin** [comment]
Based on some things I saw online, I wonder if this is more related to device enumeration rather than audio playback. If you disable all of your audio devices, does the crash still occur?

**Comment by dremin** [comment]
Closing due to no response.
