### ISSUE TITLE
[feature-request] Windows 7 Taskbar

### ISSUE THREAD

**Issue by Bluscream** [dremin/RetroBar#507]
I love switching "OS" looks from time to time, just "upgraded" from WinXP to Vista. Would be nice if i could "upgrade" to windows 7 next :)

**Comment by 111ebobo** [comment]
Developer said no

**Comment by DatGamerYoloYT** [comment]
StartIsBack/StartAllBack may be useful to you as the superbar (the windows 7+ taskbar) is not what this was supposed to be for, it was supposed to be for the original taskbar (no pinning and no way to remove labels)

**Comment by dremin** [comment]
Duplicate of #45
