### ISSUE TITLE
System font is not respected on titles

### ISSUE THREAD

**Issue by yereverluvinunclebert** [dremin/RetroBar#509]
The windows system font, when set to an alternative, is not picked up by retrobar which still displays the default as designed into the application itself, arial I assume. It would seem only sensible to respect the system set font. Tested on Win 10 and 11.

My suggestion would be to have an option to: 
i.   Retain the arial by default on the app, 
ii.  Respect the system font
iii. Call the font selector to allow retrobar to display any user-selected font as distinct from the system font.

All my own apps allow the user to customise font. It makes for a familiar UI on each system.
This would allow a level of customisation that Win10/11 does not enable.

**Comment by arlobo1** [comment]
yeah, I would like to be able to change the font too, since I use Tahoma as my current system font
