### ISSUE TITLE
Trend Micro Enters An Anti-Virus False Positive In RetroBar

### ISSUE THREAD

**Issue by EpicBProgrammingOnReddit** [dremin/RetroBar#52]
Hello Everyone, I Have An Issue For That... Trend Micro Is Currently Installed Already & Downloaded RetroBar.zip. After Extracting, & Opening RetroBar.exe, Something Is Happening, Trend Micro Detected It As A Suspicious File & Removed It. I Think It's A False Positive Application, So Can You Remove This Annoying False Positive From Trend Micro?

**Comment by ToruTheRedFox** [comment]
they can't
contact Trend Micro instead

**Comment by FoxbitDreamtail** [comment]
it's because the app is not signed.... sadly, you can't sign it as the dev needs to.

**Comment by ToruTheRedFox** [comment]
which costs money might I add
