### ISSUE TITLE
Ideas & Suggestions

### ISSUE THREAD

**Issue by legacy1477** [dremin/RetroBar#523]
Some Needed Fixes/Adjustments:

- Add a way to disable logging. Some logs I found were over 200MB+ (PC ran 24/7)
- Add a way to refresh restore empty or bugged out tray icons. - I like to put my computer to hibernate (different from sleep, everything is stored on the drive), but when I resume some tray icons are invisible and not clickable at all. [only used the x86 build]
![image](https://user-images.githubusercontent.com/118707318/218308435-d2fbb171-305d-401d-ab25-c2d462599c69.png)
 Some have a weird placeholder icon. Attempted to delete temp files and etc, but had no effect. Only fully restarting PC did.
- Fix RetroBar from randomly using a new folder for settings. - Sometimes when it closes it no longer uses the same folder for settings and therefore resets. An easy solution is to have a way to specify a custom settings path for those who prefer it.

Suggestions:

- (Kinda Already Suggested) Windows 7 Basic taskbar theme. The operating system got mainstream support dropped back in 2015 and was fully dropped with ESU this year and is now no longer updated. It is also the last taskbar to feature gradients and some sort of detail compared to modern flat taskbars. I'd perhaps agree that replicating the Aero version would be too much work, but I'd definitely would love to see at least the Windows Basic version of the taskbar someday.
- Allow to manually change system tray icon colors. Sometimes they're white on white and not visible.
![image](https://user-images.githubusercontent.com/118707318/218308395-48229ee4-c789-465f-a1a0-d1e5a57b18e1.png)

**Comment by Icepenguins101** [comment]
The devs said they will not do a Windows 7 theme, and yes the placeholder icons are very annoying.

**Comment by dremin** [comment]
> Add a way to refresh restore empty or bugged out tray icons. - I like to put my computer to hibernate (different from sleep, everything is stored on the drive), but when I resume some tray icons are invisible and not clickable at all. [only used the x86 build]

What version of Windows are you using? Does this issue happen after every hibernate or only sometimes?
