### ISSUE TITLE
Thin black line appears over the taskbar when using Brave 

### ISSUE THREAD

**Issue by mrt505** [dremin/RetroBar#53]
İ'm using Windows 10 x64 LTSC 1809
My Radeon Software version is 21.6.1
İ have this problem when using fullscreen Brave Browser 
![Capture](https://user-images.githubusercontent.com/89605569/131019013-5b9ddd25-2267-4b26-8381-a65ed534b210.PNG)

**Comment by ToruTheRedFox** [comment]
this is not a problem exclusive to brave
I think this line is the original taskbar, specifically the line it leaves when hidden

**Comment by dremin** [comment]
I have a fix for this that I'll be implementing shortly.

**Comment by dremin** [comment]
A pre-release build with this fixed is [available here](https://github.com/dremin/RetroBar/suites/4346512920/artifacts/114026079) (link requires you to be logged into GitHub)

**Comment by dremin** [comment]
This is fixed in the latest release.
