### ISSUE TITLE
make the config files store in %localappdata% instead of %temp%

### ISSUE THREAD

**Issue by maxox** [dremin/RetroBar#543]
using software like CCleaner might delete files inside %temp% folder, that would cause the config files of retrobar gone
Better make them store in the %localappdata% instead

**Comment by xoascf** [comment]
Funny, I just deleted everything in `%temp%` and my settings are still there; same theme, same language.

You can check the settings, custom themes and languages in `%localappdata%\RetroBar` since [RetroBar 1.11](https://github.com/dremin/RetroBar/releases/tag/v1.11.15).
