### ISSUE TITLE
Windows flying

### ISSUE THREAD

**Issue by Raupy10** [dremin/RetroBar#551]
Hello.
I have the following problem with the retrobar:
Every time I start Retrobar and then open a window, this window hovers about 3 centimeters above the Retrobar.
Can you please fix this?
Thanks

**Comment by Raupy10** [comment]
And yes i turned on the "run with windows" feature in the Retrobar settings.

**Comment by 111ebobo** [comment]
> Ah! ok thanks. it works.

You're welcome
