### ISSUE TITLE
Window not filling screen

### ISSUE THREAD

**Issue by sheldonmac** [dremin/RetroBar#567]
Sometimes the window just does not fill the screen I tried restarting, did not work P.S Can you add a windows vista bar with the same color scheme as windows xp blue (:

![image](https://user-images.githubusercontent.com/89378970/236104707-4c1172eb-d56e-4a04-8b59-3387bfa508e0.png)

**Comment by dremin** [comment]
Recent updates have impacted RetroBar's ability to hide the default Windows taskbar. Before starting RetroBar, it is recommended to open Windows Settings > Personalization > Taskbar, select "Taskbar behaviors", then enable "Automatically hide the taskbar."

**Comment by Gockel67** [comment]
Hello Dremin,
I had exactly the same problem. Thanks for your tip. Really great work from you. I love it.

**Comment by dremin** [comment]
Closing as issue is fixed by the above comment.
