### ISSUE TITLE
Windows 10 Graphical Issues

### ISSUE THREAD

**Issue by WildRoseII** [dremin/RetroBar#57]
![retrobar issue #1](https://user-images.githubusercontent.com/89715050/131235602-9b219746-402e-451d-97d5-ae734e22ad1d.png)
![retrobar issue #2](https://user-images.githubusercontent.com/89715050/131235605-ff6a5b3f-27a4-4602-a7f4-971acdb439c9.png)
I really like the idea of having a Windows XP taskbar (and menu thanks to Open Shell), but graphical glitches like this keep occurring. Does anyone know what could be causing it, and how to fix it?
My laptop uses an Nvidia GeForce GTX 1070, not sure if that graphics card has anything to do with the problem but it might.

**Comment by dremin** [comment]
This is really strange, I do not see this on my machine with a GTX 1080. Have you tried updated video drivers?

**Comment by WildRoseII** [comment]
> This is really strange, I do not see this on my machine with a GTX 1080. Have you tried updated video drivers?

Indeed I have, and the problem still persists.

**Comment by dremin** [comment]
This should now be addressed with the new option to enable software rendering in the latest release.
