### ISSUE TITLE
Windows 2000 Desktop Icon replaces Windows XP Desktop Icon in modified XP Blue theme

### ISSUE THREAD

**Issue by DynamicOsi** [dremin/RetroBar#574]
For context, I created a copy of the Windows XP Blue theme and changed
``<system:Double x:Key="TaskbarHeight">30</system:Double>``
to:
``<system:Double x:Key="TaskbarHeight">31</system:Double>``
so that the taskbar could be one pixel taller and allign with OpenShell's XP Luna Start Menu theme.

**With change:**
![image](https://github.com/dremin/RetroBar/assets/94809883/c798e3c6-a9d7-4321-b0a8-5b1b947d49f3)

**Without change:**
![image](https://github.com/dremin/RetroBar/assets/94809883/241f78f8-9638-4353-9aa0-e26916a3b988)

### My Issue:
With the new update, I added the Show Desktop Button to my modifed theme and to my suprise, unlike the regular XP Blue theme, it applied the Windows 2000 desktop icon for the button.
![image](https://github.com/dremin/RetroBar/assets/94809883/00efccce-1c13-4bc3-aa80-261a46490a17)
 
Is it possible to change or remove the icon so that it maches with the regular, unmodifed XP Blue theme?
![image](https://github.com/dremin/RetroBar/assets/94809883/05fcda66-7f34-437e-958a-de701e64ca54)

It would also be nice if I could extend the lighter shade of blue used for the notification area so that to the right end of the taskbar, acting as the background for the Show Desktop Button but that would be a stretch... (literally)
**(terrible ms paint rendition)**
![image](https://github.com/dremin/RetroBar/assets/94809883/f1948dc3-1062-4315-af21-4c4b1ac9dae2)
Thanks!

**Comment by xoascf** [comment]
You may have copied an earlier version of the theme; if you want to make this change, you can inherit the properties of the original theme by referencing it within `ResourceDictionary.MergedDictionaries`.

That way, the XAML of your theme would look like this:
```
<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                    xmlns:system="clr-namespace:System;assembly=mscorlib">

    <ResourceDictionary.MergedDictionaries>
        <ResourceDictionary Source="Windows XP Blue.xaml" />
    </ResourceDictionary.MergedDictionaries>

    <system:Double x:Key="TaskbarHeight">31</system:Double>
</ResourceDictionary>
```
