### ISSUE TITLE
Program asks me to install .NET Core even after I've already installed it.

### ISSUE THREAD

**Issue by nussun-celestia** [dremin/RetroBar#58]
Hi, I'm getting an issue in which I can't run the executable, and it told me to install .NET Core, so I did. But even after I installed it, it still asks me to install it, as well as a bonus error saying "The framework 'Microsoft.WindowsDesktop.App', version '3.1.0' was not found."
![image](https://user-images.githubusercontent.com/69641920/131243533-8e5df122-a8ab-4045-a6aa-9336d412ee70.png)

**Comment by nubilate** [comment]
How did you resolve the issue? I keep getting the same error.
