### ISSUE TITLE
Retrobar breaks OpenShell on Windows 11 (hovering menu bug)

### ISSUE THREAD

**Issue by TheSystemGuy1337** [dremin/RetroBar#586]
This is a severe issue, as this makes Open Shell harder to use. RetroBar causes a bug where the start menu hovers over the taskbar instead of sitting on it. This is the bug in question:
![Untitled](https://github.com/dremin/RetroBar/assets/61162037/e00eaf24-a395-47e9-ad7b-aee9818a9af2)

**Comment by 111ebobo** [comment]
Turn on "show next to taskbar" and "show next to the working area"

**Comment by TheSystemGuy1337** [comment]
This fixed my issue. Now there's only a very minor overlap. Thank you

**Comment by weareallimaginary** [comment]
> 

open shell has offset option vertical offset 1 works great in my case
