### ISSUE TITLE
Do not add windows 7 theme

### ISSUE THREAD

**Issue by 111ebobo** [dremin/RetroBar#590]
Do not add windows 7 theme because first of all isnt retro, second of all we already have vista theme so we don`t need win 7 theme

**Comment by SwiftyPeed** [comment]
Please can it just be added

**Comment by SwiftyPeed** [comment]
Windows 7 came out like 13 years ago and Windows vista is 15 years old. And along with that the windows 7 taskbar is radically different compared to windows vista so please add it

**Comment by 111ebobo** [comment]
> Windows 7 came out like 13 years ago and Windows vista is 15 years old. And along with that the windows 7 taskbar is radically different compared to windows vista so please add it

No, win 7 taskbar almost the same as vistas one but with small differenced (also if you turn on show desktop in vistas taskbar and you will get the windows 7 beta taskbar

**Comment by SwiftyPeed** [comment]
So then by your logic you would say not to add the windows longhorn theme because it looks partially like the windows xp taskbar

**Comment by 111ebobo** [comment]
> So then by your logic you would say not to add the windows longhorn theme because it looks partially like the windows xp taskbar

Longhor taskbar looks way differnt than xp one but windows 7 taskbar is just vista taskbar without texture

**Comment by SwiftyPeed** [comment]
No the windows 7 taskbar is the windows vista taskbar but it is dramatically larger the start sphere does not stick out instead it is fully encompassed, the taskbar is entirely transparent so its not a black tint and different flyouts window popouts all that.
![dgtrdgdgr](https://github.com/dremin/RetroBar/assets/125750738/c9a74486-1913-4da9-b7f4-6def3f52b0c7)

**Comment by doubleddav** [comment]
I don't understand people's resistance to making "modern" themes. If the dev doesn't want to do it because he like things old school, that's fine. But if someone else wants to create a modern theme and merge it in what's the big deal? No-one will force you to use it

**Comment by 111ebobo** [comment]
> I don't understand people's resistance to making "modern" themes. If the dev doesn't want to do it because he like things old school, that's fine. But if someone else wants to create a modern theme and merge it in what's the big deal? No-one will force you to use it
Merged modern theme near old school themes doesn`t look appropriate

**Comment by xoascf** [comment]
If a Windows 7 theme is added, it will just be an additional option and you will always be able to choose other classic taskbar themes at any time.

**Comment by 111ebobo** [comment]
But still it won't look right
