### ISSUE TITLE
Jumplist and app window support

### ISSUE THREAD

**Issue by FireCubeStudios** [dremin/RetroBar#6]
![image](https://user-images.githubusercontent.com/40955345/104211252-245c6680-5434-11eb-9a96-0031cc304307.png)
add support for jumplists in the taskbar and if possible add a styling to them

also in windows 10 when you hover over an app there is a small window shown. pls add support for it

**Comment by Rex501st** [comment]
> ![image](https://user-images.githubusercontent.com/40955345/104211252-245c6680-5434-11eb-9a96-0031cc304307.png)
> add support for jumplists in the taskbar and if possible add a styling to them
> 
> also in windows 10 when you hover over an app there is a small window shown. pls add support for it

I believe this project is trying to replicate the classic Windows NT era taskbar; I can agree with the jump list for the XP and beyond themes, but as for the Window previews, I don't think it should be added as Alt-tab can be used.

**Comment by Rex501st** [comment]
> ![image](https://user-images.githubusercontent.com/40955345/104211252-245c6680-5434-11eb-9a96-0031cc304307.png)
> add support for jumplists in the taskbar and if possible add a styling to them
> 
> also in windows 10 when you hover over an app there is a small window shown. pls add support for it

I believe this project is trying to replicate the classic Windows NT era taskbar; I can agree with the jump list for the XP and beyond themes, but as for the Window previews, I don't think it should be added as Alt-tab can be used.

**Comment by dremin** [comment]
App windows on hover is being handled in #408. Jump list support and other Windows 7+ features are not planned.
