### ISSUE TITLE
Quick Launch seperators

### ISSUE THREAD

**Issue by snuskgubbe** [dremin/RetroBar#601]
in classic themes & windows 9x there was seperators around quick launch like this:
![image](https://github.com/dremin/RetroBar/assets/130178512/3e688d34-0f2a-4121-93ca-763e97b92821)
and they're just not there in retrobar:
![image](https://github.com/dremin/RetroBar/assets/130178512/76d24351-f07d-420a-acc4-40a9b32cd9bd)

would be very nice if someone added them

**Comment by dremin** [comment]
This was added in 1.13.
