### ISSUE TITLE
Is there a way to make it so tabs of chrome don't show individually like they are apps?

### ISSUE THREAD

**Issue by DrBrad22** [dremin/RetroBar#606]

**Comment by dremin** [comment]
I'm not sure I understand what you mean, each window shows as a single button for me. Could you please provide a screenshot of what you're seeing?

**Comment by DrBrad22** [comment]
![image](https://github.com/dremin/RetroBar/assets/136956759/6aabda15-1b1e-4bec-9d43-b1194027dcc9)
This is what I mean. Is there a way to change it so that each tab doesn't show individually?

**Comment by Dron007** [comment]
You probably mean separate browser windows, not tabs. I found it very cool that they are not glued together like in Windows 10 taskbar but I wish to get access to windows context menus.
