### ISSUE TITLE
Start Icons are green-ish how do i fix this?

### ISSUE THREAD

**Issue by NatanIsGone** [dremin/RetroBar#607]
Its kinda green how do i make the color normal?

**Comment by NatanIsGone** [comment]
Its kinda green how do i make the color normal?

**Comment by dremin** [comment]
Hm, could you please provide a screenshot of what you are seeing with green icons?

**Comment by NatanIsGone** [comment]
![Desktop-screenshot (12)](https://github.com/dremin/RetroBar/assets/103850738/583210af-1264-4153-b573-c6386e3df30e)

**Comment by NatanIsGone** [comment]
> Hm, could you please provide a screenshot of what you are seeing with green icons?

![Desktop-screenshot (12)](https://github.com/dremin/RetroBar/assets/103850738/de2cfde2-6671-4756-ace0-c6f08d397a83)

**Comment by NatanIsGone** [comment]
Like the start icon looks a little bit greener how do i fix it to make it have the normal color

**Comment by dremin** [comment]
If you set the taskbar to the top edge is it the right color?

**Comment by dremin** [comment]
I believe this is resolved. Closing due to no response.
