### ISSUE TITLE
Add support for XP .msstyles

### ISSUE THREAD

**Issue by TorutheRedFox** [dremin/RetroBar#61]
This will allow people to use any XP theme.

**Comment by IoIxD** [comment]
I want to second this because in my Windows 10 VM I have it themed around the Windows XP Zune theme, which is basically Windows XP Dark mode, and being able to have a more accurate task bar would be wonderful.

**Comment by IoIxD** [comment]
...in fact, I might even be able to just make my own Zune theme and add it as a pull request

**Comment by FoxbitDreamtail** [comment]
I just want an xpdark or silver theme in win10..... when 11's out I'm ditching windows anyhow.... so why not make my last month enjoyable?

**Comment by ThaBluNate** [comment]
Are you seriously asking for retrobar to support of a proprietary file extension.., on only one of the many taskbar styles?
...Seriously?

**Comment by xoascf** [comment]
For now you can use [Simple Classic Theme Taskbar](https://github.com/WinClassic/SimpleClassicTheme.Taskbar) to load .msstyles files.

**Comment by IoIxD** [comment]
> Are you seriously asking for retrobar to support of a proprietary file extension.., on only one of the many taskbar styles?

Yes because I was under the presumption that this was a more widespread format, that people had made more themes under it, and then this would be easier then manually adding them. However, msstyles is not as well documented I thought it'd be [(although somebody RE'd the format enough to make an editor for it.)](https://github.com/nptr/msstyleEditor) and apparently every theme made under this format was ported to the program anyways.

**Comment by xoascf** [comment]
@IoIxD, if you are referring to modern (post XP) .msstyles files, you can use [StartIsBack](https://www.startisback.com/)/[StartAllBack](https://www.startallback.com/), as it has its own implementation to apply them to the taskbar.

RetroBar uses XAML for themes, a vector graphics markup language, really different from the raster graphics of .msstyles files, it is preferable to rewrite themes cleanly to this format for use.

**Comment by FoxbitDreamtail** [comment]
Alternatively, you can write a program to convert .msstyles files to .xaml files. That way it can be as simple as drag drop convert drag drop install. I am not particularly well-versed in this but I am pretty sure it is possible because it's just sprites if I'm not mistaken.
