### ISSUE TITLE
custom volume icon is inverted when using the classic theme

### ISSUE THREAD

**Issue by spawncampingnoob** [dremin/RetroBar#613]
after changing windows 10's sound icon in customizergod to the 9x/2000 icon, when using any of the classic taskbars, the icon is always inverted regardless of the light/dark theme being used, due to the way windows 10 inverts that icon for the light theme:
![invertsound](https://github.com/dremin/RetroBar/assets/56559810/5e09d89b-57cf-43dc-9f10-15e6e3491845)

this is fixed if i use a taskbar theme that uses the white icons, such as windows xp's:
![normalsound](https://github.com/dremin/RetroBar/assets/56559810/0462ddd0-ecb2-49ca-801f-e5be33c1a35c)

ideally you'd have an option in the settings to use either light/dark icons for sound/network, to prevent this from being a problem

i know it's not the biggest issue in the world, since the sound/network icons aren't something the average user (myself included) is constantly looking at, but i think it'd be cool to have the option there for people who use custom tray icons :D

**Comment by dremin** [comment]
Have you tried the "System" theme? It will use the classic color scheme you have selected on your system and will not invert the icons.

**Comment by spawncampingnoob** [comment]
never thought to try it, but it works! thanks! :D
![YIPPEE](https://github.com/dremin/RetroBar/assets/56559810/cdb0110b-891d-4d9f-9a19-768a7e943c50)
