### ISSUE TITLE
Open-Shell doesn't work with RetroBar

### ISSUE THREAD

**Issue by MrRussellgro** [dremin/RetroBar#624]
So I have happened to get RetroBar running well on here pretty well. I'm also using Open-Shell to match up with my layout, but isn't working. It only shows the Windows 11 start menu.
Open-Shell's version is 4.4.170, while RetroBar's is 1.12.39+776377be44e.

**Comment by xoascf** [comment]
[You need to update Open-Shell to the latest pre-release](https://github.com/Open-Shell/Open-Shell-Menu/releases) (#583).
