### ISSUE TITLE
Error with Aero themes "The image data generated an overflow during processing"

### ISSUE THREAD

**Issue by PastelGalaxyMochi** [dremin/RetroBar#627]
The error only appears when trying to change to the themes Vista Aero and Vista Basic, every other theme works perfectly. It will still allow you to use the theme, but the start button won't appear. I have currently tried updating the .net version and tried deleting all previous installations of Retrobar, including the AppData folders. So far, nothing has worked.
![image](https://github.com/dremin/RetroBar/assets/89200301/25cf5c6b-280f-40c8-98fd-f3dab7cd0e85)

**Comment by dremin** [comment]
Does it work if you set the taskbar to the top edge? (I have a hunch about what's wrong...)

**Comment by dremin** [comment]
I believe this is resolved. Closing due to no response.
