### ISSUE TITLE
Taskbar Icons Too Bunched Up

### ISSUE THREAD

**Issue by Glennza1962** [dremin/RetroBar#629]
I was using Open Shell on Win10, have now upgraded to Win11 and switched to Retrobar.

Much easier to set up (using Zune XP theme) but the icons on the RH side (clock etc) are too bunched up and have a blurry quality to them. Can this be fixed? Thanks!

**Comment by Braxusz** [comment]
That is how they looked back in the day! Standing room only :)

Maybe try changing your taskbar zoom settings?  Looks very legible on my system with the same color scheme.

**Comment by Glennza1962** [comment]
Doing a side by side comparison, there isn't really a difference. Maybe it's the wider spacing that makes them seem sharper (hint, hint ).

![OpenShell](https://github.com/dremin/RetroBar/assets/78886086/14fe5353-c583-4bfd-acc4-22fe2acbeff7)
![Retrobar](https://github.com/dremin/RetroBar/assets/78886086/76e98c71-bc53-460c-b9f1-f2e36360036c)

**Comment by Braxusz** [comment]
Possibly. To me, massive spacing would break the immersion of having a legacy taskbar.

**Comment by Glennza1962** [comment]
That's a fair point. 
Would it be possible to have adjustable spacing? after all, you have made the taskbar scaleable and that's not legacy! :)
The OpenShell spacing is much too wide; just a slight widening would be perfect.

Overall, Retrobar looks nicer and works straight out of the box. Openshell requires a lot of effort to get a similar look - and doesn't quite achieve it.

Anyway, great job. Much appreciated!

(and I've reverted to Win10. The WIDE taskbar in 11 was causing other problems)

**Comment by dremin** [comment]
@Glennza1962 The notification area icon spacing is more of a property of the individual theme than RetroBar itself. You could customize a theme to increase the spacing.

**Comment by Glennza1962** [comment]
I'm giving it a go! Not a "software person" :) Tried XAML Studio but get this error

![Screenshot (4)](https://github.com/dremin/RetroBar/assets/78886086/f8b78eb3-c080-43fa-9813-26287a01fdec)

Tried Kaxaml get "Data at the root level is invalid. 
Am I using the wrong editor?

**Comment by ibillingsley** [comment]
The easiest way is to extend an existing theme with only the necessary changes using a text editor.

1. Create a folder called "Themes" in `%LOCALAPPDATA%/RetroBar`
2. Create a new text file in that folder called e.g. `Windows XP Zune Custom.xaml`
3. Open it in notepad and paste the following:
```xml
<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                    xmlns:system="clr-namespace:System;assembly=mscorlib">

    <ResourceDictionary.MergedDictionaries>
        <ResourceDictionary Source="pack://siteoforigin:,,,/Themes/Windows XP Zune Style.xaml" />
    </ResourceDictionary.MergedDictionaries>

    <Style TargetType="Image"
           x:Key="NotifyIcon"
           BasedOn="{StaticResource NotifyIcon}">
        <Setter Property="Margin"
                Value="4,2,4,2" />
        <Style.Triggers>
            <DataTrigger Binding="{Binding Path=Orientation, RelativeSource={RelativeSource Mode=FindAncestor, AncestorType={x:Type Window}}}"
                         Value="Vertical">
                <DataTrigger.Setters>
                    <Setter Property="Margin"
                            Value="4,2,4,4" />
                </DataTrigger.Setters>
            </DataTrigger>
        </Style.Triggers>
    </Style>

</ResourceDictionary>
```
I've increased the tray icon margin values already here, but you can tweak them if you like.
The order of the value is `left,top,right,bottom` in pixels. The first set is for horizontal taskbar, second is vertical.

**Comment by Glennza1962** [comment]
Thank you, that's perfect
