### ISSUE TITLE
Retrobar doesnt work with open shell anymore

### ISSUE THREAD

**Issue by DeceasedBrainYT** [dremin/RetroBar#634]
Retrobar doesnt work with open shell anymore for some reason. I'm using windows 11

**Comment by DeceasedBrainYT** [comment]
and Im using the latest openshell version

**Comment by DeceasedBrainYT** [comment]
I reinstalled open shell and it worked

**Comment by aughhhisCN** [comment]
I like your software very much. I hope you will keep it up! Looking forward to your new theme! ヽ(￣▽￣)ﾉ  [cid:30411800-672e-4192-9493-44c38a374b1e]

________________________________
发件人: DeceasedBrainYT ***@***.***>
发送时间: 2023年7月19日 0:05
收件人: dremin/RetroBar ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [dremin/RetroBar] Retrobar doesnt work with open shell anymore (Issue #634)


Closed #634<https://github.com/dremin/RetroBar/issues/634> as not planned.
