### ISSUE TITLE
annoying bar that shows a part of my wallpaper at the bottom of the screen.

### ISSUE THREAD

**Issue by sewp** [dremin/RetroBar#635]
here is a screenshot
![Näyttökuva 12214sggs gr q3tq2023-07-22 132114](https://github.com/dremin/RetroBar/assets/137066190/570408eb-84be-4a7b-9727-8b76d10104f5)

**Comment by sewp** [comment]
btw i use wallpaper engine

**Comment by dremin** [comment]
Recent updates have impacted RetroBar's ability to hide the default Windows taskbar. Before starting RetroBar, it is recommended to open Windows Settings > Personalization > Taskbar, select "Taskbar behaviors", then enable "Automatically hide the taskbar."

**Comment by dremin** [comment]
Closing as the issue is fixed by the above comment.
