### ISSUE TITLE
taskbar border issue?

### ISSUE THREAD

**Issue by TheDolphinSlayer** [dremin/RetroBar#645]
not sure how to describe this, but when windows are maximzed, they arent touching the taskbar..

The only solution i found is explorerpatcher and switching to the windows 10 taskbar

but that conflicts with windhawk so I can't.....
![image](https://github.com/dremin/RetroBar/assets/73983610/ee9281a2-2ecc-4707-a86d-b9db831a8b1e)

**Comment by dremin** [comment]
Before starting RetroBar, did you try opening Windows Settings > Personalization > Taskbar, select "Taskbar behaviors", then enable "Automatically hide the taskbar"? If not, exit RetroBar, give that a try, and see if it helps.

**Comment by TheDolphinSlayer** [comment]
Wow I feel so stupid, so simple in hindsight. Thank you!
