### ISSUE TITLE
Explorer.exe (continously) Restarting (Windows 11)

### ISSUE THREAD

**Issue by p1ckaxe** [dremin/RetroBar#648]
I've had this issue for more than two months now. If I restart explorer after running Retrobar, Explorer.exe gets stuck in a never-ending restart-loop. I thought it was a issue with the Auto-Hiding taskbar, but it was not.

I've also tried to install older versions of Retrobar that I knew worked without Explorer Restarting, but that didn't fix it either.

OS: Windows 11 22H2 (July 26, 2023 Update), 64 Bit

**Comment by p1ckaxe** [comment]
I apologize if I provided too little information, this is my first ever report on any Repo.

**Comment by dremin** [comment]
Closing as duplicate of #457 (which will be fixed in the next version).
