### ISSUE TITLE
[feature request... kinda] sound button working correctly in win11

### ISSUE THREAD

**Issue by monkeyman4412** [dremin/RetroBar#65]
so, usually sound and wireless do not display in retrobar (from my testing) unless in the registry, you manually change the taskbar size (since it's not available in windows 11 to resize it. Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced TaskbarSi 32 dword value:0)
Once that happens it is displayed in retrobar. Apparently windows 10 sound menu still exists in windows 11 somewhere and it does work, just very inconsistently if not, barely at all. I got it to work once, be cool if it could be more consistent. (the menu just doesn't like to pop up when clicking on it from retrobar)

**Comment by monkeyman4412** [comment]
actually found a way to make it consistent. Restarting explorer fixes the problem

**Comment by Alvyssy** [comment]
Hey, I downloaded retrobar 1.5 for dual monitor support and I was having difficulties opening the old volume mixer, I had to restart explorer to make the context menu appear, the problem with that is the windows don't resize properly with the taskbar and in the second monitor the taskbar gets hidden if you put an app in full screen but not f11 full screen just regular full screen with the button at the top right (eg. chrome)

**Comment by dremin** [comment]
> Hey, I downloaded retrobar 1.5 for dual monitor support and I was having difficulties opening the old volume mixer, I had to restart explorer to make the context menu appear, the problem with that is the windows don't resize properly with the taskbar and in the second monitor the taskbar gets hidden if you put an app in full screen but not f11 full screen just regular full screen with the button at the top right (eg. chrome)

This issue is expected if Explorer is restarted while RetroBar is running. You should be able to restart RetroBar for things to work correctly again.
