### ISSUE TITLE
Hot key Win+1/2/3 does nothing

### ISSUE THREAD

**Issue by ssssssbbb** [dremin/RetroBar#651]
As the title mentioned, can't switch between applications by hotkey.

BTW, would you please add the funtion of changing fonts ?

**Comment by 111ebobo** [comment]
Because they are just shortcuts in the folder so they can't be opened by shortcut, regular windows taskbar (starting from Windows 7 maybe) work a bit differently

**Comment by dremin** [comment]
Duplicate of #70

**Comment by xoascf** [comment]
The latest update includes this feature. By default it is disabled, so you need to change the default behavior in **RetroBar Properties** > **Advanced** tab, then you can use Win+number hotkeys.
