### ISSUE TITLE
RetroBar detected as a Virus Attacker on Windows 10

### ISSUE THREAD

**Issue by ftk789** [dremin/RetroBar#653]
![image](https://github.com/dremin/RetroBar/assets/57598907/27df20fb-91a7-4023-acc9-0b0dced65a0b)

![image](https://github.com/dremin/RetroBar/assets/57598907/a080f8fe-cc50-4d77-9054-c7bc84c1a471)

**Comment by ftk789** [comment]
This either is true, Or probably a false trigger, But in any case good to be investigated and get fixed for future users to trust.

**Comment by yereverluvinunclebert** [comment]
No need. You can inspect the code at your leisure and others can too. 

You should know by now that any bit of software that emulates system style activity or performs system level functions will be of increased likelihood for triggering any number of a/v tools. New releases of binaries also increase the levels of suspicion as they are completely unknown to the a/v tools. If you are truly suspicious yourself then the best advice is not to run the program until you have allayed your own suspicions. 

Download the virustotal plugin and always use virustotal to inspect any binary or installer for known malware activity. Some a/v providers may raise suspicions and others not, make your judgement after inspecting the results. This should be standard behaviour for any unknown binary you want to run.

Afterwards raise the false positives with your own malware provider.

**Comment by xoascf** [comment]
The RetroBar executable should not be there, did you download it from the [releases page](https://github.com/dremin/RetroBar/releases)?

**Comment by xoascf** [comment]
That .exe seems not to be RetroBar, check the [VirusTotal analysis](https://www.virustotal.com/gui/file/a0149078ba808d799454e357b9a4f5cd02dd112a06fb0ee20a0dd15644bb0ce4/detection):
![image](https://github.com/dremin/RetroBar/assets/28744392/3f1b8dd0-8f8e-4f9d-87d4-dcb5a0ac55fb)


https://www.virustotal.com/gui/file/a0149078ba808d799454e357b9a4f5cd02dd112a06fb0ee20a0dd15644bb0ce4/behavior
![image](https://github.com/dremin/RetroBar/assets/28744392/c8191148-1165-44c5-88f6-02cca6c3a594)

**Comment by ftk789** [comment]
> The RetroBar executable should not be there, did you download it from the [releases page](https://github.com/dremin/RetroBar/releases)?

Yes, I downloaded it from here, But I put it in startup cuz I want it to start with the system. 






> No need. You can inspect the code at your leisure and others can too.
> 
> You should know by now that any bit of software that emulates system style activity or performs system level functions will be of increased likelihood for triggering any number of a/v tools. New releases of binaries also increase the levels of suspicion as they are completely unknown to the a/v tools. If you are truly suspicious yourself then the best advice is not to run the program until you have allayed your own suspicions.
> 
> Download the virustotal plugin and always use virustotal to inspect any binary or installer for known malware activity. Some a/v providers may raise suspicions and others not, make your judgement after inspecting the results. This should be standard behaviour for any unknown binary you want to run.
> 
> Afterwards raise the false positives with your own malware provider.

You are 100% right, In any case I love this program and idc really, It was soo random it triggered out of nowhere, But I trust it, But since it's false trigger and nothing serious, I'll close this issue. Thank you both for replying to me <3

> That .exe seems not to be RetroBar, check the [VirusTotal analysis](https://www.virustotal.com/gui/file/a0149078ba808d799454e357b9a4f5cd02dd112a06fb0ee20a0dd15644bb0ce4/detection): ![image](https://user-images.githubusercontent.com/28744392/259601381-3f1b8dd0-8f8e-4f9d-87d4-dcb5a0ac55fb.png)
> 
> https://www.virustotal.com/gui/file/a0149078ba808d799454e357b9a4f5cd02dd112a06fb0ee20a0dd15644bb0ce4/behavior ![image](https://user-images.githubusercontent.com/28744392/259601024-c8191148-1165-44c5-88f6-02cca6c3a594.png)

It is 100% the same file from release page, The latest as well, It gives me 1 stealer trigger and 1 malware trigger on VirusTool, fake triggers for sure.

**Comment by xoascf** [comment]
> It is 100% the same file from release page, The latest as well, It gives me 1 stealer trigger and 1 malware trigger on VirusTool, fake triggers for sure.

As I said, the [VirusTotal analysis](https://www.virustotal.com/gui/file/a0149078ba808d799454e357b9a4f5cd02dd112a06fb0ee20a0dd15644bb0ce4/detection) does not show any triggers, and it is impossible for the same executable to have two completely different results on the same page (you can check this by comparing the "Behavior Tags" and the hashes), I advise you to check if you have any trojans or worms on your device that could have modified the executable after downloading it.

Your image:
![yours](https://user-images.githubusercontent.com/57598907/259490989-a080f8fe-cc50-4d77-9054-c7bc84c1a471.png)

Real result:
![real](https://user-images.githubusercontent.com/28744392/259601024-c8191148-1165-44c5-88f6-02cca6c3a594.png)

**Comment by ftk789** [comment]
Ok, I think the issue here on the Virus Tool Page was that, I was dragging the executable of RetroBar directly from WinRAR instead of unzipping it then dragging, Now it shows no triggers, But still weird that it gave me a false error, Could be Windows Defender trying it's best to not let any program to access system 32's DLL's or something, In any case, It's ok now, Turns out it was my fault and I'm sorry for that. I'm going to close this issue, I'm sorry for this. Thank you for an amazing project like this.
