### ISSUE TITLE
System.Windows.Window threw an exception

### ISSUE THREAD

**Issue by Ilexcitly** [dremin/RetroBar#656]
![image](https://github.com/dremin/RetroBar/assets/95829101/2617e627-5188-49a1-a8b0-018e6a727114)

**Comment by Ilexcitly** [comment]
the taskbar also doesnt show up  but fixes when restart

**Comment by dremin** [comment]
Is this still happening at all after the restart?

**Comment by dremin** [comment]
Closing due to no response.
