### ISSUE TITLE
WoA Support

### ISSUE THREAD

**Issue by FoxbitDreamtail** [dremin/RetroBar#66]
This software Does NOT support WoA and by extension, WoR(Windows on Raspberry).... please make a version that IS Windows on Arm capable....

**Comment by dremin** [comment]
I have an ARM machine coming so I should be able to start looking at this soon. I didn't want to release something I couldn't thoroughly vet :)

**Comment by FoxbitDreamtail** [comment]
good, I am I was asking initially because if I am forced to use Microsoft Windows 11 on my Raspberry Pi, I at least want the Windows XP taskbar.

**Comment by dremin** [comment]
This has been released!
