### ISSUE TITLE
MacOS

### ISSUE THREAD

**Issue by InsightfulFuture** [dremin/RetroBar#660]
Please add a macos theme! The dock looks nice!
![50876-100446-dock-xl](https://github.com/dremin/RetroBar/assets/109481728/4e6cbc36-b0c5-4c8d-b7d1-cf5d5c14ed24)

**Comment by 111ebobo** [comment]
Retrobar is a recreation of old windows taskbar so there won't be a Mac OS dock

**Comment by dremin** [comment]
RetroBar will not do this; there are existing dock programs that already do it well.
