### ISSUE TITLE
Missing the show seconds setting.

### ISSUE THREAD

**Issue by dziugas1959** [dremin/RetroBar#671]
This is fairly explanatory, as this was possible with all „Windows Versions“ from XP to 11 (Not sure about 9x though).
Though the methods were different (Mainly with „Windows 8/8.1/10“ having a registry key), while with „XP/Vista/7“ you could edit time config.
A simple toggle in the settings is plenty.

**Comment by xoascf** [comment]
There are at least three ways to make RetroBar show seconds in the clock.

### **By creating/modifying/referencing a specific theme (recommended method)**
You can create a theme that references an existing one if you do not want to modify it directly, this way when you update RetroBar the change will be preserved.

In this example, we will use the "Windows XP Blue" theme and create another one that references it, this new file will have a different name, also with the extension .xaml in the RetroBar themes directory (you will have to create a folder called "Themes" in `%LOCALAPPDATA%/RetroBar`).
```xml
<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                    xmlns:system="clr-namespace:System;assembly=mscorlib">

    <ResourceDictionary.MergedDictionaries>
        <ResourceDictionary Source="pack://siteoforigin:,,,/Themes/Windows XP Blue.xaml" />
    </ResourceDictionary.MergedDictionaries>

    <ControlTemplate TargetType="{x:Type UserControl}"
                     x:Key="ClockTemplateKey">
        <StackPanel Orientation="Vertical">
            <TextBlock Text="{Binding Path=Now, StringFormat=h:mm:ss tt, Mode=OneWay}"
                       Style="{DynamicResource Clock}"
                       Name="ClockText">
            </TextBlock>
            <TextBlock Text="{Binding Path=Now, StringFormat=dddd, Mode=OneWay}"
                       Style="{DynamicResource Clock}"
                       Margin="0,0,0,6"
                       Name="ClockVerticalDayOfWeek"
                       Visibility="Collapsed">
            </TextBlock>
            <TextBlock Text="{Binding Path=Now, StringFormat=d, Mode=OneWay}"
                       Style="{DynamicResource Clock}"
                       Margin="0,0,0,3"
                       Name="ClockVerticalDate"
                       Visibility="Collapsed">
            </TextBlock>
        </StackPanel>
        <ControlTemplate.Triggers>
            <DataTrigger Binding="{Binding Path=Orientation, RelativeSource={RelativeSource Mode=FindAncestor, AncestorType={x:Type Window}}}"
                         Value="Vertical">
                <DataTrigger.Setters>
                    <Setter TargetName="ClockVerticalDayOfWeek"
                            Property="Visibility"
                            Value="Visible" />
                    <Setter TargetName="ClockVerticalDate"
                            Property="Visibility"
                            Value="Visible" />
                </DataTrigger.Setters>
            </DataTrigger>
        </ControlTemplate.Triggers>
    </ControlTemplate>
</ResourceDictionary>
```
_Notice the change made to `StringFormat`, it includes "ss" which determines the seconds, if your "Long time" format already has seconds included, you can simply use "T"._
Then just reopen the RetroBar Properties window and select the theme with your changes.

### **Editing the clock format with Registry Editor**

1. Open Registry Editor (or run `regedit`)
3. Go to the following key: `HKEY_CURRENT_USER\Control Panel\International`
4. Change the value of the string  `sShortTime` to your custom date and time format (you can add "ss" at the end for seconds)
5. Reopen RetroBar

### **Editing the clock format with Control Panel**

1. Open Region in Control Panel (or run `intl.cpl`)
2. Click on "Additional settings..."
3. Change the view to the "Time" tab
4. Change the "Short time" format to your liking
6. Click "Apply" and the changes will be applied

Please note that these last two methods change the format of the clock throughout your operating system and may appear in many other applications, so they are not recommended.
