### ISSUE TITLE
Windows 11 22H2: Left Clicking on system tray icons doesn't seem to open!

### ISSUE THREAD

**Issue by RedDragonTix** [dremin/RetroBar#673]
It doesn't open Volume or Network flyout menu on Retrobar, right clicking does work and I can at least open Volume Mixer

when I close the retrobar and open those on normal taskbar, they do appear, but not on retrobar!

**Comment by dremin** [comment]
Does it work when you press WinKey+A on your keyboard?

**Comment by RedDragonTix** [comment]
> 
No it doesn't, it makes the sound and it doesn't open

**Comment by dremin** [comment]
> No it doesn't, it makes the sound and it doesn't open

That's odd--does the same key combination work when RetroBar is not running?

**Comment by RedDragonTix** [comment]
> > No it doesn't, it makes the sound and it doesn't open
> 
> That's odd--does the same key combination work when RetroBar is not running?

nope

**Comment by TommyHeavenLy6** [comment]
Same as me, I can't right click to the sound icon too, but I can right click to the network icon tho.

**Comment by dremin** [comment]
> > > No it doesn't, it makes the sound and it doesn't open
> > 
> > 
> > That's odd--does the same key combination work when RetroBar is not running?
> 
> nope

That is the default Windows key command for opening the control center. By chance have you changed any settings or made modifications which might have affected this?

**Comment by dremin** [comment]
Thanks for the update @RedDragonTix! I think I have also fixed this from the RetroBar side now too.
