### ISSUE TITLE
Weird bar on top of the XP taskbar

### ISSUE THREAD

**Issue by DrBrad22** [dremin/RetroBar#685]
When using any XP theme, this weird bar thingy that I call a "tumor" appears above the taskbar. This tumor is really annoying and I hope it can get fixed. Thanks!
![image](https://github.com/dremin/RetroBar/assets/136956759/3d2ed086-2eca-4bc0-9dab-633736d26961)

**Comment by jonm58** [comment]
> 当使用任何 XP 主题时，任务栏上方会出现一个我称之为“肿瘤”的奇怪的栏状东西。 这个肿瘤真的很烦人，我希望它能被治愈。 谢谢！ ![图像](https://user-images.githubusercontent.com/136956759/267490994-3d2ed086-2eca-4bc0-9dab-633736d26961.png)

Please,"Lock the TaskBar"
