### ISSUE TITLE
Task View Support

### ISSUE THREAD

**Issue by jribs** [dremin/RetroBar#688]
RetroBar is great so thank you for supporting us.

I see we have multiple monitor support. However, when attempting to use multiple desktops (Win + Tab), Retrobar maintains the total number windows open throughout all desktops.

Is it feasible to:
- Have a Task View option
- Support showing windows which are only represented when switching to that desktop

Thanks again for all your hard work

**Comment by TheSystemGuy1337** [comment]
Use WIN+TAB instead.

**Comment by RoPezGon561** [comment]
> Use WIN+TAB instead.

This does not provide the feature to only see windows specific to separate desktops. I'd like that feature too, only thing preventing me from using RetroBar.

**Comment by dremin** [comment]
Closing as duplicate of #131, which I have a fix coming for.
