### ISSUE TITLE
XP Blue Theme: Extended bar when unlocked, missing taskbar seperator bezels when locked

### ISSUE THREAD

**Issue by DynamicOsi** [dremin/RetroBar#689]
The Windows XP Blue Theme has an issue where the bar is extended vertically in the lastest version.
![unlocked](https://github.com/dremin/RetroBar/assets/94809883/e38a73f4-cda4-4a3c-afda-d21f5c10e7ff)

I found that a solution to this issue is by locking the taskbar. 
However, this removes the bezels that seperate the start button, quick launch, and applications tabs:
![locked](https://github.com/dremin/RetroBar/assets/94809883/09cbdfd3-a17e-44d4-822c-1fd811d9b89e)

I'm using Windows 10 19044

**Comment by Krunchy0920** [comment]
That isn't an issue, the taskbar on real Windows XP does the same thing when the Taskbar is unlocked. 

![image](https://github.com/dremin/RetroBar/assets/81315028/76160613-1ee7-4616-a99e-0793e2ac6b4e)
