### ISSUE TITLE
how do i uninstall retrobar (or revert back to original windows 10 taskbar)

### ISSUE THREAD

**Issue by 0Midnite** [dremin/RetroBar#692]
i tried to check the uninstall menu in control panel and didn't see retrobar there. when i close the program there are still icons left unchanged
![image](https://github.com/dremin/RetroBar/assets/104600774/4f7d33bc-ec71-421f-b282-a105b50d720f)
![image](https://github.com/dremin/RetroBar/assets/104600774/66766ecb-adac-486f-a2b8-3e20f10bd8cc)

**Comment by 0Midnite** [comment]
nevermind i found out how

**Comment by Cardioman1** [comment]
How did you manage to uninstall it?

**Comment by Cardioman1** [comment]
alright thanks
