### ISSUE TITLE
Windows XP themes look a little off visually

### ISSUE THREAD

**Issue by TheDwellerInDarkness** [dremin/RetroBar#695]
Before the latest version, the themes looked relatively normal, but now they have a line going on top that wasn't there before. Restarting RetroBar or changing the scaling doesn't seem to fix it if it's an error on my side, so I figured I'd bring it up. Is this normal for the new version?
![2023 10 08-19 05](https://github.com/dremin/RetroBar/assets/92492329/62ba3447-a1db-43b3-a868-dfca0d6464e6)

**Comment by dremin** [comment]
Right-click and choose "lock the taskbar."

**Comment by TheDwellerInDarkness** [comment]
> Right-click and choose "lock the taskbar."

That fixed it, thank you!
