### ISSUE TITLE
Gap between fullscreen windows and taskbar

### ISSUE THREAD

**Issue by csrealism** [dremin/RetroBar#696]
Hi, I recently downloaded the retrobar application and when I have fullscreen windows eg. web browsers, settings there seems to be a gap between the retrobar and bottom of the window. 
![image](https://github.com/dremin/RetroBar/assets/147363720/bf003119-04c9-4b89-9043-8d23afcb0952)
I am currently using windows 11 and would like to ask whether there are any fixes to the issue?

**Comment by Pipole26** [comment]
Same for me. Windows 11.

Anyone got a fix for this?

**Comment by dremin** [comment]
Before starting RetroBar, did you try opening Windows Settings > Personalization > Taskbar, select "Taskbar behaviors", then enable "Automatically hide the taskbar"? If not, exit RetroBar, give that a try, and see if it helps.

**Comment by kfmush** [comment]
Also on Win 11.  Setting the taskbar to auto-hide in Windows personalization settings did the trick for me.  Thank you!

**Comment by dremin** [comment]
Issue is fixed by the above comment.
