### ISSUE TITLE
Booted Computer w/ Retrobar And Got An Error

### ISSUE THREAD

**Issue by SuperKirbylover** [dremin/RetroBar#699]
just in case it's important:
OS: Windows 10 Home, Build 19041
Retrobar Theme: System XP
included the theme because i've never used it before until yesterday. maybe that's important who knows

and the error:

![image](https://github.com/dremin/RetroBar/assets/37816816/ef48169f-d0a8-45cb-a120-8c61224a866e)

**Comment by dremin** [comment]
Thanks! I believe I have a fix for this.
