### ISSUE TITLE
Themes folder doesn't work

### ISSUE THREAD

**Issue by FurryFan2003** [dremin/RetroBar#7]
Themes that have been copied to the Themes folder do not appear in the drop down menu

**Comment by dremin** [comment]
Oops. I believe I have fixed this, could you please try [this build](https://github.com/dremin/RetroBar/suites/1965541793/artifacts/39010579)?

**Comment by dremin** [comment]
Darn, it's definitely still broken in the build from CI...

**Comment by dremin** [comment]
Alright, it's definitely fixed now.
