### ISSUE TITLE
Bar overtop the taskbar

### ISSUE THREAD

**Issue by Jett-Secret** [dremin/RetroBar#704]
Updated to current (1.14.21+68aa7edb4f) and now there's this odd top border that doesn't look quite correct and wasn't there before.
![rbar](https://github.com/dremin/RetroBar/assets/95106441/7848d75a-455b-48fd-8c1d-c406d7c6c80c)

Not sure if this was intended... I also built it from source with the anycpu configuration and have the same issue. Windows 11 Version 21H2 Build 22000.978 (x64 obviously).  Locking the taskbar removes this for some reason which makes it a fine workaround but still notable as an issue if not intended

**Comment by xoascf** [comment]
That is the sizing bar, it is intended to be displayed on the outer side of the taskbar, as it was a way to show that it is not locked in the official Windows XP Luna themes. Locking the taskbar is the way to make it not show.

**Comment by Jett-Secret** [comment]
oop.  I didn't realize that was ever a thing...  Thanks!
