### ISSUE TITLE
Some windows don't adjust to Retrobar's size.

### ISSUE THREAD

**Issue by skelereal** [dremin/RetroBar#71]
Exactly what the title says. Some of my running windows don't resize or adjust to Retrobar's size even if I close and reopen the window.

Apps that don't adjust:
Brave Browser
Discord

**Comment by Splitwirez** [comment]
@skelereal When you say they "don't resize or adjust to Retrobar's size", are you referring to the area occupied by these programs' windows when *maximized*? And also, what version of Windows are you using?

**Comment by Rytor420** [comment]
I had the same problem.

**Comment by Rytor420** [comment]
I ran this on Windows 10

**Comment by JaidenIsDumb** [comment]
same problem lol

**Comment by dremin** [comment]
After some testing of a fix for #53, marking this as duplicate.
