### ISSUE TITLE
System Vista

### ISSUE THREAD

**Issue by FlorianisonGitHub** [dremin/RetroBar#718]
Since you did System and System XP themes for RetroBar can you please for System Vista please? It would be appreciated.

**Comment by inkballpro** [comment]
A Windows Vista theme for aero, basic and classic already exist.
![image](https://github.com/dremin/RetroBar/assets/104173450/baf6035e-a8ad-403a-b8bb-d1cf754cae36)

**Comment by inkballpro** [comment]
You can take the vista start button (https://github.com/dremin/RetroBar/blob/master/RetroBar/Resources/startvistaclassic.png) and the System XP theme (https://github.com/dremin/RetroBar/blob/master/RetroBar/Themes/System%20XP.xaml) and point it to the vista start image instead

**Comment by dremin** [comment]
This is now available in the latest release.
