### ISSUE TITLE
Possible to change start button color?

### ISSUE THREAD

**Issue by aegiswing** [dremin/RetroBar#719]
Hi, I'm trying to make an accurate royale noir theme with this on Windows 11, but on Royale Noir the start button was orange. Can I change it from dark to orange?
RetroBar
![image](https://github.com/dremin/RetroBar/assets/70413628/431dce5d-46b4-4d13-bcc7-4e6ecf41de5b)
Original XP
![image](https://github.com/dremin/RetroBar/assets/70413628/70f03290-bf10-45e5-8a23-858d43291a67)

**Comment by 111ebobo** [comment]
Maybe you used the zune theme

**Comment by aegiswing** [comment]
Thank you SO MUCH. I didn't even think to look through the options, but this is the exact one I used.
