### ISSUE TITLE
[Feature request] Drag adjust Quick Launch area and taskbar height

### ISSUE THREAD

**Issue by CPS2Evolved** [dremin/RetroBar#721]
Is it possible add functionality to make dragging the sections of the taskbar possible and also to adjust height?

![retrobar2](https://github.com/dremin/RetroBar/assets/78268472/1c63fddb-3345-470f-9934-2bc6936b7fb2)

**Comment by dremin** [comment]
Closing as duplicate of #14 (fixed in the next release) and #377.
