### ISSUE TITLE
RetroBar crashing on latest Windows 11 Pro update

### ISSUE THREAD

**Issue by dogboyxo** [dremin/RetroBar#722]
hey so recently RetroBar started crashing a few seconds after Explorer.exe starts running. tried booting into Safe Mode and it works fine, so i don't really know what the problem is. can anyone help?
OS: 11 Pro 22H2

**Comment by dremin** [comment]
Do you receive any error message from RetroBar?

**Comment by dremin** [comment]
Closing due to no response.
