### ISSUE TITLE
Problem with upscaling

### ISSUE THREAD

**Issue by Nxkorasu** [dremin/RetroBar#735]
Using certain Upscaling Measures (tested 125% and 140%) while using Auto Hide makes it so if your cursor is located in the bottom of the screen the taskbar wont pop up

**Comment by dremin** [comment]
Which theme are you experiencing this issue with?

**Comment by Nxkorasu** [comment]
Sorry for the late reply, it seems to not be specific to a theme, and it looks like the bar missplaces itself

**Comment by Nxkorasu** [comment]
P.D.: Seems like i found the issue, aparently screen resize (which my laptop had 125% as reccomended by the system) messes with retrobar´s "hitbox" while using the Auto Hide feature

**Comment by dremin** [comment]
I believe I have fixed this issue. Could you please [test this build (64-bit)](https://github.com/dremin/RetroBar/actions/runs/8902395619/artifacts/1462302094) and check if it is resolved for you?

**Comment by Nxkorasu** [comment]
> I believe I have fixed this issue. Could you please [test this build (64-bit)](https://github.com/dremin/RetroBar/actions/runs/8902395619/artifacts/1462302094) and check if it is resolved for you?

It does fix the issue

**Comment by dremin** [comment]
Great, thanks for confirming! The fix is included in the recent 1.16 release.
