### ISSUE TITLE
Tray Icons not functioning

### ISSUE THREAD

**Issue by 1JustJoey** [dremin/RetroBar#737]
I am using Retrobar with SAB on my Windows 11 host and none of the tray icons worked when clicked, the system ones, wifi, volume, saftely remove hardware, and battery do not work. Please make a fix and maybe add an update section to Retrobar, please fix how it kills explorer every single time and hides the tray icons for forever?
![ezgif-7-77ddb64e38](https://github.com/dremin/RetroBar/assets/111856670/8a99c6a5-423c-4f04-b82c-cbbd2e84fed6)

**Comment by dremin** [comment]
I've seen some issues raised here in the past when running some of the taskbar modifications from SAB. I would recommend disabling the taskbar modifications when using RetroBar so that it can work properly.

**Comment by 1JustJoey** [comment]
@dremin Whenever I do this the opened things are at the normal taskbars height.
![image](https://github.com/dremin/RetroBar/assets/111856670/9ee1dd06-04ae-4714-9b11-1fde2f6981bd)

**Comment by 1JustJoey** [comment]
Whenever I do this it is the full length of the taskbar instead of the retrobar size.
![image](https://github.com/dremin/RetroBar/assets/111856670/7ecb4fce-bbc5-4cad-9213-e38bc6647004)

**Comment by 1JustJoey** [comment]
> I've seen some issues raised here in the past when running some of the taskbar modifications from SAB. I would recommend disabling the taskbar modifications when using RetroBar so that it can work properly.

Is there a way you can code in SAB functionality like if SAB is installed use Retrobar like its the windows 10 tb?

**Comment by xoascf** [comment]
Probably due to the change in https://github.com/cairoshell/ManagedShell/pull/38 that makes it ignore left clicks on certain icons in the notification area and redirect the action to open the Notification Center in Windows 11, this version was used in #108 and since then RetroBar does not work correctly with some StartAllBack tray icon left click actions.

**Comment by dremin** [comment]
Hm, maybe we can send both the click message and the hotkey to support this. I'll do some testing.

**Comment by dremin** [comment]
A few things I've noticed:
- It seems like we can safely send both messages and "the right thing" happens
- The network icon began responding to clicks at some point, which is quite nice, but means we'll need to add another logic branch here.

I'll get this fixed up.

**Comment by 1JustJoey** [comment]
> A few things I've noticed:
> 
> * It seems like we can safely send both messages and "the right thing" happens
> * The network icon began responding to clicks at some point, which is quite nice, but means we'll need to add another logic branch here.
> 
> I'll get this fixed up.

Thank you!

**Comment by xoascf** [comment]
This bug still exists in version 1.15.33, RetroBar still opens the Action Center instead of the StartAllBack flyouts.
