### ISSUE TITLE
Clock freezes when Team Fortress 2 is running in exclusive fullscreen

### ISSUE THREAD

**Issue by TorutheRedFox** [dremin/RetroBar#741]
The clock has the tendency to freeze when TF2 is running on my end

**Comment by TorutheRedFox** [comment]
the taskbar seems to stop refreshing properly overall

**Comment by xoascf** [comment]
Probably related to #188? Try using software acceleration to see if that is the case.

**Comment by TorutheRedFox** [comment]
it seems to work
