### ISSUE TITLE
Win Input Experience

### ISSUE THREAD

**Issue by R-D-R248** [dremin/RetroBar#745]
![image](https://github.com/dremin/RetroBar/assets/140945791/cd83540b-984e-4b5c-aa4d-ae5282824fe0)
### It shows random Windows And If i close input experience it duplicate

**Comment by R-D-R248** [comment]
Pls Help

**Comment by adamek0202** [comment]
It is probably some Windows component that is ment to be hidden from user, but the taskbar thinks it is a normal program, so it show it. The only fix i think about is implementing some code to hide it, or you can just somehow ignore it.

**Comment by R-D-R248** [comment]
how do i do that

**Comment by R-D-R248** [comment]
![image](https://github.com/dremin/RetroBar/assets/140945791/14769afc-859f-41eb-a88f-c8fec09817c7)
Also, When i click chrome **Game Bar** come out of Nowhere.

**Comment by R-D-R248** [comment]
Now this scr... which i got from snipping tool.

**Comment by R-D-R248** [comment]
Search and Start when I click Start.

**Comment by R-D-R248** [comment]
> It is probably some Windows component that is ment to be hidden from user, but the taskbar thinks it is a normal program, so it show it. The only fix i think about is implementing some code to hide it, or you can just somehow ignore it.

thanks for responding
