### ISSUE TITLE
weird line over taskbar in XP luna

### ISSUE THREAD

**Issue by PlasticLover69** [dremin/RetroBar#750]
whenever I choose luna XP theme appears this weird thin line over the task bar 
![line](https://github.com/dremin/RetroBar/assets/16528236/7b119b10-42cf-4325-806a-b088a99f5b9f)
this doesnt happen with any other skins/themes from retrobar

**Comment by mapsack** [comment]
that's the unlocked taskbar variant bro. perfectly normal
