### ISSUE TITLE
RetroBar Error 'Culture'

### ISSUE THREAD

**Issue by legacy1477** [dremin/RetroBar#758]
![image](https://github.com/dremin/RetroBar/assets/118707318/baa7a3b8-ae4f-47fc-889b-b36191228568)

OS Info:
![image](https://github.com/dremin/RetroBar/assets/118707318/2b92960b-fdbe-44ca-b22a-76f18742fff6)

I'm currently on the x64 build. This wasn't happening on the previous builds.

**Comment by dremin** [comment]
Does this only happen with the “show input language” option enabled?

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
I have enabled the input language selector and sometimes this error happens to me as well.

**Comment by xoascf** [comment]
@legacy1477, @aeiouaeiouaeiouaeiouaeiouaeiou, could you please try this build?
[RetroBar_1.15.37+misc0.zip](https://github.com/dremin/RetroBar/files/14461978/RetroBar_1.15.37%2Bmisc0.zip)
It shouldn't crash, since it uses a positive number for `culture` in `GetCultureInfo()`.

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
@xoascf I don't know, but it doesn't help.

![image](https://github.com/dremin/RetroBar/assets/69355938/edffdcfe-f407-4e44-9a6b-332107a408eb)

**Comment by exalye** [comment]
often happens to me too for no reason

**Comment by Squiddu** [comment]
This error always happens whenever I open up cmd.exe for the first time. If I ask it not to restart, it doesn't appear again for the rest of the session.

**Comment by Squiddu** [comment]
Can also confirm it only happens with the input language display on.

**Comment by RubberDuck01** [comment]
+1, same here. Attaching a screenshot nonetheless:

![image](https://github.com/dremin/RetroBar/assets/72613604/8ce81fb5-84ba-42db-b068-f82d4b08b51c)
