### ISSUE TITLE
RetroBar crash on opening PowerShell

### ISSUE THREAD

**Issue by FrostedGeulleisia** [dremin/RetroBar#770]
![RetroBar_Sbe7HdBu98](https://github.com/dremin/RetroBar/assets/27410260/02074a6f-0d8b-4f47-a4c5-0f2a54a74993)
Happens consistently on opening PowerShell via Shift+RightClick in directory > "Open PowerShell window here"
using latest x64 on Win10 (build 19045.3448)

**Comment by dremin** [comment]
Duplicate of #758 which will be fixed in the next release.
