### ISSUE TITLE
Taskbar feature suggestion: Add Windows 7 Aero 

### ISSUE THREAD

**Issue by coachjr** [dremin/RetroBar#771]
I love retrobar, but i always wanted a windows 7 taskbar, so that is why im asking if you are able to add it someday. Thank you. PS. It would look nice

**Comment by TheWeirdo600** [comment]
A Windows 7 taskbar is requested so much!

I would also like a Windows 7 taskbar, even if it lacks the Windows 7-exclusive features. The small taskbar from Basic theme would be a good start

**Comment by 111ebobo** [comment]
I don't think that windows 7 fits here because the windows 7 taskbar uses different technology, and you can use startisback to change it

**Comment by teknixstuff** [comment]
> I don't think that windows 7 fits here because the windows 7 taskbar uses different technology, and you can use startisback to change it

On Windows 11, it's hard to get StartAllBack to do it correctly, and it's not free anyway.

**Comment by 111ebobo** [comment]
> > I don't think that windows 7 fits here because the windows 7 taskbar uses different technology, and you can use startisback to change it
> 
> On Windows 11, it's hard to get StartAllBack to do it correctly, and it's not free anyway.

StartAllBack probably is, but Startisback is free, and imo windows 11 isn't that customize friendly

**Comment by teknixstuff** [comment]
> > > I don't think that windows 7 fits here because the windows 7 taskbar uses different technology, and you can use startisback to change it
> > 
> > 
> > On Windows 11, it's hard to get StartAllBack to do it correctly, and it's not free anyway.
> 
> StartAllBack probably is, but Startisback is free, and imo windows 11 isn't that customize friendly

StartIsBack isn't free, just like StartAllBack. They cost $4.99 (keys for one work on both), and StartIsBack has a 30-day free trial, while StartAllBack has a 100-day trial.

**Comment by teknixstuff** [comment]
> Got windows 7 theme with Startisback, closing the issue.

It works, but it's not as accurate as it could be.
