### ISSUE TITLE
Some odd error when opening CMD

### ISSUE THREAD

**Issue by metrochel** [dremin/RetroBar#778]
Any time I open up a cmd window, this error pops up, forcing me to restart RetroBar. 
![image](https://github.com/dremin/RetroBar/assets/158221670/22b60a48-6830-4165-ad95-6fa1fcd27dd3)
Also, clicking "Yes" does not restart RetroBar, it just crashes.
Any idea what may be causing this?

**Comment by dremin** [comment]
This happens with the "Show input language" option enabled. It's a known issue and will be fixed with the next release!

**Comment by dremin** [comment]
Duplicate of #758 which will be fixed in the next release.
