### ISSUE TITLE
Invitation to work hand in hand with Open-Shell :)

### ISSUE THREAD

**Issue by blackcrack** [dremin/RetroBar#78]
I want give you a invitation to Open-Shell for work hand in hand to have a mighty Desksurface for the Users who have the possible for Modding like the User want.

and the german Deskmodder.de has introduced your program and i use since very long time Classic/Open-Shell
https://www.deskmodder.de/blog/2021/09/04/mit-der-retrobar-unter-windows-11-die-taskleiste-ersetzen-und-nicht-gruppiert-darstellen/

so, what's is closer than coordinating a bit together and acting as a "BadPack"
I would like to invite your RetroBargroup to Open-Shell :)
https://github.com/Open-Shell/Open-Shell-Menu

best regards
Blacky

**Comment by nardholio** [comment]
Yes these two products would make great friends

**Comment by dremin** [comment]
RetroBar has support for Open Shell.
