### ISSUE TITLE
Quicklaunch icons not updating

### ISSUE THREAD

**Issue by 2Sloppy4slime** [dremin/RetroBar#780]
Hello, I'm using the vista aero setting and wanted to add spotify to my quicklaunch. So I pinned the icon on my Win11 taskbar before launching retrobar. Issue is the quicklaunch section did not show spotify in it, only my other pinned apps (steam opera and file explorer)

Am I doing it wrong?

**Comment by 111ebobo** [comment]
> Hello, I'm using the vista aero setting and wanted to add spotify to my quicklaunch. So I pinned the icon on my Win11 taskbar before launching retrobar. Issue is the quicklaunch section did not show spotify in it, only my other pinned apps (steam opera and file explorer)
> 
> Am I doing it wrong?

It's probably not syncing with uwp shortcuts so try putting it manually

**Comment by 2Sloppy4slime** [comment]
k I managed to do it, thx

**Comment by 2Sloppy4slime** [comment]
for those having the same problem, drag the icon that you want in there from your desktop to the place where the shortcuts are
