### ISSUE TITLE
Taskbar shows up when you have a 2nd monitor.

### ISSUE THREAD

**Issue by thatmemeguy2** [dremin/RetroBar#784]
![image](https://github.com/dremin/RetroBar/assets/165538124/5e40eca5-a039-41eb-9c41-5313553ed7a1)
Basically whenever I click the taskbar or anywhere on my 2nd monitor while watching a youtube video the taskbar will show up, I've tried without running retrobar and it doesn't do this. Not sure if it's a browser thing.

**Comment by dremin** [comment]
This behavior is intentional.
