### ISSUE TITLE
Add in Readme.md the "System requirements: Windows 7, Windows 8, windows 10, Windows 11"

### ISSUE THREAD

**Issue by blackcrack** [dremin/RetroBar#79]
Hy,

Could be well, if exist in the Readme.md
for have a bit an reference point

__System requirements:__ 
*  min. Net Framework : .NET Core 3.1.
 *  Windows XP (5.1, 5.2)
 *  Windows Vista (6.0)
 *  Windows 7 (6.1)
 *  Windows 8  (6.2, 6.3)
 *  Windows 10 (6.4, 10.0)
 *  Windows 11 (10.0, 11.0)

best

**Comment by samiscoolest** [comment]
it should be able to run on as early as vista sp2 and 7 sp1 but im not 100% sure

**Comment by blackcrack** [comment]
@samiscoolest , blubb.. !
issue, => Adding in the Readme.md !
i have not ask if it's work or not.. 
Reading, understanding then writing !

**Comment by Aokromes** [comment]
@dremin  you forgot to close :)
