### ISSUE TITLE
Bug report: RetroBar throws exception on GetCultureInfo

### ISSUE THREAD

**Issue by samhjn** [dremin/RetroBar#794]
![image](https://github.com/dremin/RetroBar/assets/4426124/a97f24e2-6e79-473e-ad15-5cc72f2c20db)
RetroBar throws exception on GetCultureInfo, probably introduced in 1.15.33, not seen on versions before
And I usually found this exception when I open the lid of my laptop and unlock it, which indicates it may be one of the reason.
I also doubt that my usage of two screens also a key factor of this exception, although there is no evident clues.

**Comment by samhjn** [comment]
find this problem may be the same as #758

**Comment by dremin** [comment]
Duplicate of #758 which will be fixed in the next release.
