### ISSUE TITLE
Badge icons

### ISSUE THREAD

**Issue by xpewster** [dremin/RetroBar#797]
On some apps such as Discord, I have a notification badge that appears over the taskbar icon of the app. I don't see those anymore. Can it be added as a feature? Or am I missing something?

Thanks.

**Comment by dremin** [comment]
Try fully exiting and then restarting Discord after RetroBar is running.

**Comment by xpewster** [comment]
Still nothing. The taskbar flashes properly but I'm talking about the icon on the taskbar getting a little red overlay badge when theres a notification.
![image](https://github.com/dremin/RetroBar/assets/24950321/801ef6e4-ffec-4d9e-ae76-3922608997ec)

**Comment by dremin** [comment]
So I actually thought that RetroBar had this already, turns out it actually doesn't! I'll add support.

**Comment by xpewster** [comment]
Sweet!! I love this program, can't wait for the release
