### ISSUE TITLE
[Request] Add Windows 7 Bar as Retrobar and make compatieble to OpenShell/Windows Start Button

### ISSUE THREAD

**Issue by blackcrack** [dremin/RetroBar#80]
Hi, 

would be nice if Windows7 as Retrobar and configurable like the original Windows
with the same programs like in Win7 if this possible.. to have a compatibility to Open-Shell and 
other Adjusting programs from Win7.

best regards
Blacky

**Comment by CodeRabbid64** [comment]
@dremin please add this next update!

**Comment by DavidXanatos** [comment]
this would be indeed great + multi monitor support

**Comment by blackcrack** [comment]
> 
> I guess Windows 7's superbar is too much to wait for now... maybe somewhere in the future, but not in v1.4
> 
> Windows Vista's taskbar though seems easier to realise, especially if don't add preview functionality to it  

@1280px well, your skills ? just for taking up and why .. just for explain why and because i telling you now something..

**Comment by l0oo** [comment]
Well - just tested OpenShell + RetroBar and it actually works... ;)

**Comment by xoascf** [comment]
> 
> not the custom Startbutton, i have download the actual Release , the custom Startbutton from OpenShell works not ..
> 

That's because they are two completely different programs, although if you are willing to create a communication bridge between these two programs, you are welcome to write it.

**Comment by blackcrack** [comment]
> 
> 
> > not the custom Startbutton, i have download the actual Release , the custom Startbutton from OpenShell works not ..
> 
> That's because they are two completely different programs, although if you are willing to create a communication bridge between these two programs, you are welcome to write it.

nice critique , If I could have, I would have done it a looong time ago... ;) 

no, in ernest.. ehh serious i can not programming, i be in able to scripting in bash/sh and in Win9X via bat/cmd
and have build up my homepage in PHP, i have never found the way to it.. pity, but more f.. it is i have now to lern python, java and other unneeded Bu.Sh. (okey, python is usable.. *bg*) and not c or c++ or so.. but in a couple weeks.. or month ?

so, now you @xoascf (and don't forget, i be more as 25 years in the net already )
i was ever in opinion it must give both, programmers and Users.. and i be a Extended User with hobby in Orderingsystems .. so..
best :)

**Comment by nlogozzo** [comment]
+1

**Comment by dremin** [comment]
Windows 7 theme/feature support is not planned as there are other utilities that provide this, and custom start buttons can be used with RetroBar via themes.

**Comment by dogboyxo** [comment]
push
