### ISSUE TITLE
Start Button oversized and not matching taskbar (Taken care of)

### ISSUE THREAD

**Issue by SD308** [dremin/RetroBar#800]
For the theme of "Windows Vista Aero", the start button is oversized. Changing the taskbar scale keeps the same oversized ratio as any other size. I would also like to have it have a black background, rather than a blue one.

![image_2024-04-16_031843859](https://github.com/dremin/RetroBar/assets/63887188/12b2395a-7773-4e34-bb24-0a17f9d9922a)

to

![image](https://github.com/dremin/RetroBar/assets/63887188/82f8cff4-dd1a-4358-a684-040c1b347d29)

in design.

**Comment by konstidog** [comment]
That's just how it looked in actual Vista though.

**Comment by ChardeX03** [comment]
thats not oversized, thats how windows vista should be try other themes.

**Comment by dremin** [comment]
:)
