### ISSUE TITLE
Minor complaint about aero/vista theme

### ISSUE THREAD

**Issue by bandomy** [dremin/RetroBar#830]
The start button/icon barely clips through the bottom of the screen.
If there's any way to turn up the scale of the taskbar without changing the size of the icon that'd be greatly helpful.
![image](https://github.com/dremin/RetroBar/assets/121991100/8c3619e4-ff52-4e27-9f94-51d30bd7b3d1)

**Comment by InsaneGal** [comment]
That's how the orb was in Vista.

**Comment by jobukkit** [comment]
> That's how the orb was in Vista.

Yes, but Vista did allow you to increase the size of the taskbar so the orb fits in.

![2007 screenshot of Windows Vista from a forum](https://github.com/dremin/RetroBar/assets/2750434/4fbfb801-aac4-4fb0-98f7-541dfec15651)

(This screenshot is from a 2007 forum post)

**Comment by dremin** [comment]
This is fixed by #14 which adds support for rows.
