### ISSUE TITLE
Unfortunately there are scripts embedded to open crypto exchanges

### ISSUE THREAD

**Issue by crwg** [dremin/RetroBar#835]
![134](https://github.com/dremin/RetroBar/assets/13091768/635b1830-b93f-484d-b172-ac98369f098a)

Just look at this 18 scripts attached to chrome, also I noticed when my computer is awaiting more than 30 minutes Chrome opens HTX site

**Comment by xoascf** [comment]
RetroBar does not have any embedded scripts (as they are provided on the [official Releases page](https://github.com/dremin/RetroBar/releases), they are generated by GitHub itself, so there is no reason for the executable to be tampered with), please upload your `RetroBar.exe` file to https://www.virustotal.com so we can analyze it and check if it is a tampered application.
Also try scanning your system for viruses and make sure that no malware has been injected into the program.

**Comment by teknixstuff** [comment]
> ![134](https://private-user-images.githubusercontent.com/13091768/329879292-635b1830-b93f-484d-b172-ac98369f098a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwODg2ODMsIm5iZiI6MTcxOTA4ODM4MywicGF0aCI6Ii8xMzA5MTc2OC8zMjk4NzkyOTItNjM1YjE4MzAtYjkzZi00ODRkLWIxNzItYWM5ODM2OWYwOThhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDIwMzMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzYjc1NjM4YzAxZjAwNDNjMTEyNDAxYzE2MTg2NzZhZmY0ZjNlZjcyNTViYzg5NTc4YWM0N2ViZDIxM2RhYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iWcnaF_5hC9BV52tU8I6nvGCYCs6-Ni2i2SrjDvcsGs)
> 
> Just look at this 18 scripts attached to chrome, also I noticed when my computer is awaiting more than 30 minutes Chrome opens HTX site

That grouping effect is a W11 task manager bug and is incorrect.

**Comment by dremin** [comment]
Closing as this is a Task Manager display issue we can't control.
