### ISSUE TITLE
Retrobar waking pc from hibernation

### ISSUE THREAD

**Issue by PinkamenaVTR** [dremin/RetroBar#841]
Hello! first ever post i ever made on github
Love the program! only a small weird problem, it's waking my pc from hibernation apparently, if i close Retrobar before hibernating, it doesn't wake up by itself.
If you can, please help, thank you!

![retrobarwake](https://github.com/dremin/RetroBar/assets/170089922/d8047c6e-91be-4a6a-a824-f851ffad0a2f)

**Comment by dremin** [comment]
Hello! Does the wake occur immediately or after some time? If it is after some time, does disabling the “check for updates” option help?

**Comment by PinkamenaVTR** [comment]
i will try as soon as i can, thank you!

**Comment by PinkamenaVTR** [comment]
So disabling the "check for updates" option apparently fixed, but I wanted to make sure so i re-enabled it, but this time it didnt wake the pc.
But its not waking the pc anymore, so thats good!
Also thing to note, it would only wake my pc when it had the charger plugged in.
Thank you for the help!
