### ISSUE TITLE
Bar above the actual taskbar

### ISSUE THREAD

**Issue by IvanBondarevus** [dremin/RetroBar#843]
Almost all windows xp skins have a bar on top of the actual taskbar
![изображение](https://github.com/dremin/RetroBar/assets/169177913/6282269a-c822-439a-a748-91dccd834cf8)

Dunno whether its done intentionally or not, on the videos dating two years ago it wasn't there

There are no similar issues, and it is just a visual thing, I just wanted to know whether it's supposed to be like that or not

**Comment by jobukkit** [comment]
The real Windows XP does this too. It indicates that the taskbar is unlocked and gives you more space to drag it with. It disappears if you lock the taskbar.
