### ISSUE TITLE
Question: Quick Launch Bar functionality.

### ISSUE THREAD

**Issue by Noomene** [dremin/RetroBar#847]
Dear Dev,

First off, thank you for this gem!

My question is whether it is possible to use this app to only add the functionality of the quick launch bar without changing the windows 11 or windows 10 theme?

Thank you again for your amazing work.

Cheers,

**Comment by 111ebobo** [comment]
In windows 10 you can add quick launch, or any folder in your taskbar without any additional programs, in windows 11 you can't do this, only with retrobar but you will be forced to have a themed taskbar

**Comment by Noomene** [comment]
For anyone interested,I found an alternative that works with W11, and that is 7Stack.
