### ISSUE TITLE
Bar crash  after open a regular command promp by running windows run

### ISSUE THREAD

**Issue by StarWong** [dremin/RetroBar#849]
![er](https://github.com/dremin/RetroBar/assets/42410196/8940f95e-05fc-49c1-9cd6-ca2fbb1c164a)
Microsoft Windows [Version 10.0.19044.3930]
also i installed the app named Classic Shell  -http://www.classicshell.net/

**Comment by dremin** [comment]
Please update to the [latest release](https://github.com/dremin/RetroBar/releases), it has been fixed.
