### ISSUE TITLE
need help with this err that pops up when starting my PC

### ISSUE THREAD

**Issue by aalexx-z** [dremin/RetroBar#862]
i don't know if there is a way to fix this. I've had this ever since i have downloaded this software. if anyone knows how to fix this that would be nice.
![Screenshot 2024-06-19 140031](https://github.com/dremin/RetroBar/assets/173306138/c2cc658d-71cc-4210-b8a4-602362931aab)

**Comment by dremin** [comment]
Right-click RetroBar.exe, choose Properties. Select "Unblock", then click OK. That should fix the warning!

**Comment by aalexx-z** [comment]
> Right-click RetroBar.exe, choose Properties. Select "Unblock", then click OK. That should fix the warning!

i have just done this but i'm still receiving this warning.

**Comment by dremin** [comment]
Oh, I just realized, it looks like the copy of RetroBar that is running at startup is coming from a zip file, which explains why. We need to remove that copy from startup:
1. Next time, click Run.
2. Open RetroBar Properties > Advanced and uncheck "Automatically start at logon", then click OK.
3. Exit RetroBar.

Now make sure you've extracted RetroBar.exe from the zip file, such as by dragging it to a folder. Right-click RetroBar.exe, choose Properties. Select "Unblock" if it's there, then click OK, and open RetroBar.exe.
Once it's open, open RetroBar Properties > Advanced and select "Automatically start at logon", then click OK. Now the unblocked exe will be the one that auto starts.

**Comment by dremin** [comment]
Closing as the previous comment has the steps to fix this.
