### ISSUE TITLE
errror 903

### ISSUE THREAD

**Issue by deviledonions** [dremin/RetroBar#866]
for some reason everytime i open my computer and retrobar activates, it gives me an error that says "7+ Taskbar Tweaker. Taskbar wasn't found (903)"
how do i fix this?
[no_taskbartweaker](https://github.com/dremin/RetroBar/assets/173621270/58252910-9242-4c59-87dd-9fe2c55df36a)

**Comment by dremin** [comment]
This error seems to be coming from 7+ Taskbar Tweaker. If you disable that program before starting RetroBar, you should stop receiving the error.

**Comment by dremin** [comment]
Closing as this is not a RetroBar issue.
