### ISSUE TITLE
Suggestion: make a file explorer equivalent to RetroBar

### ISSUE THREAD

**Issue by ComputeriFan431** [dremin/RetroBar#87]

**Comment by mrt505** [comment]
i think these projects should combine: open-shell and explorer++
it would be very nice. we can have complete look of windows xp( with classic theme). i miss that look so much.

**Comment by koblue** [comment]
Add a dash of Rainmeter.

Imagine a fully WinUI, easily skinnable without the complexity of xaml, 100% bespoke to the users whims Start Menu. 

I live in hope.

**Comment by dremin** [comment]
While I would absolutely be in support of a project doing this, I don't currently have time to do it myself.
