### ISSUE TITLE
Windows not staying "above" Win 95/98 taskbar

### ISSUE THREAD

**Issue by RobertLeeMich** [dremin/RetroBar#870]
![image](https://github.com/dremin/RetroBar/assets/13278272/e2f1aa5f-98ff-4a4b-a13b-b1862ced7c4c)
![image](https://github.com/dremin/RetroBar/assets/13278272/c51b61f6-8285-4bd0-be38-867e03bcc347)

Every window overlaps the taskbar. It's hard to tell what causes it because it seems to be random, I just notice it happening every now and again. But the "fix" is ticking auto-hide and then unticking it and it seems to be fixed for another few hours. Obviously I'd prefer if this didn't happen at all but that's why I'm posting this.

**Comment by dremin** [comment]
This will be fixed by the fix for #96.
