### ISSUE TITLE
Add Windows 10 theme

### ISSUE THREAD

**Issue by akamienski** [dremin/RetroBar#875]
With removal of classic taskbar in upcoming Windows 11 24H2 version, it'll be nice to have Windows 10 theme.

**Comment by ibillingsley** [comment]
If anyone is looking for this, I made a Windows 10 theme at https://github.com/ibillingsley/RetroBar-Themes

![Windows 10 Dark](https://github.com/dremin/RetroBar/assets/1782216/dc91edc4-ecc6-4193-a26c-72ae747f74bf)
