### ISSUE TITLE
QuickLaunch hotkeys dont work. 

### ISSUE THREAD

**Issue by AJolly** [dremin/RetroBar#882]
The hotkeys for quicklaunch shortcuts dont seem to work  win+1, win+2, etc.

**Comment by 111ebobo** [comment]
It's not a bug, they're wasn't working in that versions because quick launch is just a toolbar with a bunch of shortcuts

**Comment by dremin** [comment]
Closing as duplicate of #70.

**Comment by xoascf** [comment]
This feature is live: you have to enable it first in the **Advanced** tab of **RetroBar Properties**, and then press the win+number hotkeys to launch Quick Launch items or switch tasks.
