### ISSUE TITLE
Feature Request: Windows 7 Taskbar

### ISSUE THREAD

**Issue by WindowsNinetyTen** [dremin/RetroBar#884]
Can Windows 7 Taskbar be added to this program?

**Comment by WindClan** [comment]
#832 #785 #45 #771 #592 #584 #582 #581 #579 #577 #565 #507 #491 #490 #488 #485 #478 #465 #451 #215 #168 #80

can everyone stop asking for this
the devs wont add this, they were reluctant to add even Vista

**Comment by ikkqqstudio** [comment]
> #832 #785 #45 #771 #592 #584 #582 #581 #579 #577 #565 #507 #491 #490 #488 #485 #478 #465 #451 #215 #168 #80
> 
> can everyone stop asking for this the devs wont add this, they were reluctant to add even Vista

No

**Comment by dremin** [comment]
Duplicate of #45
