### ISSUE TITLE
request: Windows 7 theme needed

### ISSUE THREAD

**Issue by ikkqqstudio** [dremin/RetroBar#886]
because Windows 7 is out of support and we want to add windows 7 Taskbar @dremin

**Comment by Scratcher3** [comment]
then get a theme tool ;-;

**Comment by ikkqqstudio** [comment]
> then get a theme tool ;-;

what is that

**Comment by ikkqqstudio** [comment]
> then get a theme tool ;-;

I mean add Windows 7 Taskbar to Retrobar not theme

**Comment by ikkqqstudio** [comment]
#85 #884 #785 #577

**Comment by dremin** [comment]
Duplicate of #45

**Comment by ikkqqstudio** [comment]
fine

**Comment by WindClan** [comment]
#832 #785 #45 #771 #592 #584 #582 #581 #579 #577 #565 #507 #491 #490 #488 #485 #478 #465 #451 #215 #168 #80 #884

**Comment by AngrySonics** [comment]
it might be possible to make a custom Windows 7 theme. i haven't experimented with custom themes yet so i dunno for sure
