### ISSUE TITLE
[FEATURE REQUEST] Add 'windows key + number' shortcut to open pinned apps (quick apps)

### ISSUE THREAD

**Issue by deyvien** [dremin/RetroBar#891]
I don't know in what version windows this keyboard shortcut was implement, but at least from W10 you are able to press 'windows + number' to select a pinned app (called quick apps in retrobar). It'd be a cool add for those who use keyboard shortcuts for everything.

**Comment by 111ebobo** [comment]
This feature appeared in windows 7 when the pinning feature was changed from having a toolbar with shortcuts to what we see today

**Comment by dremin** [comment]
Closing as duplicate of #70.

**Comment by xoascf** [comment]
You can now press the Windows key + a number key to switch tasks (or open Quick Launch items), go to **RetroBar Properties** > **Advanced** tab to change and apply this behavior.
Check out the latest release here: https://github.com/dremin/RetroBar/releases.
