### ISSUE TITLE
Classic Shell does not show the start menu I set

### ISSUE THREAD

**Issue by imguest24897** [dremin/RetroBar#892]
Installed Classic Shell, opening menu start and - only Windows 11 start menu opens. Huh? How do I fix that?!

**Comment by GaryM99** [comment]
> Installed Classic Shell, opening menu start and - only Windows 11 start menu opens. Huh? How do I fix that?!

Classic Shell was retired from development before Windows 11 was even released, and its successor Open-Shell had issues with Windows 11 in its infancy. I recently upgraded to Windows 11 and I've experienced no issues with Open-Shell v4.4.191 and RetroBar v1.16.34, so my recommended fix for you is to switch to Open-Shell. You may even be able to export your old settings from Classic Shell and import them into Open-Shell.

Note to Sam Johnson... RetroBar is an AWESOME improvement over the Windows 11 taskbar. Thanks very much!!!

**Comment by imguest24897** [comment]
Installed Open-Shell, and it really worked. Closing this issue.
