### ISSUE TITLE
System + System XP theme colorization missing

### ISSUE THREAD

**Issue by Crunch64** [dremin/RetroBar#900]
These themes do not appear to be using my system colors set in personalization. It instead defaults to a bright white, as shown below. 
![RetroBar_LGTMs1BMAH](https://github.com/user-attachments/assets/c7fe4749-1ddb-46e7-9376-9dac7d193643)

Tested on 2 Windows 10 machines, both have ticked to show coloring on the taskbar.

**Comment by dremin** [comment]
Out of the box, Windows 10/11 don't have a UI for changing the classic system colors. You can either change them in the registry (`HKCU\Control Panel\Colors` or `HKCU\Control Panel\Desktop\Colors`) or use a GUI tool such as [WinClassicThemeConfig](https://gitlab.com/ftortoriello/WinClassicThemeConfig).

**Comment by Crunch64** [comment]
Thank you for the clarification! I'd like to see a basic implementation of pulling your modern color setting added someday. I've also found [WinPaletter](https://github.com/Abdelrhman-AK/WinPaletter), which intuitively comes loaded with loads of classic system presets for anyone else looking.
