### ISSUE TITLE
Extra Space at top of XP Blue Taskbar v1.16

### ISSUE THREAD

**Issue by Pickleman223** [dremin/RetroBar#904]
![43124162f6799f3ac52d89c9e23af56f](https://github.com/user-attachments/assets/56f1d82c-0841-4557-a9e7-af78ad65a228)
Does anyone know how to get rid of this extra space at the top of the XP Blue taskbar? I don't know if this is a bug with RetroBar or with my computer.

**Comment by dremin** [comment]
Right click and lock the taskbar :)

**Comment by Pickleman223** [comment]
> Right click and lock the taskbar :)

Thank you :)
