### ISSUE TITLE
[Question] Does RetroBar change fonts based on the skin used?

### ISSUE THREAD

**Issue by TheDwellerInDarkness** [dremin/RetroBar#920]
I've been using RetroBar on and off for a bit and I've never been able to tell, but does the font change depending on the skin selected? From what I've been reading, Windows 98 uses MS Sans Serif while Windows XP (the blue themed version) uses Tahoma, and I can't really tell if RetroBar uses those fonts when the skins are selected. If it doesn't, I think it would make for a good feature.

**Comment by dremin** [comment]
Yes, RetroBar does change fonts according to the selected theme.
