### ISSUE TITLE
Retrobar causes explorer.exe crashing and restarts over and over after u restart explorer.exe! (11 24H2)

### ISSUE THREAD

**Issue by RedDragonTix** [dremin/RetroBar#927]
When u try to restart explorer.exe with retrobar running, it causes crashes and flashes but when u close retrobar.exe, nothing happens!

**Comment by tamarindojuice** [comment]
I can confirm, same behaviour here. 
Windows 11 24H2

**Comment by manaphychu** [comment]
Me too

**Comment by dremin** [comment]
Closing as duplicate of #457 (which will be fixed in the next version).
