### ISSUE TITLE
Small start button image (custom themes)

### ISSUE THREAD

**Issue by Callu342** [dremin/RetroBar#94]
I was making a custom theme and then I changed the start button image and then it looked like this
![image](https://user-images.githubusercontent.com/76173715/133473214-47a72d3e-3010-4a93-bfd6-efc8d22f3c12.png)

it also looks like this when the mouse hovers over/clicked on
![image](https://user-images.githubusercontent.com/76173715/133473909-483cef44-2e51-4e1f-a4a2-a82715fb9e94.png)

is there a way to fix this?

(the image has the same dimensions as the original btw)

**Comment by dremin** [comment]
The original image is 3 times the width of the button. When you say your image is the same size, is it that, or is it the size of the button? I also wonder if it has to do with the DPI set on the image. If you're able to upload it here, I can take a look.

**Comment by Callu342** [comment]
i built it off of the image from the source code of retrobar

heres the image
![startxpsimplebluebutton](https://user-images.githubusercontent.com/76173715/133496423-ffa3ebbb-1b31-452a-82d3-3c593087246d.png)

**Comment by xoascf** [comment]
It is probably a DPI-related problem, since the values of the start button image coordinates in the theme are absolute, rather than relative...
