### ISSUE TITLE
Cannot move taskbar to second display

### ISSUE THREAD

**Issue by aaronbeecham** [dremin/RetroBar#963]
I'd like to move the taskbar to my secondary display. Not my primary. Since I want games to open on my primary display while also seeing my taskbar on my secondary display.

No, I don't want a taskbar on every single display.

I just want the taskbar on my secondary display only.

**Comment by xoascf** [comment]
Yes, it would be nice to be able to choose which displays to show the taskbar on.

**Comment by dremin** [comment]
Closing as duplicate of #646.
