### ISSUE TITLE
Issue - Retrobar crashes explorer on explorer startup

### ISSUE THREAD

**Issue by ThaBluNate** [dremin/RetroBar#964]
Continuation to issue #313 (Issue - Retrobar crashes explorer constantly in windows 11 beta insider).
Since I have started using retrobar again, here's my (more refined) experience with this crash:

Trigger by restarting explorer while retrobar is active. That's it.
Retrobar seems to crash explorer on startup. This is a retrobar-exclusive issue.
Probably 'fixable' by closing retrobar automatically if it's detected that explorer is closed.

**Comment by dremin** [comment]
@ThaBluNate The fix for this I referenced in the previous issue is available in [the latest build](https://github.com/dremin/RetroBar/actions/runs/12064288618/artifacts/2248321339), could you please try it and let me know if this resolves the issue for you?

**Comment by ThaBluNate** [comment]
> @ThaBluNate The fix for this I referenced in the previous issue is available in [the latest build](https://github.com/dremin/RetroBar/actions/runs/12064288618/artifacts/2248321339), could you please try it and let me know if this resolves the issue for you?

Nope! Doesn't seem to be fixed, I just tested that download link you sent me.

**Comment by ThaBluNate** [comment]
I'm just gonna keep this closed cause I forgot I already made this an issue, I'll probably paste the contents of this into #457
