### ISSUE TITLE
Pinned to Taskbar programs won't appear.

### ISSUE THREAD

**Issue by ILoveMugRootBeer** [dremin/RetroBar#970]
Hi, I don't recall when, but my apps and programs pinned to the taskbar, ie, Chrome, and a few game launchers, just, vanished. It's not the icons missing, the entire section for pinned items is gone. I attached an image of where the pinned to taskbar apps should be, but aren't. If I exit Retrobar, they're there on my normal Windows 10 taskbar.
![Screenshot 2024-12-01 123036](https://github.com/user-attachments/assets/f376c17b-97d2-4168-bdce-d19b0ae629f6)

**Comment by GaryM99** [comment]
Is it possible that you inadvertently unchecked the "Show Quick Launch" option box in the Retrobar properties dialog?
![RetrobarTaskbarQuickLaunch](https://github.com/user-attachments/assets/0568e0f0-cdb7-4335-873b-dbd092bd4a08)

**Comment by dremin** [comment]
> Hi! I believe you may be right? I selected the Show Quick Launch, but currently, theres nothing visible but something did change.

@ILoveMugRootBeer Next to the "show quick launch" checkbox, there's a "select location" button. If you click this, you should be able to select the directory that has your shortcuts. The default is `%appdata%\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar`. You can paste that in and click Select Folder, and it should have your standard taskbar shortcuts again.

**Comment by ILoveMugRootBeer** [comment]
Thank you! It worked! Sorry I didn't respond, I got busy with a lot of stuff and forgot to check this.

> > Hi! I believe you may be right? I selected the Show Quick Launch, but currently, theres nothing visible but something did change.
> 
> @ILoveMugRootBeer Next to the "show quick launch" checkbox, there's a "select location" button. If you click this, you should be able to select the directory that has your shortcuts. The default is `%appdata%\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar`. You can paste that in and click Select Folder, and it should have your standard taskbar shortcuts again.
