### ISSUE TITLE
Request for several useablity features

### ISSUE THREAD

**Issue by Australian-Infomaniac** [dremin/RetroBar#98]
This is a great app for those of us who found OS like XP far more intuitive.

In particular on 10 I highly dislike:
- the whole new 'feature' of putting items in vertical menus
- the fact that when you pin things (which is the easiest way to access them), new items open next to other windows of that application, rather than the END of the taskbar, which is more natural - and requires less searching every time
- combining of items: again, harder to find than just putting new items at the end
IE I always find myself searching and struggling to find my items under Win 10!

In other words, like XP I want:
- to be able to see all the names of my windows laid out simply in front of me
- new items to open nice and simply at the END of the taskbar where i can easily FIND them!

____________________________________________

Your app does alot of this but there are still a couple of things that would be really fantastic and take it close to the most productive way of using the old XP taskbar.

1. 'TASKBAR SHUFFLE'...is one of the first programs I used to install. It allows you to drag the items around the taskbar WHEN YOU WANT TO. When you are working on a big project, this is an absolute necessity. I know that wasn't native with XP but it should have been (which is why its in subsequent OS). Is there some way you could add an option to do this?

2. Its just a bit small: not very 'high'/'deep'. Ive used XP recently (I have it on dualboot) and Im sure its a BIT bigger than this! Its a bit fiddly to access. Could you make it a bit 'taller'?
a) Related to this, I notice that more items on the taskbar just make each one smaller. 
One thing you could do on XP was PULL the taskbar up, giving it several rows.
That would be SO handy ! 
Sometimes you have more interest in seeing what windows you have than having loads of screen real estate !

3. I notice that perhaps also you can't create a  taskbar toolbar? (IE a vertical menu that springs up from the taskbar). Adding this would make it alot more functional.

If you were to add all these things, It would be just as functional as my old XP taskbar.

_______________________________________________________________
FWIW, for others who find the new Windows 10 behaviours above confusing, I did find a way to replicate Xp behaviour
Install 7+ Taskbar Tweaker and set

Grouping > dont group
Combining > Dont combine

And have NO pinned items.

Instead use a pop-up toolbar menu as described above.

Its a bit annoying not to have the more easily accessible pinned items, but you can use the toolbar menu.

I also use Launchy which is very helpful.

**Comment by dremin** [comment]
Open windows drag ordering is a duplicate #19, which should be fixed in the next release.

**Comment by IoIxD** [comment]
I want to second combining windows, I know it's not historically accurate but
- neither are the taskbar icons or the ability to turn on font smoothing
- it really helps for smaller screens, especially if you're not gonna add the ability to hide window titles.

**Comment by dremin** [comment]
The remaining items in this are duplicates:
- Taskbar height: #14 
- Toolbars: #42
