### ISSUE TITLE
When exiting RetroBar, it automatically minimizes the task bar 

### ISSUE THREAD

**Issue by papujarapy** [dremin/RetroBar#99]
When exiting RetroBar, it automatically minimizes the task bar.
By not having Windows activated, it does not allow the possibility of returning so that it is not minimized.

Sorry for my English, Spanish my first language

**Comment by xoascf** [comment]
I was going to report exactly the same: "When exiting RetroBar, the Windows taskbar appears hidden as default.", but I have tried with the new version and it works, the taskbar is no longer hidden.
Try with this version: https://github.com/dremin/RetroBar/suites/3772463836/artifacts/92845302

**Comment by papujarapy** [comment]
yes, already solved with the new version !!! Brilliant

**Comment by papujarapy** [comment]
I still have the same problem :(, I tried the version, the taskbar continues to be hidden, and since my Windows is not activated, I cannot from that option

**Comment by xoascf** [comment]
Oh, it may be because I recently upgraded to Windows 11, that new version uses a different type of taskbar, or also because I'm testing [StartIsBack](http://startisback.com/tbd/), either of those two things may have fixed the problem for me.

**Comment by papujarapy** [comment]
I am using Windows 10 without activating the product

**Comment by xoascf** [comment]
Extract [RestoreTaskbar.zip](https://github.com/dremin/RetroBar/files/7199467/RestoreTaskbar.zip) and run the .ps1 with PowerShell, or follow this guide:
https://www.tenforums.com/tutorials/23817-turn-off-auto-hide-taskbar-desktop-mode-windows-10-a.html

**Comment by papujarapy** [comment]
Following the guide I was able to reset the taskbar, Thanks!
